### ISSUE TITLE
Wordpress plugin

### ISSUE THREAD

**Issue by danielfriis** [space10-community/conversational-form#10]
Easy implementation for non-techies for Wordpress

**Comment by steveraffner** [comment]
Non techie volunteer to test it and feedback :)

**Comment by poondq** [comment]
will be the first to test out.

**Comment by steveraffner** [comment]
awesome ! :)

**Comment by laxmin** [comment]
Another volunteer non-tech here ready to test drive.

**Comment by janfsauer** [comment]
ready to test drive it here. non-tecchie

**Comment by artneo8** [comment]
Ready to test it too! ;)

**Comment by AdrenalineX** [comment]
Oh oh, me to!

**Comment by tadinski** [comment]
me pleaasee 😀

**Comment by Nonor2188** [comment]
Hey there! 
I'm building a WordPress plugin to use CF! I'll let you know when ready for testing :-)

**Comment by danielfriis** [comment]
@Nonor2188 Super excited to hear that! Let me know if we can support :)

**Comment by arnaudpaul21** [comment]
Hey there @danielfriis , @steveraffner , @poondq , @tadinski , @laxmin .

Just released first version of the Wordpress plugin here: https://github.com/arnaudpaul21/conversational-form-wordpress-plugin

Enjoy and feel free to feedback :-)

**Comment by felixnielsen** [comment]
@arnaudpaul21 very nice! Please see latest PR merged into [develop](https://github.com/space10-community/conversational-form/tree/develop) it contains the formless feature, which could have interest for your Wordpress plugin. It's basically a way to build and instantiate Conversational Form without a `<form>` element, JSON only. See the [formless example](https://github.com/space10-community/conversational-form/blob/develop/examples/formless.html) and associated [JSON](https://github.com/space10-community/conversational-form/blob/develop/examples/files/formless.json) file.

**Comment by patrickcoombe** [comment]
am also willing to beta test this, contribute to back end code or write documentation
