### ISSUE TITLE
form displays briefly before overlay initiates

### ISSUE THREAD

**Issue by sull** [space10-community/conversational-form#107]
I was adding a `display:none` to the form which worked but now when trying the conditional branch,  this fails due to inability to "focus". Removing the `display:none` form style resolves the issue but the form is displayed for a second before the CF UI overlays.

Thoughts?

**Comment by sull** [comment]
seems to be ok when using build files as opposed to dist files.

**Comment by alok108** [comment]
I added opacity: 0; to the form instead. This seems to be a better solution.
