### ISSUE TITLE
Update user image after gender choice

### ISSUE THREAD

**Issue by willwalker** [space10-community/conversational-form#108]
I'm trying to change the user image according to the genre chosen. If a man is an image and a woman is another image. Can someone help me?

**Comment by felixnielsen** [comment]
hi @willwalker please see this [jsbin](https://jsbin.com/tohewanika/1/edit?html,js,output) it shows how to update a user-image from an uploaded image, you should not have to change much to accommodate your scenario.

**Comment by willwalker** [comment]
I did it differently.

I looked at the plugin until I found where it takes the values. I added a condition and a variable to change the user's image like this:

`n.prototype.onClick = function(t) {
this.onChoose();
if(this.el.innerText.trim() == 'Masculino') {
$('.user thumb').css({ 'background-image' : 'url(images/boy.png)' });
CustomImageUser = 'images/boy.png';
}else if(this.el.innerText.trim() == 'Feminino') {
$('.user thumb').css({ 'background-image' : 'url(images/girl.png)' });
CustomImageUser = 'images/girl.png';
}
}`

And I used this CustomImageUser variable in the template, creating an image exchange condition like this:

`n.prototype.getTemplate = function() {
return '<cf-chat-response class="' + (this.isRobotReponse ? "robot" : "user") + '">\n\t\t\t\t<thumb style="background-image: url(' + (this.isRobotReponse ? this.image : (CustomImageUser ? CustomImageUser : this.image)) + ')"></thumb>\n\t\t\t\t<text>' + (this.response ? this.response : n.THINKING_MARKUP) + "</text>\n\t\t\t</cf-chat-response>"
}`

And so I was able to change the user's image according to their chosen genre in the input [type = "radio"].

**Comment by abhinav118** [comment]
@willwalker please can you share a jsbin. I'm looking into the same issue

**Comment by willwalker** [comment]
Sure you can download here: https://mega.nz/#!mMwy1a7B

**Comment by demian1985** [comment]
@willwalker Great work! Can't open the link without a key. Are you able to share it differently?

**Comment by willwalker** [comment]
https://mega.nz/#!mMwy1a7B!EexfzIXNdSZwlHufZ_uEtuMpXi_mu6zXSDTODpdTVwg
