### ISSUE TITLE
A few UI things

### ISSUE THREAD

**Issue by tipcircle** [space10-community/conversational-form#109]
Hello, I've been playing around with this for a couple days and it's brilliant, really great idea.

Just a few UI things from a user standpoint (my own at least.)

Don't show the user's bubble until they make a choice or type input.
Don't show the input bar unless the answer requires textual input.
Some sort of indication the data is being sent at the end.

If you take a look at https://azumbrunnen.me/ the UI is brilliant and seems very human.

Thanks for releasing the code, beautiful work.

**Comment by felixnielsen** [comment]
@tipcircle thanks for your feedback! Thoughts on your feedback.
1. We had logic before as you described, but it seemed to static as you only had the "thumbnail" showing before typing anything. So we need some kind of indication, we are up for suggestions.
2. This one as you mention in the other issue is related to filtering of input buttons, but I will implement some logic that removes input bar if all buttons are visible.
3. This is per. design up the implementor. But in v.0.9.3 there is a subtle indicator at the submit button showing a load state (spinning outline)

Agree, azumbrunnen is lovely!

**Comment by danielfriis** [comment]
1. Agree. Up for suggestions :)
2. It's important that a user is able to complete a CF form without having to remove your hands from the keyboard. Could be optional though.
3. We could look at more obvious indicators. Up for suggestions.

**Comment by tipcircle** [comment]
1: I guess I see this like FB Messenger bots. No bubble or user thumb until user sends a message. There are either answer buttons or text input, when the user sends, the bubble and thumb show. I think it depends on what the user is used to and most users have FB messenger and use it.

2: Optional would be cool. 

3: Maybe a typing indicator then a "finished" or "thank you" message?

Again, this is just from my own standpoint as a user and some things I found confusing.

**Comment by tipcircle** [comment]
Another thing I wonder about is why not start the conversation at the top of the form container?

**Comment by felixnielsen** [comment]
@tipcircle use [`cf-context`](https://github.com/space10-community/conversational-form#optional-attributes) for the form element if you wan't to append it into the form element.

**Comment by tipcircle** [comment]
Right, I mean have the "bot" opening message start at the top of whatever container it's in. Probably just a css thing?

**Comment by felixnielsen** [comment]
@tipcircle correct, you can align elements to top by setting:
`.. .conversational-form-inner{
    justify-content: flex-start;
}
`
