### ISSUE TITLE
Logic and Piping

### ISSUE THREAD

**Issue by nearkingdom** [space10-community/conversational-form#11]
It would be great to build in some kind of logic response and piping. 

**Question 1: How do you like your eggs in the morning?**
A - Fried Sunny Side Up
B - Poached
C - Scrambled

**Question 2: Are you** 
A: Male
B: Female?

```
if (question 1:A AND 2:A Answered ) {
 "Sir, you eat the breakfast of champions!"
else if (question 1:A AND 2:B Answered ) {
 "Madam, you eat the breakfast of champions!"
} else if (question 1:A Answered) { 
You eat the breakfast of champions!"
}
```

**Comment by felixnielsen** [comment]
hi @nearkingdom please see my answer here; [1. "100% control"](https://github.com/space10-community/conversational-form/issues/18#issuecomment-263791800), would that work?
A 3rd solution could also be more in the lines of what you have written as the example code. Where defining a if, else mapping to the existing tags and passing that as an argument when creating the ConversationalForm instance. A tool that would allow you to select the tags and do the mapping visually, outputting the code structure below could be interesting to explore.

```
if (question 1:A AND 2:A Answered ) {
 #id-to-element-A-A -> show
else if (question 1:A AND 2:B Answered ) {
 #id-to-element-B-B -> show
} else if (question 1:A Answered) { 
#id-to-element-A -> show
}
```

**Comment by nearkingdom** [comment]
I like the idea of mapping the logic visually.

**Comment by danielfriis** [comment]
#18

**Comment by LeGfrey** [comment]
If you want, I made a PR which fix this "issue". Don't hesitate to check it and post your feedback :smile: 
https://github.com/space10-community/conversational-form/pull/42

**Comment by felixnielsen** [comment]
Please see latest [release](https://github.com/space10-community/conversational-form/releases/tag/v0.9.4) with Conditional Flow and example [value-piping](https://space10-community.github.io/conversational-form-docs/conditional-flow.html)
