### ISSUE TITLE
Multiple lines by typing enter

### ISSUE THREAD

**Issue by MediacraftFR** [space10-community/conversational-form#110]
Hi,

Once again : Great work espacialy for the 0.9.3 pre release and the form less feature.

I saw few weeks ago that multilines feature was added but it's not obvious for our users to add new lines by typings shit + enter. I would like to type just enter when it's a multiline input to add line and of course to keep passing to new question by typing enter when it's a simple input.

In some case it's important to easily invite user to enter severals lines

What do you think about that ?

Regards

**Comment by danielfriis** [comment]
Hi @MediacraftFR,

Thanks for the comment and valid consideration. However, I would argue the the prevalent approach in chat-interfaces is for a shit-enter to equal new line. Just noticed that Facebook Messenger discontinued the ability to choose and only allows shit-enter for new lines.

**Comment by MediacraftFR** [comment]
Hi @danielfriis ,

That's correct for messenger and you're right it's the better approach for a good chat experience. 

But the problem is if a user want to say severals things he types a first sentence and type Enter (not shift+enter) the bot will continue to the next question without letting the user finish to answer completely to the previous question. I know the user can update by clicking on a previous answer but it's not obvious all users.

Do you see my point ?

Regards,

**Comment by danielfriis** [comment]
Get you point 100%. But I will still argue that the prevalent UX is to have shift + enter do the new line. This is also the approach that Typeform takes. Also, if this wasn't the case, all inputs except multiline would have submit by enter, which I believe would be counterintuitive.

However, we will definitely keep you suggestion in mind and consider adding an option to do the reverse.

**Comment by MediacraftFR** [comment]
Ok i agree ...
However there is a "bug" to fix in your CF when you edit a multilines user answer.

Imagine you type multilines input with shift+enter like : 
"qwer
ty

yolo"

when you edit this answer you will get on the input : 
"qwertyyolo"

The lines breaks arent't kept :/

Can you fix this ?

Thanks

**Comment by MediacraftFR** [comment]
Hello conversational form team :)

Have you reproduced my issue ? 

Regards

**Comment by danielfriis** [comment]
@felixnielsen can you take a look?

**Comment by felixnielsen** [comment]
@MediacraftFR @danielfriis I had a look at this, and input tag does not natively support multiline, this is the core problem. See [example](https://jsbin.com/binohudapo/edit?html,js,output) first element is a <textarea, here you can add multi lines, submit and re-edit multilines, but this is not the case with the second field which is a <input field.

From my side the issue seem to be that <input fields have multiline support from CF side. They shouldn't. Let me know your thoughts.

**Comment by felixnielsen** [comment]
should prevent multiline when reference tag is of type `input`
