### ISSUE TITLE
API call and redirect to cf-form with previous chat history

### ISSUE THREAD

**Issue by abhinav118** [space10-community/conversational-form#111]
Firstly @felixnielsen and team, Kudos on your effort and the overall product. 🙌👍

I am finding it hard to add an API redirect to that point in chat where we left off from the cf-form, based on a click event.

To give you an example we are trying to add Facebook login to cf-form , something like this [example/manual-start.html](https://github.com/space10-community/conversational-form/blob/master/examples/manual-start.html) and after the user logins, we would like to redirect him to the chat, where user left off.

Please can you help us with this? Is it feasible with current conversation-form. If not can you suggest any hack regarding the same?

Appreciate your help!

**Comment by felixnielsen** [comment]
hi @abhinav118 thanks! :) I understand you correctly that the user opens a different window, for the facebook flow or do you redirect to user from cf, login and back to cf?

**Comment by abhinav118** [comment]
yeah.. we could do it may hacking and redirecting to new html with previous questions and answers..
Any easier method is much appreciated.

**Comment by felixnielsen** [comment]
@abhinav118 jsbin and facebook API does not play nicely together, but this [example](https://jsbin.com/mahureloco/1/edit?html,js,output) should get you all the way in a none iframe solution. Let me know how it goes.

**Comment by felixnielsen** [comment]
@abhinav118 if above code-example did not work for you, then you are also able to setup the facebook callback url to contain a querystring that you can read and exclude the field in the form when the user returns, all in all it will require some custom code (client or server).
