### ISSUE TITLE
Remove auto focus

### ISSUE THREAD

**Issue by willwalker** [space10-community/conversational-form#112]
I need to remove auto focus. Because on cell phones it is bad to read the text because every time the keyboard goes up. I want to remove auto focus every time the user responds. Can someone help me?

**Comment by felixnielsen** [comment]
hi @willwalker you can apply `cf-prevent-autofocus` to your form tag, like so: `<form id="my-form-element" cf-form cf-prevent-autofocus>`

**Comment by felixnielsen** [comment]
you also want to remove when the user jumps to the next question?

**Comment by willwalker** [comment]
Exact!

**Comment by felixnielsen** [comment]
@willwalker and you tried `cf-prevent-autofocus`? Just had a look at the code-base and it does check for this at every flow update.

**Comment by willwalker** [comment]
The form has this attribute and only prevents focus when it starts, but when I answer the question it selects the field again.

**Comment by felixnielsen** [comment]
@willwalker fix coming up

**Comment by danielfriis** [comment]
Did this remove auto focus altogether? I think it's great for desktop that the user doesn't have to select the input field again everytime they've answered a question.

**Comment by willwalker** [comment]
But on cell phone it's not cool and you can choose whether you want that autofocus or not. Just add the attribute or not.

**Comment by danielfriis** [comment]
Yes got it. Nice fix 👍

**Comment by xblix** [comment]
Anyway to keep autofocus on some input and remove on others.
That's be great if we can have a full setting for autofocus or not any input separated
cf-no inputfocus on input field by example :)

**Comment by xblix** [comment]
Any way to disable autofocus for first question and back autofocus for all other ones? :)

**Comment by demian1985** [comment]
Hi, I am looking for a similar solution for cf-prevent-autofocus in a multiple select attribute. However, it's not working. I added this: `<select multiple id="cf-prevent-autofocus"`. Am I doing something wrong?

The first picked answer on a multiple select question opens the keyboard on a mobile phone, which is not ideal.

**Comment by jenssogaard** [comment]
@demian1985 Try doing <select multiple cf-prevent-autofocus /> instead of adding it as the ID value.

**Comment by demian1985** [comment]
@jenssogaard Sorry I forgot to mention, without the ID value was my first approach and did not work. It's in CF7; is the cf-prevent-autofocus activated there?

**Comment by jenssogaard** [comment]
@demian1985 hmm, not sure what you are asking, but CF7 and our projects has nothing to do with one  another so I don't think I can answer your question.

**Comment by demian1985** [comment]
Strange, so you guys did not create this [add on](https://wordpress.org/plugins/cf7-bot-forms-add-on/) for CF7? 

Despite this, I have removed it and continued with building a raw form, as there were more responsive issues with add on plugin.

**Comment by jenssogaard** [comment]
@demian1985 no, that is a community effort. I don't know about the compatibility of that plugin. Best of luck.
