### ISSUE TITLE
Remove the input bar when text input is not required

### ISSUE THREAD

**Issue by tipcircle** [space10-community/conversational-form#114]
How would I remove the input bar when text input isn't required?

It doesn't seem to make sense to have it along with input buttons.

If I type in an answer instead of clicking a button and make a typo like "seveloper" instead of "developer", there is no correction mechanism and the only way to go back is to click the previous answer, which isn't very apparent.

Make sense?

Thanks

**Comment by MediacraftFR** [comment]
Hi,

+1 I agree with you. I was looking for the same feature.

Regards

**Comment by felixnielsen** [comment]
@tipcircle input buttons, you mean radio and check buttons? If yes, then how are you able to submit "seveloper"?

**Comment by tipcircle** [comment]
Yes, if there are radio/check buttons to tap for the input/answer, then maybe not allow text input along with them. Don't have 2 different ways to enter the same data.  Hope that make sense.

**Comment by tipcircle** [comment]
Here's an interesting implementation where they don't hide the input bar, but disable it when buttons are available. http://lucasbassetti.com.br/react-simple-chatbot/#/docs/form

**Comment by def-mycroft** [comment]
+1 - it confuses users when there is a text box but there are a set of choices.
