### ISSUE TITLE
Adding a robot message based on user input (not a form question)

### ISSUE THREAD

**Issue by maringerov** [space10-community/conversational-form#115]
Hey, I want to have a robot message appear in the middle of a flow of questions which is triggered based on a user's response to the previous question. Here is an example I tried to illustrate:

- Q: Are you a robot?
- A: No -> Proceed to next question
- A: Yes -> Robot (custom message): Please find a human -> then proceeds to next question in flow
- Next question...

I looked at the examples and the wiki but wasn't able to find a solution.

Would really appreciate if someone encountered the same issue to shed some light :)

Thanks

**Comment by amaranter** [comment]
I was looking for that, I would also like to know how to work with conditional flows.

**Comment by felixnielsen** [comment]
hi @maringerov as I read your question, then you would like for "A: Yes -> Robot (cus..." to show a message before continuing the flow.
So both `No` and `Yes` ends up at {Next question} (so no conditional flow), is that correctly understood?

Or should `No` go to {next question **A**} and `Yes` to {next question **B**}?

**Comment by amaranter** [comment]
@felixnielsen; Your commit about [Conditional Flow](https://github.com/space10-community/conversational-form/pull/105) are available in master branch? Do you have any example using conditional?

**Comment by maringerov** [comment]
Hi @felixnielsen yes, you understood correctly - there is no need for a conditional flow - no matter the answer the user is redirected to the next question. Only in one case (if 'yes') I would like to add a cutom robot message before the question is loaded.

**Comment by maringerov** [comment]
Hi @amaranter, there is an example here https://github.com/space10-community/conversational-form/wiki/Conditional-Flow

**Comment by felixnielsen** [comment]
@maringerov i this what you are after? https://jsbin.com/yihujuneha/edit?html,js,output

**Comment by felixnielsen** [comment]
@amaranter @maringerov maybe conditional flow can help as well, latest [release](https://github.com/space10-community/conversational-form/releases/tag/v0.9.4) see this [example](https://space10-community.github.io/conversational-form-docs/conditional-flow.html)

**Comment by maringerov** [comment]
Thanks @felixnielsen the JS Bin is exactly the behaviour I was trying to get :) +1
