### ISSUE TITLE
Enable HTML in questions

### ISSUE THREAD

**Issue by ok-MicroTech** [space10-community/conversational-form#116]
Hello

Is it possible to use HTML in the questions or at least allow styling (bold, underline etc.)

**Comment by tipcircle** [comment]
There is this example in click-edit-previous-answer.html

`<input type="text" cf-questions="Input field, once you submitted your answer, you can click your input to <strong>change</strong> it" name="text" value="">`

**Comment by felixnielsen** [comment]
@ok-MicroTech jsbin https://jsbin.com/namobububu/1/edit?html,js,output showing tags and how you can apply your own styling.
