### ISSUE TITLE
Conditional Flow : does it work in formless version?

### ISSUE THREAD

**Issue by rimx** [space10-community/conversational-form#117]
Hi, 
I was just wondering if the conditional workflow works in formless version too?
I have tried the following and looks like the condition was not applied..
```
		{
			"tag": "input",
			"type": "text",
            "name": "q1",
			"value": "",
            "required" : "required",
			"cf-questions": "type MJ"
            
        },
		{
			"tag": "input",
			"type": "text",
            "name":"q2",
			"value": "",
            "required" : "required",
			"cf-questions": "you sure you entered MJ",
            "cf-conditional-q1":"MJ"
		}
```
anyone tried this before?

**Comment by felixnielsen** [comment]
@rimx not yet, conditional will be rolled out this week. We encountered a small issue with it when going back to edit previous answers. But to answer your question, then, Yes, conditional and formless will work together.

**Comment by felixnielsen** [comment]
@rimx please have a look at latest release, conditional flow and formless are now under the latest release tag [0.9.4](https://github.com/space10-community/conversational-form/tree/v0.9.4)

**Comment by rimx** [comment]
@felixnielsen - thank you very much for the update. I have just tested the conditional flow and its working perfect (y).
