### ISSUE TITLE
Chaining questions from a single input tag?

### ISSUE THREAD

**Issue by FranckSCTV** [space10-community/conversational-form#118]
Hi,
I see that you can shuffle between several questions by using the pipe separator but I would also like to split questions into several chunks so that one question can use several bubbles. Is that possible? This would increase readability for long questions and make the whole experience a little bit more human-like.
Thanks in advance!

**Comment by felixnielsen** [comment]
@FranckSCTV I like this idea!
Maybe **&&** could work for this?

`cf-questions="Hello there&&Please choose an option|Hello&&Those choices"`

Would result in two robot speech bubbles.

What do you think?

**Comment by FranckSCTV** [comment]
@felixnielsen , GREAT, this is exactly what I had in mind :)

**Comment by EtgolWalkor** [comment]
+1 for this. Any chance of moving it up the queue?

**Comment by bellamystudio** [comment]
+1 for this as well. Multiple bot speech bubbles would be great for conversational flow

**Comment by danielfriis** [comment]
:+1
