### ISSUE TITLE
Weird IE behaviour

### ISSUE THREAD

**Issue by AfaanBilal** [space10-community/conversational-form#119]
Hi,

On Windows 10, IE 11, the chat area doesn't scroll so the input box as well as the option inputs are hidden after the first two questions.

Update: The input boxes and the options do show up (the upper half of them anyway) but after a wait time of about 45 seconds!

Any fix?
Thanks!

**Comment by felixnielsen** [comment]
@AfaanBilal flex-box and IE11, especially using flex-end, will see if I cannot make a hack to make IE11 align a bit better.

Regarding your wait time, then I just did a test with 300 input items here, https://jsbin.com/xumubariju/1/edit?html,output it's running instant for me. Can you please elaborate on your setup and what you are trying to archive?

**Comment by AfaanBilal** [comment]
Hi @felixnielsen 
I tried your form and I'm facing the same issue again. Please see the attached screenshot. Notice how there is no input box.
![ie](https://cloud.githubusercontent.com/assets/1507671/26006426/f2d2e346-3759-11e7-9c45-2379ed78d937.jpg)

**Comment by rimx** [comment]
@AfaanBilal, 
i was facing the same issue in IE11(WIN7) and found out IE can't handle the 
```
cf-chat scrollable {
....    
height: auto;
}
```
If you set the height to a fixed height i.e. 300px the scrollbar and the input box stays at the screen. Please give it a try and see if it works for you. If you got any better workaround please share that as well.

**Comment by AfaanBilal** [comment]
Hi @rimx ,
The fix worked for me (not perfect but pretty well).
Thanks a lot for this!

**Comment by ivanguimam** [comment]
Guys, I faced the same issue, and the solution I've found is set the height of scrollable tag, and use "vh" to make this.

`scrollable { height: 79vh; }`

Hope it helps

**Comment by felixnielsen** [comment]
@ivanguimam next release, hopefully released today, will fix this.
