### ISSUE TITLE
Form inputs remain on page

### ISSUE THREAD

**Issue by tipcircle** [space10-community/conversational-form#122]
Can anyone tell me what I might be doing wrong here?

I am getting the conversational form, but the regular form elements are still on the page behind the cf form.

This is in a Wordpress site.

I'm calling the script in the head like this:
`<script type="text/javascript" src="https://cf-4053.kxcdn.com/conversational-form/0.9.4/conversational-form.min.js" crossorigin></script>`

Here is the form code, basically copied and pasted from examples:

https://gist.github.com/tipcircle/5a72fc9c86dc6eae9113b9255d03a1c4

And instantiating it like this:
`<script>
	(function(){
		var conversationalForm = new cf.ConversationalForm({
			formEl: document.getElementById("survey-bot"),
		});
	})();
</script>`

Here is the result:

![cf-screen](https://cloud.githubusercontent.com/assets/10174/26038954/c056c930-38e1-11e7-9ec1-e6b4f2392f3b.jpg)

**Comment by felixnielsen** [comment]
hi @tipcircle you need to define the context element when instantiating Conversational Form. the Context element allow you to control where CF will be injected and how it will look (like placing it on top of your <form>)

**Comment by tipcircle** [comment]
Hi @felixnielsen I think I tried that before so I tried again like this

`<script>
	(function(){
		var conversationalForm = new cf.ConversationalForm({
			formEl: document.getElementById("survey-bot"),
                       context: document.getElementById("cf-context"),
		});
	})();
</script>`

And:
`<div id="cf-context" role="cf-context" cf-context></div>`

But I'm still seeing the same results. The cf form appears, but the form elements are still showing behind it.

Thanks

**Comment by felixnielsen** [comment]
@tipcircle CF will not replace your old form. You need to hide/remove that your self.

**Comment by tipcircle** [comment]
Ahhh, thank you.
