### ISSUE TITLE
Windows 7 Safari 5.1 wont render the conversational form 

### ISSUE THREAD

**Issue by rimx** [space10-community/conversational-form#123]
conversational form (latest version) won't render in safari (latest version - win7). Looking at the console, the exact issue is : 
`TypeError: 'undefined' is not an object (evaluating 'attr.name.indexOf')`

Looking at =>
[line 2034](https://github.com/space10-community/conversational-form/blob/master/dist/conversational-form.js) , I see we are trying to read the domElements attributes and for some reason, safari is trying to read the length (which is undefined and causing this error).
Insetead of :
`if (attr.name.indexOf("cf-conditional") !== -1) {`
I have extended the conditional check:
`if (typeof(attr.name) !== 'undefined' && attr.name.indexOf("cf-conditional") !== -1) {`
which solves the issue in safari.
@felixnielsen - would you mind having a look please?
Is it only me (using conditional) or someone else is facing this issue in safari as well?

**Comment by felixnielsen** [comment]
hi @rimx just ran through conditional flow in safari here https://space10-community.github.io/conversational-form-docs/conditional-flow.html and it works fine.
Can you let me know details of your use-case and cf setup?

**Comment by rimx** [comment]
Hi @felixnielsen - yes Im on Win7 safari 5.1*. I have tried your link and can see the same issue. I am attaching a screenshot. 
![safari](https://cloud.githubusercontent.com/assets/413091/26119593/062b2d7e-3a6e-11e7-89fd-9dae89821fa0.jpg)

**Comment by felixnielsen** [comment]
@rimx Win 7 Safari 5.1 what is the use percentage of that? Seems it is from 2010-2011

**Comment by rimx** [comment]
@felixnielsen ..you are right. probably the browser share is not that huge...but if anyone is using safari in windows that's probably the latest version they got.
Unfortunately, when it comes to corps and gov. they are not always up to date:(

**Comment by felixnielsen** [comment]
@rimx if anyone should be up2date then it should be corps and gov, such a problematic tendency.
I will check it, just to make sure it is not small "feature" that's making it break, will let you know if any improvements. Closing this for now.
