### ISSUE TITLE
cf-input-button wont show up if cf-error is thrown

### ISSUE THREAD

**Issue by rimx** [space10-community/conversational-form#125]
How to reproduce:
1. if an input field is required, try submitting is by pressing enter/clicking on the button (up arrow )
2. cf-error message would show up, adding class loading to cf-input-button, which actually hides the button
3. wait a while or delete the error message - the input button won't show up anymore

at desktops, it's not an issue but for mobile devices..user ends up with no option to submit the answer.

**Comment by rimx** [comment]
@felixnielsen - I have solved the issue by removing the loading class from input button:
```
        UserInput.prototype.inputInvalid = function (event) {
            var _this = this;
...
                _this.submitButton.classList.remove("loading");
....
        };
  
```
If it's the right fix..would be great if you could add it to next release.

**Comment by felixnielsen** [comment]
@rimx great find, fix is pushed to latest master + v.0.9.4 release. I will also push it cdn tmr.
