### ISSUE TITLE
Overwriting style

### ISSUE THREAD

**Issue by Remi-Leclercq-Blondel** [space10-community/conversational-form#128]
Hi, i'm trying to overwrite the style in /dist/styles but when I reload the page, the style is still the same.
There is anything to change ?
Thanks !

**Comment by Remi-Leclercq-Blondel** [comment]
I found a solution.

**Comment by felixnielsen** [comment]
great @Remi-Leclercq-Blondel, let me know if I can help.

**Comment by vikasr111** [comment]
@felixnielsen Can you please guide me through the process of overriding the styles.
I'm trying to get the UI similar to https://github.com/space10-community/conversational-form/blob/master/docs/src/styles/cf/cf-theming.styl

I have already compiled this CSS and added in my html page but the UI is not changing.

**Comment by felixnielsen** [comment]
@vikasr111 make sure that you include your styles after the initial cf styling, also make sure your css rules are the same selector depths as the styles you are trying to overwrite.
