### ISSUE TITLE
How do I save data to a Google Sheet?

### ISSUE THREAD

**Issue by wendyfromdc** [space10-community/conversational-form#13]
Do I put anything here, perhaps? 

<form id="co-billing-form" action="" cf-form-element>

**Comment by felixnielsen** [comment]
@wendyfromdc if you mean the user-submitted data upon conversation end?
Then you could add this yourself to your [forms end-point (action tag)](http://www.w3schools.com/TAGs/att_form_action.asp)

You can also manually instantiate ConversationalForm and set submitCallback, which takes a method.
Please see `submitCallback` in the readme file [here](https://github.com/space10-community/conversational-form#parameters-to-pass-the-constructor-of-conversationalform-conversationalformoptions)

**Comment by xerosanyam** [comment]
Not sure how you can use Google sheet. But [mailzen](http://mailzen.io) & [formspree](http://formspree.io) are good alternatives for collecting the form data  on a static site. :smile:

**Comment by Austin-Stephens** [comment]
I agree with @xerosanyam, Formspree is amazing, I am using this combo daily. But if you want to link form directly to Google Sheets you _can_ use this: [](https://github.com/dwyl/web-form-to-google-sheet)
