### ISSUE TITLE
Usage with react

### ISSUE THREAD

**Issue by JonathanWbn** [space10-community/conversational-form#133]
I am trying to implement this package in my react app. However I haven't really found a way of how to do this, since working with react and the DOM is always a little tricky for me.

Could someone maybe give an idea or maybe even add documentation on how to implement the form in react? And do I need to add jQuery?

I'm also happy to write the react documentation myself, once I got the hang of it.

Thanks in advance!

**Comment by TLevesque** [comment]
A basic example of implementation with react will be really great!

**Comment by felixnielsen** [comment]
@JonathanWbn @TLevesque sure thing, I will add this tomorrow.

**Comment by martinyung** [comment]
I am having trouble implementing it in my react app too. A documentation on this will be greatly appreciated.

**Comment by felixnielsen** [comment]
@JonathanWbn @TLevesque @martinyung [check ](https://github.com/space10-community/conversational-form/commit/d55564d1317b7bcb19db1aab6113b7869c3f195a)

**Comment by alexgurr** [comment]
I've built a react wrapper for this (work in progress). You can see it [here](https://github.com/alexgurr/react-conversation-form)
