### ISSUE TITLE
Maxsteps not update after addtags on formless feature

### ISSUE THREAD

**Issue by MediacraftFR** [space10-community/conversational-form#134]
Hello,

We tried formless feature and we noticed that the maxsteps variable is not updated after addtags method. So if we start the conversation with 1 tag the submit callback function is fired after we add a tag on step callback and the conversion stop.

We have found a trick, we set the maxsteps to 1000 just after the startconversation but it's not very clean.

Regards

**Comment by felixnielsen** [comment]
@MediacraftFR thanks for the report, i've pushed a fix to master
