### ISSUE TITLE
Is it possible to show input after radiobutton choice

### ISSUE THREAD

**Issue by WeTurkstra** [space10-community/conversational-form#135]
Is it possible to show a input immediately after a user has selected a radiobutton option?

Example: 
Which color do you like? 
 - red 
 - green
 - blue
 - else: [input]

This would be really nice

Edit: Its not needed to show the input in the radiobutton option. 
Just when the option is choosen to immediately jump to a input field.

**Comment by AfaanBilal** [comment]
Hi @WeTurkstra 

I'm not one of the developers of CF but I think that you can achieve the required effect by using conditional flow.

For example, if your radio options are:
```
<fieldset cf-questions="Which color do you like?">
	<label for="red">Red<input type="radio" name="my-color" id="red" value="red"></label>
	<label for="green">Green<input type="radio" name="my-color" id="green" value="green"></label>
	<label for="other">Other<input type="radio" name="my-color" id="other" value="other"></label>
</fieldset>
```

Then, you could have your input field as:
```
<input type="text" id="other-value" name="other-value" cf-questions="Which color do you like, then?" cf-conditional-my-color="other" />
```

The above input box would only show if the "other" radio button was selected by the user.

Hope it helps!

**Comment by felixnielsen** [comment]
thanks @AfaanBilal that could most defiantly work. @WeTurkstra the alternative to @AfaanBilal's proposal is to build a new ControlElements UI, so for simplicity then the [conditional flow](https://github.com/space10-community/conversational-form/wiki/Conditional-Flow) should get you far.
