### ISSUE TITLE
Editing behaves differently in formless than in non formless

### ISSUE THREAD

**Issue by EtgolWalkor** [space10-community/conversational-form#140]
Clicking on a previous answer in formless leaves the robot tags after the tag being edited in place. This is not the case in non formless.

**Comment by felixnielsen** [comment]
hi @EtgolWalkor this behaviour is for conditional-flow. Are you sure that you don't have any conditions active in your form?

**Comment by EtgolWalkor** [comment]
Thanks for the follow up. Why would this behave differently for conditional-flow vs. not? And if I wanted conditional-flow to act the same as non conditional, how would go about that?

**Comment by felixnielsen** [comment]
@EtgolWalkor reason for the different edit-behaviour, is that when you are editing a tag that is part of a conditional flow, then you are making changes to the conditions of already filled out tags, therefore it resets to the tag you choose to edit. Do you have a specific scenario at hand where this is counter-intuitive?

**Comment by EtgolWalkor** [comment]
Sorry my last reply was back to front. How it works in conditional flow is logical. How it works without conditional flow is not. As a user I expect the form to reset to the point clicked, regardless of implementation type.
