### ISSUE TITLE
Multiple Robot responses and skipping questions

### ISSUE THREAD

**Issue by sidrabhatti** [space10-community/conversational-form#141]
Is it possible to have the robot say/ask multiple things before the user responds? Is it it also possible to insert images into the form?

**Comment by felixnielsen** [comment]
@sidrabhatti please see [manuel-start example](https://space10-community.github.io/conversational-form/manual-start.html) and [image example](https://space10-community.github.io/conversational-form/image-answers.html)
Let me know if they meet your needs.
