### ISSUE TITLE
Missing File? 

### ISSUE THREAD

**Issue by def-mycroft** [space10-community/conversational-form#143]
I'm trying to run some of the examples in the docs folder, and I keep running into an issue with the file at this url: 

```
file://cf-4053.kxcdn.com/conversational-form/0.9.4/conversational-form.min.css
```

The min.js file is there, and the min.js file tries to reference the min.css file at the above url and throws a ERR_FILE_NOT_FOUND.

**Comment by felixnielsen** [comment]
hi @def-mycroft this issue seems to be related to if you run examples straight from your file system.
I would recommend you to run it on a local server, like MAMP etc.

I have also updated the protocol target on master branch, but this fix will not be pushed to cdn before next version.
