### ISSUE TITLE
Error on import for /requirejs/amd plugin

### ISSUE THREAD

**Issue by alsuga** [space10-community/conversational-form#146]
Unable to resolve some modules:

  "conversationalform" in
/opt/app/node_modules/conversational-form/dist/conversational-form.js
(web.browser)

The require for requirejs and amd plugin search for conversationalform instead of conversational-form
[here](https://github.com/space10-community/conversational-form/blob/master/src/scripts/cf/ConversationalForm.plugin.js#L30) and [here](https://github.com/space10-community/conversational-form/blob/master/src/scripts/cf/ConversationalForm.plugin.js#L34)

**Comment by felixnielsen** [comment]
Fixed with [PR](https://github.com/space10-community/conversational-form/commit/12ca38264b985cd9e1ba400d3a57232b0b7fbc23)
