### ISSUE TITLE
Limiting select options

### ISSUE THREAD

**Issue by bellamystudio** [space10-community/conversational-form#148]
Hi - if I want to limit the number of options in a multi select field, should I observe the select element (like I was validating a normal form) or is there another way I should do this using cf- tags? Essentially I want the visitor to be able to select a maximum of two options on a question, and for the response to be sent on the second selection (like they'd hit return). The conversational form works really well with the multi-select field, I just want to tweak the behaviour!

**Comment by felixnielsen** [comment]
hi @bellamystudio there is no direct API for this behaviour, but using the Conversational Form [Event system](https://github.com/space10-community/conversational-form/wiki/Events) with a bit of manual work and you can get it to work as you describe, see this [jsbin](https://jsbin.com/cotedejoha/edit?html,js,output)

**Comment by bellamystudio** [comment]
Fantastic! Thank you @felixnielsen 👍  I've noticed that this approach removes one-way data binding - is there an option in the conversationalForm function that I should enable?

**Comment by felixnielsen** [comment]
@bellamystudio is that with {previous-answer} or actual element ID you experience this?

**Comment by bellamystudio** [comment]
{previous-answer} works fine, so I've adopted that instead. I had been referring to input names of previous answers in {} tags to display as part of the bot responses questions, but it stopped working when I added the multi-select code and I couldn't figure out why it would affect that functionality. 

eg I had an input called 'like_reading', which I would then refer to in a cf-question="{like_reading} - why do you think this is?" - before this new code it was working for the whole form (ie I could refer to older answers in subsequent questions), but afterwards it would only store the very first response and {previous-answer} - any others wouldn't get parsed and the {input-name} would show up instead

**Comment by felixnielsen** [comment]
@bellamystudio thx for the outline, will investigate.

**Comment by felixnielsen** [comment]
hi @bellamystudio just had a look at the issue again, and I am not able to re-create, or maybe I am misunderstanding.
Could it be because you are missing an **s**? In `cf-question="{like_reading}`, it should be cf-questions.

**Comment by felixnielsen** [comment]
Closing this as I am not able to recreate.
