### ISSUE TITLE
Multiple bot responses without user response.

### ISSUE THREAD

**Issue by ccwdude** [space10-community/conversational-form#149]
Is there a way for the bot to have multiple responses before requiring a user input when using json?

**Comment by felixnielsen** [comment]
hi @ccwdude you mean something like [this](https://jsbin.com/sasulesetu/1) where we prevent auto start and use a static json to init the Conversation.

**Comment by ccwdude** [comment]
@felixnielsen Id like to be able to go from my bot asking a user a question and then the bot being able to have multiple responses without user inputs. Then I will be asking questions again after a few messages.

**Comment by NathAston** [comment]
I'm trying to do something similar. I would like the bot to greet the user on the 1st line, then proceed to asking a question.

Example

Bot - Text 1: Hello (No response required)
Bot - Text 2:  How are you today? (Response Required)

**Comment by felixnielsen** [comment]
@ccwdude please highlight the flow, then I can try and mimic it in a jsbin.
@NathAston you can use the double ampersand (&&) in cf-questions. Please see latest [commit](https://github.com/space10-community/conversational-form/commit/08fa3574a817972ddff06e9e4ed5c3bf5971df7d) to develop branch, this will be released next week.

**Comment by felixnielsen** [comment]
@ccwdude @NathAston let me know if your issues have been resolved, closing until further feedback.
