### ISSUE TITLE
Browser autofill

### ISSUE THREAD

**Issue by danielfriis** [space10-community/conversational-form#15]
Would be clever to utilize the autofill of browsers.

**Comment by SampsonCrowley** [comment]
@danielfriis that is exactly the thing that caused me to stumble across this project.  I would be happy to start implementing it for a PR, if you can think of a way to get started.  The thing that came to mind would be have an autofill button, that shows the underlying webform, asks for which autofill to use, then returns to a conversation style form

**Comment by SampsonCrowley** [comment]
@danielfriis but for that to work, conversational-form would have to accept prepopulated values.  is that the case with the current implementation?
