### ISSUE TITLE
Importing conversational-form with npm. 

### ISSUE THREAD

**Issue by IvanBashkirov** [space10-community/conversational-form#151]
Hello,

When I `npm install` the module and `import cf from 'conversational-form'` I get an error:

Module not found: Can't resolve 'conversationalform' in '/Users/user/Desktop/app_name/node_modules/conversational-form/dist'

It seems like it's coming from this line in the source 
`define(["conversationalform"], function(conversationalform)`
where `conversationalform` should be `conversational-form`.

**Comment by felixnielsen** [comment]
@IvanBashkirov I did not notice that the current package was not updated on NPM, just published a fix for NPM.

**Comment by IvanBashkirov** [comment]
Thanks a lot, keep up the good work.

**Comment by IvanBashkirov** [comment]
The name resolves but still having trouble using it. Could you point me in the right direction? I tried this but that doesn't work. Much appreciated.

`import cf from 'conversational-form';
new cf.ConversationalForm({elForm: myForm})`

**Comment by felixnielsen** [comment]
hi @IvanBashkirov the object you are passing should be {**formEl**: myForm} and not {**elForm**: myForm}, let me know if this solves your issue. Also make sure myForm is defined.

**Comment by IvanBashkirov** [comment]
Yes, my bad, I am using `formEl`. Form is defined. The error I get is 

```
TypeError: not a function

16 | function Promise(fn) {
  17 |   if (typeof this !== 'object') throw new TypeError('Promises must be constructed via new');
> 18 |   if (typeof fn !== 'function') throw new TypeError('not a function');
  19 |   this._state = 0;
  20 |   this._handled = false;
  21 |   this._value = undefined;
```

if I `console.log()` `cf` itself then I get this function. 

```
function Promise(fn) {
    if (typeof this !== 'object') throw new TypeError('Promises must be constructed via new');
    if (typeof fn !== 'function') throw new TypeError('not a function');
    this._state =…
```

 Not sure what to do with it.

**Comment by felixnielsen** [comment]
@IvanBashkirov please let me know which bundler are you using.
I see that ex. [rollup](https://github.com/rollup/rollup) has issues with top level references to `this`, which causes a problem depending on your project structure.

With rollup I get it to work like this:
```javascript
import './node_modules/conversational-form/dist/conversational-form';
var cfInstance = conversationalform.startTheConversation({formEl: myForm});
````

**Comment by IvanBashkirov** [comment]
I am creating a react app with `create-react-app` util which uses webpack. There may be something going on with the way the project is bundled, I'll keep looking into it.

**Comment by felixnielsen** [comment]
@IvanBashkirov just did a test with webpack to and found the [problem](https://github.com/space10-community/conversational-form/commit/5d5f4b641f2de0a60be9f5f9b6573903404008e2), please update to latest NPM version (0.9.51).

For reference:
Webpack:
```javascript
import './node_modules/conversational-form/dist/conversational-form';
var cfInstance = conversationalform.startTheConversation({formEl: document.createElement("form")}); // new conversationalform({formEl: myForm})
````

Rollup:
```javascript
import './node_modules/conversational-form/dist/conversational-form';
var cfInstance = conversationalform.startTheConversation({formEl: myForm}); // new conversationalform({formEl: myForm})
````

Let me know if this works.

**Comment by IvanBashkirov** [comment]
@felixnielsen works like a charm! And I don't even need to specify the path, simply this works.

 ```
import cf from 'conversational-form'

var myForm = document.querySelector('#my-form');
var c = new cf.startTheConversation({formEl: myForm})
```

Thanks again for taking your time to figure this out.

**Comment by felixnielsen** [comment]
thanks for the report @IvanBashkirov ! You can exclude the `new` as cf.startTheConversation will return an instance to you.
