### ISSUE TITLE
Unable to attach event to specific Button(radio button) change

### ISSUE THREAD

**Issue by khaalidm** [space10-community/conversational-form#152]
Hi @felixnielsen ,

Is there a way to attach an event to a specific action i.e a radio button ?
I've noticed that the form doesn't build out the id attributes in run time.
So I am unable to target the specific event.

Regards

**Comment by felixnielsen** [comment]
hi @khaalidm you highlight a good thing, I will add id attributes to the fields.
What you can do now is listen to `cf.UserInputEvents.CONTROL_ELEMENTS_ADDED` event and then you can get the buttons there and attach your events.
I will also add an event that will get exposed through the event dispatcher for these buttons. Added in next release.

**Comment by khaalidm** [comment]
hi @felixnielsen 

Thank you for the speedy response, 

I am using the `cf.ControlElementEvents.SUBMIT_VALUE` event  to listen for radio-button clicks, 
I have steps with multiple options(radio buttons), so I do not think that `cf.UserInputEvents.CONTROL_ELEMENTS_ADDED` would help, since I cannot target the specific button click. so I won't be able to attach an event.

If I have the id attribute from the input tag in the form that populates during run time, I can listen for that in the event and trigger my function call.

I am a big fan of CF, I see a lot of potential with this, Thanks for the great work =D

**Comment by felixnielsen** [comment]
@khaalidm thx :)
As you are using a radio button, can you then not use flowCallback?
Like this example: https://jsbin.com/ponibimeka/edit?html,js,output

**Comment by khaalidm** [comment]
@felixnielsen ahh I see,

apologies, I didn't understand what you said previously.
Thanks a million for the help =D

**Comment by alexsonnay** [comment]
Didn't understand how to trigger an event on radio inputs. Does someone have a more precise example  ?
