### ISSUE TITLE
Required checkbox is accepting unchecked as a value

### ISSUE THREAD

**Issue by lucaydaniel** [space10-community/conversational-form#153]
Hey guys...it's the first issue that I am submitting in my whole history (ok had to share this...it's a big moment for me 😄)

I have tried making a checkbox required but the user can just press enter and go to the next question.

The use case is the following: our users should accept the privacy policy or else they cannot have the conversation. A similar one could be accepting Terms and conditions.

I wonder if this behaviour is too specific and we should handled it manually, if so any suggestions on the best way to proceed?

Thank you so much guys for the work they you are doing ❤️ 

p.s: very similar issue https://github.com/angular/angular/issues/11459

**Comment by felixnielsen** [comment]
thanks for the report @lucaydaniel the required attribute on a `type=checkbox`should be valid. I will implement asap.
In the meantime then you can do [this](https://jsbin.com/larezixege/1/edit?html,js,output)
