### ISSUE TITLE
Any plan to add type definition .d.ts in the project root ?

### ISSUE THREAD

**Issue by pvdyck** [space10-community/conversational-form#154]
https://www.triplet.fi/blog/three-ways-to-provide-typescript-type-definitions-to-3rd-party-libraries/

**Comment by felixnielsen** [comment]
@pvdyck thinking about it yes, help is always appreciated.

**Comment by pvdyck** [comment]
looks like you just have to specify where your .d.ts file is in the "typings" => https://stackoverflow.com/questions/38909692/what-is-the-proper-way-to-include-typescript-typings-for-js-packages-which-will

**Comment by felixnielsen** [comment]
Yep, before that, the index.d.ts file should be setup manually, a moderated version, or use a gulp [library](https://github.com/ivogabe/gulp-typescript) to automatically build the index.d.ts file.

**Comment by pvdyck** [comment]
You can either use tsc --declaration fileName.ts like Ryan describes, or
you can specify declaration: true under compilerOptionsin your
tsconfig.json assuming
you've already had a tsconfig.json under your project.

Then specify typings in package.json
