### ISSUE TITLE
Attachments integration

### ISSUE THREAD

**Issue by mfaizanshaikh** [space10-community/conversational-form#156]
Hi all, any chance we can support attachments too ?

**Comment by felixnielsen** [comment]
hi @mfaizanshaikh Conversational Form supports [input[type=file]](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file) here is a [jsbin](https://jsbin.com/tulezoliya/1/edit?html,js,output) to illustrate the support.

**Comment by mfaizanshaikh** [comment]
thanks for the jsbin @felixnielsen
