### ISSUE TITLE
Help : Required prevent submit even if cf-conditional isn't respected

### ISSUE THREAD

**Issue by Vaelrium** [space10-community/conversational-form#157]
I've several forms merged in a single one.

I want to prevent empty input without using the required tag. Any work-around ?

**Comment by Vaelrium** [comment]
It'll do the trick, thx. Maybe adding some "cf-required" stuff could be useful tho.

**Comment by felixnielsen** [comment]
@Vaelrium I see your point, it does go against embracing standards as much as possible. You are also able to use `flowStepCallback`, like this [example](https://jsbin.com/kedixewami/edit?html,js,output)

**Comment by Vaelrium** [comment]
It's okay with the pattern stuff tbh.

Now i'm trying to go a different path depending on the first select value.
I could change the action attribute of the form with jquery, but it seems like the action is stored at the beginning of the chat loading. Problem is I can't find where.
