### ISSUE TITLE
Help: combobox filled dynamically keeps the old values

### ISSUE THREAD

**Issue by JoergVistra** [space10-community/conversational-form#158]
I have a form where a combobox is filled dynamically via Javascript. My ConversationalForm shows only the old value from page load. How can I refesh the values in ConversationalForm after populating the combobox? 
Thank you.

**Comment by felixnielsen** [comment]
hi @JoergVistra for this I would suggest you to manually start Conversational Form. So await the value-filling of the combobox and then initiate Conversational Form, like this [jsbin](https://jsbin.com/suruseyetu/1/edit?html,js,output)

**Comment by JoergVistra** [comment]
Hi, thank you for the fast answer.
I need a way to update the values in the combobox during the chat, because they depend a previous answer.
The user picks a date from a datepicker and after that the combobox is filled with available timeslots for this day.
Could it be done with remapTagsAndStartFrom?

**Comment by felixnielsen** [comment]
@JoergVistra let me take a look at how to handle runtime removing/adding elements of fieldset and select tags, will get back to you tomorrow afternoon with an update.

**Comment by felixnielsen** [comment]
@JoergVistra i've been looking in to this now, currently, removing an element from the original `form` tag is not something that is taken care of. But modifying `remapTagsAndStartFrom` to accommodate for removing tags would be an easy-fix. Alternatively an API to remove á tag would also be beneficial, where the parameter would just be the original tag to be removed, this could both be a group (select, fieldset) or a input, option. Let me know what you think.

**Comment by JoergVistra** [comment]
sorry the late response. Went with the API solution. Only delete the tag from tags and add it again. Works great, thank you.
And really great work that you are doing with this project.
