### ISSUE TITLE
Bower release differs from github one

### ISSUE THREAD

**Issue by maxart2007** [space10-community/conversational-form#159]
It's really disappointing to see chaos in docs and repositories. Do something about it.
Good idea with poor implementation.

**Comment by felixnielsen** [comment]
@maxart2007 can you please elaborate.

**Comment by maxart2007** [comment]
I used same code for bower release and it worked for me with bugs (wrong order of responses if added via API, but it's not the case). When I replaced bower release with the one downloaded from github everything just worked without any additional actions. And an additional <p> tag appeared in response block.

**Comment by felixnielsen** [comment]
@maxart2007 I just did a comparison of the latest bower package and the code from the latest [release](https://github.com/space10-community/conversational-form/releases/tag/v0.9.6), there is no differences between the files, checked both min and none-min.
Could it be that you used a older version before updating bower?

Please also elaborate on chaos in docs and the responses via API issue you are having.

**Comment by felixnielsen** [comment]
@maxart2007 closing this, as it is inconclusive. Please re-open if you are able to elaborate on the precise issue.
