### ISSUE TITLE
addTags not working

### ISSUE THREAD

**Issue by al2spark** [space10-community/conversational-form#161]
Hi, the addTags method doesn't work when trying to add new tags with addAfterCurrentStep option.

Indeed, there is a bug in the code on line 5262 where 

`this.tags.concat(tags);`

should be

`this.tags = this.tags.concat(tags);`

Thanks

**Comment by felixnielsen** [comment]
@al2spark thanks for the report. I will update NPM, Bower, CDN asap, can you use the source from master for now?

**Comment by al2spark** [comment]
Yep, no problem. Thanks
