### ISSUE TITLE
Display answer list on more than two lines

### ISSUE THREAD

**Issue by pvdyck** [space10-community/conversational-form#163]
Hi,

I have a lot of answers to a specific question (around 15 checkboxes) and they are then displayed on two lines.

On narrow screens (like mobile) it does not work very well.

Any plan to display the list on 3 or 4 lines ? Or simply fill the space on the screen ?

Thanks,

Philippe

**Comment by felixnielsen** [comment]
@pvdyck would be nice with a alternative view for lists with many items @danielfriis what do you say here?

**Comment by danielfriis** [comment]
I agree. Let's think about a good solution. Happy to hear inputs or see examples of best practise.

**Comment by pvdyck** [comment]
Actually, simply increasing the number one lines might do it.
It's a poor man's solution, but it's a solution.

**Comment by felixnielsen** [comment]
How about a solution that shows an CTA that will open the iOS native list UI?

**Comment by danielfriis** [comment]
On really long list that could be an option. Was just checking how Facebook handles long lists. They seem to have a limit on 12, but one line.

@pvdyck how come it doesn't work on narrow screens? Maybe padding on the options could be decreased to allow for more options being displayed at once?

**Comment by pvdyck** [comment]
@felixnielsen ideally the solution should be platform neutral and propose its own l&f
@danielfriis it works but if I count the number of 'actions' to see & select some answers, it is not efficient at all ...
