### ISSUE TITLE
Treat textareas differently from text fields

### ISSUE THREAD

**Issue by michieloosterling** [space10-community/conversational-form#164]
For usability reasons it would most likely be a good idea to have the input for a textarea turn into a multiline field when encountered. The current method of just showing an input area one line high is not very inviting to entering longer pieces of text. Thoughts?
If this is already possible, I apologise, although I can't find it anywhere in the docs or examples.

**Comment by felixnielsen** [comment]
hi @michieloosterling you should be able to use `shift + enter` to make a new line, like this [jsbin](https://jsbin.com/sahawohevo/edit?html,output), here you can make [new lines](https://www.dropbox.com/s/ir48fm6kmynd6m0/Screenshot%202017-08-09%2015.27.48.png?dl=0) using `shift`

**Comment by michieloosterling** [comment]
Hi @felixnielsen, thanks for the reply. I understand the behaviour you describe, however during testing our test audience doesn't get it. Their comments came down to expecting a multiline input field when a question clearly demanding a longer answer was shown. Note that the test audience is not internet savvy per se, but represent your average internet user.

Would this be something that's relatively easy to change/add?

Appreciate your time!

**Comment by felixnielsen** [comment]
@michieloosterling gotcha, I could implement something like an attribute: `cf-multiline` that would allow for just pressing enter, so then you would have to press the submit button. Would that work?

**Comment by felixnielsen** [comment]
@michieloosterling gotcha, I could implement something like an attribute: `cf-multiline` that would allow for just pressing enter, so then you would have to press the submit button. Would that work?

**Comment by danielfriis** [comment]
If we are to implement this, I would make an option as you suggest @felixnielsen on the tag itself or in the instantialization. Naming it something like `cf-alt-newline-on-multiline` or `altNewlineOnMultiline`

**Comment by michieloosterling** [comment]
I think that would be a good start. I'd suggest if possible that in the case a textarea field is seen with (for instance) a tag like cf-textarea-multiline, the input field automatically visually changes to 2 or 3 lines. Perhaps the default size (height?) could be overridden if the cf-textarea-multiline has an optional number along with it, so for instance in the following example the user input field shows as 3 lines high: <textarea name="myTextArea" cf-questions="Tell us all about your awesome idea!" cf-textarea-multiline="3"></textarea>.

**Comment by felixnielsen** [comment]
@michieloosterling should we maybe do a combo;
`<input cf-textarea-multiline`would allow for pressing enter without submitting.
but you can also use `cf-textarea-multiline="3"` to set the height of the input as well as limit the lines, so pressing enter >= 3rd times would submit but < 3rd would create a new line. Let me know.

**Comment by meowhunter** [comment]
Any update on this?

**Comment by jenssogaard** [comment]
@meowhunter I will support for the rows-attribute on `<textarea>` in an upcoming minor release this week. A new option `preventSubmitOnEnter` will also be added which prevents submit on enter-keypress. This will subsequently allow for newlines on enter-click if a textarea-field has rows > 1.

Not exactly what is discussed but might be of relevance.
