### ISSUE TITLE
hideUserInputOnNoneTextInput with input type="file" failure

### ISSUE THREAD

**Issue by TimTdev** [space10-community/conversational-form#165]
Hi,

I have hideUserInputOnNoneTextInput enabled on my form.

But when arriving at the input type="file" the _choose file_ button disappears (because it is not a type="text" of course). 
This means you can not select a file and thus not continue...

A solution, I think, might be to only involve any input type that NOT text OR file.
Any other suggestions are welcome of course.

Thanks,

Tim

**Comment by jenssogaard** [comment]
@TimTdev hopefully better late then never. A fix for this will be released in a few days.

**Comment by jenssogaard** [comment]
This has been fixed in latest 0.9.90 release.
