### ISSUE TITLE
Tag.prototype.setTagValueAndIsValid, min and max is not minLength, maxLength

### ISSUE THREAD

**Issue by nuFaqtz** [space10-community/conversational-form#166]
Hi,

In the method Tag.prototype.setTagValueAndIsValid the value of the input is validated against its length.
But the min and max attributes are actually values:

see: [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number)

Or when the actual length is intended change the attributes to minlength and maxlength.

Keep up the good work,
Best regards, 
JamBo

P.S. I personally would like validation to be mandatory external. I found this error because my 'flowStepCallback' function was never called and started investigating

**Comment by felixnielsen** [comment]
@nuFaqtz Thanks for the outline, I will switch max and min to maxlength and minlength asap.
