### ISSUE TITLE
Conditional on select (array) and regex

### ISSUE THREAD

**Issue by nuFaqtz** [space10-community/conversational-form#167]
Hi,

In Tag.testConditions when the tagvalue is an array (from a select?) the condition is not checked against a provided regex.
I solved this by doing:

```
// tag value is an array
var isValid = false;
for (var i = 0; i < condition.conditionals.length; i++) {
	var conditional = condition.conditionals[i];
	var value = tagValue[0];
	if (typeof conditional === "object") {
		// regex
		isValid = conditional.test(value);
	}
	else {
		// string comparisson
		isValid = tagValue.toString() == conditional.toString();
	}
	if (isValid)
		break;
}
```
But I'm not sure about the 'var value = tagValue[0];' part.
In my situation this works perfect but is the value to check against always a single item? 
Then [0] is valid...

Best regards,
JamBo

**Comment by felixnielsen** [comment]
@nuFaqtz I have added it on my list, will make some test scenarios for select. Expect something from me tomorrow.

**Comment by felixnielsen** [comment]
@nuFaqtz can you have a re-check of your issue with the version I just pushed to develop? thanks :)

**Comment by nuFaqtz** [comment]
@felixnielsen Validated & working as expected, 
thnx

**Comment by felixnielsen** [comment]
@nuFaqtz great, will push a release later today with these micro fixes.
