### ISSUE TITLE
cf-list on one-row instead of two-row

### ISSUE THREAD

**Issue by karthikradhakrishnan96** [space10-community/conversational-form#168]
Hey have a list of radio buttons showing up in two rows(css class two-row). I see a class 'one-row' in your code. Can I configure the radio buttons to show up in a single scrollable row always?

**Comment by felixnielsen** [comment]
hi @karthikradhakrishnan96 this is not an option atm. UI limitation, you can request an alternative UI (let me know how that could work) or let me know if this should be a feature-request from your side.

**Comment by karthikradhakrishnan96** [comment]
Maybe chage cf.ControlElements.prototype.resize function and take another parameter in options?
Something like
```
if (options.allowTwoRow && isListWidthOverElementWidth && !containsElementWithImage) {
                    this.el.classList.add("two-row");
                    this.listWidth = Math.max(elOffsetWidth, Math.round((listWidthValues[Math.floor(listWidthValues.length / 2)]) + 50));
                    this.list.style.width = this.listWidth + "px";
                }
```
