### ISSUE TITLE
hybrid bot/human

### ISSUE THREAD

**Issue by webmagnets** [space10-community/conversational-form#17]
It would be nice if the person types something that the bot doesn't understand then it would notify me and allow me to respond manually.

**Comment by felixnielsen** [comment]
hi @webmagnets when do you see this scenario happening?

**Comment by felixnielsen** [comment]
@webmagnets let me know your thoughts here.

**Comment by webmagnets** [comment]
Well, I imagined the form coming up when someone visits one of my sites. The bot starts signing them up for my offer, but then the visitor goes off script so we need human intervention.

Does that make sense?

**Comment by danielfriis** [comment]
I'm not sure I understand your issue. Conversational Form builds upon a regular form, which means there wouldn't be a case (as it is now), where the bot wouldn't understand the user's answer.

I'm closing this issue. Feel free to reopen and give a more detailed issue description.
