### ISSUE TITLE
Long Form

### ISSUE THREAD

**Issue by xblix** [space10-community/conversational-form#170]
i have a form with 1200 input.
Work like a charm.

But all input is showing outside the chat white main box. So i scroll down and down over 1200 input.

Any way to make chat 100% fluid and 100% width and height for hidding completely all input down after chat window and in the same times, disable scroll down of all input after chat window

**Comment by xblix** [comment]
error on mycside. no issue

**Comment by xblix** [comment]
i confirm
long form with many inputs make a very long height of entire form and blank space for.
its could be great if the size of global chat be dynamic depending how much input you have. svrolling is there anyway...no need to show entire history (and blank more than 2680px on my page)

**Comment by xblix** [comment]
or if we can set a max-height in entire fkrm...but keep scroling of history. The oroblem is when yiu have 1200 input....the form make space for all chat allready. how we can keep a chat of 600px by example, and hide history and use scrolling as he's

**Comment by felixnielsen** [comment]
@xblix it sounds like you need to define cf-context and control the height of that element.

**Comment by xblix** [comment]
cf-context style="height:300px;visibility:hidden;overflow:hidden" works like a charm!
