### ISSUE TITLE
Add user response and thinking robot before flowstep callback

### ISSUE THREAD

**Issue by karthikradhakrishnan96** [space10-community/conversational-form#174]
In your formless example, flowstepcallback is used to fetch content from server, but in the case where the server is slow, it seems more intuitive to add the user response to the chat list and set the robot to thinking till the success function is called. Could you please let me know if that's possible?
Thank you

**Comment by felixnielsen** [comment]
@karthikradhakrishnan96 makes sense, I will implement in the coming days.
