### ISSUE TITLE
How does this handle prefilled lists?

### ISSUE THREAD

**Issue by 1beb** [space10-community/conversational-form#176]
Let's say I have a form with a prefilled list that is rather long, is there a way to get this to show the respondent options based on what they started typing. (Think like google does in the search box, like autofill)

**Comment by felixnielsen** [comment]
hi @1beb you mean when the list is showing? Currently if you type in the input field it filters the list.

**Comment by nukeourlimo** [comment]
@1beb you can hide the list using css, I went with
`[tag-type="select"] cf-input-control-elements.two-row {
					display: none;
				}`
You will still get a list of filtered options when user starts typing, although maybe restricted to one line (not tested)
Its a bit dirty but works a treat for my use-case.

**Comment by felixnielsen** [comment]
@1beb let me know if your issue got resolved.
