### ISSUE TITLE
Text input with suggestions

### ISSUE THREAD

**Issue by SebastianKempf** [space10-community/conversational-form#178]
I might be missing something but is there a input with suggestions for the answer?
What I mean is a simple text input with a list of options from which I might choose one but does not have to and instead be able to wright my own. Something like a radio input but with an "other" option.

**Comment by shaolinjr** [comment]
@SebastianKempf  If you have a question that has more than one option such as an checkbox or radio, when you type in the textInput, it will filter the list to match your search! Is this what you were asking?

**Comment by SebastianKempf** [comment]
Thanks for your reply. It's not quite what I mean. Maybe the following example helps to understand my case:

The Question would be:
"What do you want to talk about?"

Now, I what to give three suggestions (e.g.: "the weather", "everything and anything" and "the godfather") but also I want the user to be able to ignore these suggestions and type in the topic of his or her choice instead which does not have to be one of the suggestions.

If I use an radio or checkbox field to achive this I get a "Your input is not correct ..." reply which makes sense but excluded the use case above.

**Comment by shaolinjr** [comment]
@SebastianKempf You have the SAME problem I have, I need the users to try to choose some items from the list, but if a item he seeks is not there, I wish he could add that. I currently achieved the action of adding another item into the list, but it has a LOT of bugs, I'm even considering not using this framework at all because of this. This feature is a MUST HAVE for the type of flow my platform need to have...

**Comment by felixnielsen** [comment]
@SebastianKempf @shaolinjr this is a limitation of the UI, I would suggest building a new UI that accommodate your requirements. Adding a new type of UI is very easy, just ping me if you want to get the info on how. PRs are welcome.

**Comment by shaolinjr** [comment]
Hey @felixnielsen I would love to know how hehe! I needed to use the .js, because I could not compile the .ts, can you help me with both? Building this new UI component and compiling the .ts (the Tag class somehow was compiling after all dependencies, even with the ///)

**Comment by felixnielsen** [comment]
@shaolinjr sure, let me know the errors you are getting when compiling the .ts files.

**Comment by shaolinjr** [comment]
@felixnielsen  it says that I had used the class Tag.ts before it was implemented, and I've just cloned the repository...

**Comment by felixnielsen** [comment]
@shaolinjr can you send me the output?

**Comment by shaolinjr** [comment]
@felixnielsen Course! Give my a sec'

**Comment by shaolinjr** [comment]
<img width="1280" alt="captura de tela 2017-09-18 as 16 10 58" src="https://user-images.githubusercontent.com/8459735/30559735-03d505ba-9c8c-11e7-86d6-9377631a5033.png">

**Comment by felixnielsen** [comment]
@shaolinjr did you do a `$ bower update`  from ./ ? I think it is the es6-promise polyfill that disrupt the compiling and not an issue with Tag.ts

**Comment by shaolinjr** [comment]
@frederikchristensen  Oww.. I didn't do that! I will try it now!

**Comment by shaolinjr** [comment]
@felixnielsen Should I do anything else than bower update in root folder? It didn't work...

**Comment by felixnielsen** [comment]
@shaolinjr please also do the `$ typings install`

**Comment by shaolinjr** [comment]
<img width="483" alt="captura de tela 2017-09-18 as 16 32 31" src="https://user-images.githubusercontent.com/8459735/30560668-045e25fe-9c8f-11e7-995b-7ac38bc214b8.png">

**Comment by felixnielsen** [comment]
@shaolinjr can you try and run `$ gulp build`?

**Comment by SebastianKempf** [comment]
Hey @felixnielsen thx for the reply would love to know how to build a new UI.

**Comment by danieltome** [comment]
Hi @shaolinjr I think what they need, and actually I also need is a way to use ajax autocomplete.
Eg. The question from chatbot: Which location did this happen at?
And when they start typing an address, we can call ajax, and return autocomplete.

Is there a way to trigger this for a specific question?

Another question, related. Could we use a datepicker for specific questions.

thanks,
Dan

**Comment by suvarnaR** [comment]
is there a way to autocomplete the user input like in android while user type it gets suggestions..something similar in conversational form

**Comment by jenssogaard** [comment]
@Rchanger When you add a select field you can type and then options will be filtered.

**Comment by Rchanger** [comment]
@jenssogaard thanks for your reply, thats all with select,radio and checkboxes. I'm trying with normal text inputs

**Comment by jenssogaard** [comment]
@Rchanger I see. It is not something we support currently. I can't really see a use case where that feature is needed, but if you can convince me it is something we might implement.

**Comment by Rchanger** [comment]
sometimes some of the address and words are to big if user gets suggestions that makes it is and if we have to give same input again and again in that case getting suggestions makes it is.

**Comment by jenssogaard** [comment]
I see the use case for autosuggestions when typing in your address. That makes sense. What that would look like in CF would probably be:
- event for handling user input changes ([We already have that](https://space10-community.github.io/conversational-form/docs/0.9.80/events/))
- method for presenting suggestions returned by e.g. Google Maps Api

I'll discuss with the team but right now I do not think that it will take priority as it's a feature that would greatly rely on 3rd party API.

**Comment by Rchanger** [comment]
@jenssogaard That's great ,but actually I have done that only i have made ajax call on key change and given suggestions but problem is thàt EventDispatcher giving error in vuejs that its not a constructor....it works fine with JavaScript

**Comment by melicerte** [comment]
@Rchanger Did you find a solution to submit the data ?
I build the autocomplete logic myself, but I can't make conversational from to proceed to next question.

**Comment by Rchanger** [comment]
i didn't get your question do you submit the form ? or it does not proceed to next question

**Comment by melicerte** [comment]
I have an input for getting zipcode-city. The list is loaded via AJAX and manually appended to cf-input as ul > li.
When user clicks on an item, it fills the input with selected item, put the key in an hidden field of the form and removes ul autocomplete list.
From there, I do not know how to automatically go to next question.
User has to focus in the field and press ENTER to do that. But I want this action to be done automatically when an item is selected in the autocomplete list.

**Comment by melicerte** [comment]
@Rchanger finally I came up with triggering click event on the hidden button.
It works :)

**Comment by sijiahahaha** [comment]
@melicerte Hi, I'm facing some same issue. Could you talk more about how you achieve that?

In my survey, I have some questions with so many choices(like choose which state you live in).

My idea is to hide the radio at first and be shown after typing in some letters (like show Washington after typing in wa). I'm trying to set up a UserInputEvents.KEY_CHANGE dispatcher on this particular question by id rather than the whole form, but I failed....Is it possible to do that?

**Comment by melicerte** [comment]
Hi @sijiahahaha 
What I did is loading a simple input text, let's say 
`<input type="text" name="city" />`
On change, get data via AJAX. On success, add custom ul li in cf-input.
On click on li, set data where you want (current field or hidden input for example), then submit to next question.
jQuery version to submit :
`$('cf-input cf-input-button').trigger('click');`

**Comment by sijiahahaha** [comment]
@melicerte Thank you so much!!!

**Comment by sijiahahaha** [comment]
@melicerte Hi, I'm sorry to bother you again, but I still don't know how to implement....I'm a starter in AJAX and JQuery.
Could you indicate more about how to do it? And I don't know how to hide the buttons.
Thank you so much and so sorry for any inconvenience!!!!!

**Comment by melicerte** [comment]
@sijiahahaha You should probably read jQuery documentation :
AJAX : http://api.jquery.com/jquery.ajax/
Attach events : http://api.jquery.com/on/
Trigger events : http://api.jquery.com/trigger/

You'll find documentation of what AJAX and events are is on the Internet, your favorite search engine is your friend ;)
Hide the buttons with CSS (display:none). You'll find plenty of documentation on the Internet.

**Comment by sijiahahaha** [comment]
Thank you for sharing!
