### ISSUE TITLE
How to add new value to prefilled list of checkboxes or radios

### ISSUE THREAD

**Issue by shaolinjr** [space10-community/conversational-form#179]
Hello @felixnielsen ! I wonder if there's a way of adding a user's text into the list of checkboxes or radio buttons. Here's an example: "I have a list of skills as checkboxes, the user types a skill that I don't have in my json". Can I add the user input to the list of values for that question? The user shouldn't skip to next question after he added the new skill, because he might want to add another skill. Anyone have an idea how to achieve this??

**Comment by jenssogaard** [comment]
@shaolinjr I late reply but might still be of value to you. I would recommend achieving this by using [flowStepCallback events](https://space10-community.github.io/conversational-form/docs/0.9.80/events/) and adding your tags using [addTags()](https://space10-community.github.io/conversational-form/docs/0.9.80/public-api/) that would give you the option to control the next tags based on the users response.
