### ISSUE TITLE
Question based on previous response

### ISSUE THREAD

**Issue by cauesanches** [space10-community/conversational-form#18]
Hi,

Firstly, congratulations for iniciative. Conversational form is the future of web communication.

Well, I'm building a form that I need set a specific question according with the previous answer. For example:

**Question**: The client is a person or a company?

**Question (if person)**: Inform the number of personal document.
**Question (if company)**: Inform the number of employees.

Has a solution for this case? Is it possible get the previous answer and make a test to show correct question?

Thanks!

**Comment by felixnielsen** [comment]
hi @cauesanches great feature. I see it implemented in a couple of ways:

1. "100% control": We expose the internal event system, this way you would be able to listen for when a user submits an answer and inject a new [cf.ITag](https://github.com/space10-community/conversational-form/blob/master/src/scripts/cf/form-tags/Tag.ts#L24) depending on the answer.

2. "Pure markup": We could setup a way to map an answer to a specific tag via markup.
```html
<input cf-answers="fruit=#list-of-favourite-fruits|vegetables=#list-of-favorite-veggies" ...>
```
so as a user writting "fruit" and submit would show the selector of fruits to the user as the next step.

Let me know if you have a 3rd solution in mind or if 1. or 2. sounds appealing.

**Comment by demircancelebi** [comment]
Hi @felixnielsen,
I think there may be times when some of the questions are not asked at all depending on the previous answers, and the actual shape of the all questions available might resemble a tree (or object), rather than an array. So it would be better to have 100% control with an easy to use API, rather than appending lots of input fields

**Comment by felixnielsen** [comment]
@demircancelebi great, sounds like it would be a good overall idea to expose the internal event system.

For the enhancement at hand:
The flow of Conversational Form is controlled from a centralised in the [code](https://github.com/space10-community/conversational-form/blob/master/src/scripts/cf/logic/FlowManager.ts#L114) here, we could expose a method that could allow for:
1. pick an already registered ITag
2. make a new tag based upon an answer
and just fallback to the default behaviour of choosing the next tag in line.

By reviewing the code it would also make sense to expose the [validation of the form-completion](https://github.com/space10-community/conversational-form/blob/master/src/scripts/cf/logic/FlowManager.ts#L104) to a public API.

Let me know your thoughts @demircancelebi

**Comment by danielfriis** [comment]
I think there might be some value in allowing people to specify conditional questions directly in the markup, instead of having to define it in the script. That way, it's easier to have a clear overview of what's going on. Otherwise, you'd have some questions in the markup, and others in the script.

**Comment by anragab** [comment]
I guess this feature will drift the product from being a UI for a web form.

I would rather suggest that the standard visibility and enabled tags are a more compatible solution and the developers can also listen on the input fields to trigger visibility or enable/disable fields.

This will clearly decouple the plugin from the form design and will maintain the feature of toggling between conversation and web form

**Comment by LeGfrey** [comment]
Hi,

I'm encountering the same _issue_ and I'm wondering if something like an attribute `cf-if-previous` could be a good solution.

So if I should resolve the owner's issue. I would do something like that : 
```html
<input cf-questions="Are you a person or a company ?" type="radio" name="person-or-company" value="person" />
<input type="radio" name="person-or-company"  value="company" />

<input cf-questions="Inform the number of personal document." cf-if-previous="person" type="text" name="number-document" /> 
<input cf-questions="Inform the number of employees." cf-if-previous="company" type="text" name="number-employees" /> 
```

What do you think of this kind of solutions ? :smile:

**Comment by jadismael** [comment]
tried to use the above solutions with fail.  In my implementation i am asking the user two questions, first is to select his current job  ( student, manager, job seeker), and on the second im asking the user to select his area of expertise ( it, hr, sales). then we're supposed to answer based on the previous 2 answers . for example if job=student and area = it   reply with " you're an it student". Does anyone have an idea on how to make this possible

**Comment by LeGfrey** [comment]
Hi @jadismael 

Did you try using the code of this pull request ? https://github.com/space10-community/conversational-form/pull/42

If so you could find an example of a similar workflow here on this pastebin.
http://pastebin.com/ugYqCA1S

On this workflow I'm using `cf-display-if` to make conditionals display :smiley:

**Comment by jadismael** [comment]
Hello @LeGfrey I tried your code, but the bot always display the first condition which is Young Boy in your script.

**Comment by LeGfrey** [comment]
Hi, 
Are you sure you built the source of CF using my pull-request ? :cry: 

I just tried this and it works don't you forget a step ?
* pull the source code from my PR
* execute gulp to build the js code from ts
* copy paste this code http://pastebin.com/raw/ugYqCA1S to /test/custom-form.html

**Comment by jadismael** [comment]
@LeGfrey  I've followed your steps, still it always tells me that "young boy" even when you indicate that you're a old girl

**Comment by LeGfrey** [comment]
@jadismael I uploaded an example online (thanks to surge) if you want to check it.
If it works online, I guess you should compare the different files included on the page (html, js) to know where the different is.

You can find my example right here : http://cf-conditional.surge.sh/ :grinning:

**Comment by jadismael** [comment]
@LeGfrey  thank you a lot for your help, it works like a charm now. seems like i had a problem with the js.

**Comment by LeGfrey** [comment]
@jadismael you're welcome :smile: 
if you like (or not) my version of conditional display and want to improve it don't hesitate to post your opinion on the PR

**Comment by danielfriis** [comment]
Interpreting this as conditional logic jump - i.e. jumping to questions based on previous answers @felixnielsen

**Comment by allantorres** [comment]
Well, after a lot of tries, i did it! 
The decision is running well! @LeGfrey !!!

**Comment by scooter7** [comment]
Hi. Is it possible to use logic so that, instead of using {previous-answer} in a way that only enables inputting the answer to the last question only, I could specify logic using the answer to any previous question that will end up being used in a series of follow-up questions? 
For example, let's suppose that I am conducting a study of people who were admitted to Yale University but who chose to enroll at another school. Question 1 asks, "Which school did you choose to attend?" If the answer is "Harvard," I would use the {previous-answer} function to ask "Which college has better academics, Yale or {previous-answer}?" If the user then selects "Yale," I still want the next question to ask, "Which college has better faculty: Yale or {previous-answer}, which I want to remain as "Harvard" even though the user selected "Yale" as the choice for the previous question. So, basically, I want to know if there is a way to choose a previous answer to a specific question to be used anywhere in the conversation form that I choose. Thanks!

**Comment by conixit** [comment]
Can someone post a compiled version of all the js and css files necessary to run the example file examples/development.html?  All of the files I was able to get off GIT have .ts and .styl extensions, I'm assuming that the "install" using grunt unpacks those files into real .css and .js files.  Here are the directories that I don't have:
                ../build/cf/ui/control-elements/OptionButton.js"
		../build/cf/ui/control-elements/OptionsList.js"
	        ../build/cf/ui/control-elements/UploadFileUI.js"
etc




Thanks

**Comment by msaidtw** [comment]
The @LeGfrey solution seems to break - updating the CSS file it's pointing at to the latest version mostly fixes things, but still getting a handful of UI errors. Anybody up for updating it (I'm stuck)?

**Comment by sull** [comment]
see [cf-jump](https://github.com/space10-community/conversational-form/pull/42#issuecomment-294245398) idea

**Comment by felixnielsen** [comment]
Please see latest [release](https://github.com/space10-community/conversational-form/releases/tag/v0.9.4) and [Conditional Flow example](https://space10-community.github.io/conversational-form-docs/conditional-flow.html)

And [Wiki](https://github.com/space10-community/conversational-form/wiki/Conditional-Flow) on conditional flow feature

@scooter7 please see [value piping](https://space10-community.github.io/conversational-form-docs/value-piping.html) combined with conditional flow should accommodate your scenario?

**Comment by scooter7** [comment]
Thanks!

*James Vineburgh, Jr., PhD* | 319-899-6620
[image: LinkedIn] <http://www.linkedin.com/in/scootervineburgh>
