### ISSUE TITLE
loadExternalStyleSheet doesn't work and  global conception issue

### ISSUE THREAD

**Issue by tvequaud** [space10-community/conversational-form#181]
`$("form").conversationalForm({ 'loadExternalStyleSheet': false });`

This option doesn't work. A default remote stylesheet is called everytime I instantiate the conversationalForm object... Worst good idea ever.

As for bootstrap, jquery... etc. We should add a call from HTML to a default CSS if the user wants it. And that's easier if we want to customize the styles. Here, I cannot create a conversationalForm on the fly (OR NOT !) depending on the context... Because once conversationalForm object is instantiated... I cannot override default styles because your CSS oveerrides mine... Daaaah !

And, no, instantiate conversationalForm everytime is not a good idea either.

**Comment by felixnielsen** [comment]
@tvequaud hard to dissect the problem you are having, but it seems to be rooted elsewhere in your code, please be more problem oriented in your issue description.
these jsfiddles showcases the options usage is working as expected:
[This one DOES load external stylesheet](https://jsfiddle.net/c0vq6h1b/1/)
[This one DOES NOT load external stylesheet][https://jsfiddle.net/c0vq6h1b/2/]

I would recommend you to let it load the external stylesheet, you get some bootstrap styling from it.. and through [style specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) override the styles.
