### ISSUE TITLE
How can I export formless conversation to server?

### ISSUE THREAD

**Issue by erogol** [space10-community/conversational-form#182]
#After all the conversation I like to pass it to server.However, since I generate it in formless way, I cannot serialize it by using the form. Is there nay way to export all the conversation as json or in any other format?

**Comment by erogol** [comment]
Currently what I've done is I switched to load all form by javascript and then init the conversational form. In this way, I am able to serialize the form after the whole session. 

It is not possible in formless version (conversation is created by JS) since each update only adds content to 'cf-context' not to the form. 

If there is any other way to export the conversation in the formless case, please let me know.

**Comment by felixnielsen** [comment]
@erogol form you form instance use [getFormData](https://github.com/space10-community/conversational-form#getformdata)
````javascript
instance.getFormData(true) <- serialized(json)
instance.getFormData(false) <- FormData
````
