### ISSUE TITLE
Usage with vuejs

### ISSUE THREAD

**Issue by Sireini** [space10-community/conversational-form#183]
I am trying to implement this package in my vuejs app. However I haven't really found a way of how to do this, since implementing the library.

Could someone provide me an example of implementing this library in vuejs. I allready saw an reactjs implementation but this differs from the vuejs.

I would like to implement the formless conversational-form.

**Comment by jenssogaard** [comment]
Open call for anyone in the community to cook up an example.

**Comment by findborg** [comment]
I had it working once with a simple import and require.  All depends how deep you are needing vue to go.  I was only using for layout.

**Comment by jenssogaard** [comment]
I will close this issue for now. I will add proper Vue example soon.

**Comment by it-fm** [comment]
any news?

**Comment by Leleking** [comment]
i got it working by doing this with jquery or vanilla js
first install the package: npm install conversational-form 
then in your script, do this 
<script>
 mounted() {
            $(document).ready(() => {
              $("form").conversationalForm({
                formEl: document.getElementById("form"),
                context: document.getElementById("cf-context"),
                userImage: "https://gulpjs.com/img/gulp-white-text.svg",
                robotImage: "https://static.wixstatic.com/media/170a47_2959d43fa79b4f6781b188e639c58303~mv2.png/v1/crop/x_339,y_0,w_754,h_882/fill/w_33,h_38,al_c,q_80,usm_0.66_1.00_0.01/170a47_2959d43fa79b4f6781b188e639c58303~mv2.webp",
                submitCallback: () => {
                  this.callSuccess()
                }
              })
            })
        },


</script>

**Comment by jenssogaard** [comment]
@it-fm the updated v1.0 documentation has an example on how to implement in Vue: https://space10-community.github.io/conversational-form/docs/1.0.0/getting-started/

Just scroll down the page a bit and you'll see a StackBlitz example.
