### ISSUE TITLE
how to get user informations via email ?

### ISSUE THREAD

**Issue by dilshantharaka** [space10-community/conversational-form#184]
how to get user informations (name, phone, email) via email ???

**Comment by nukeourlimo** [comment]
Not part of the team, but you will need to post the form data to a function that links into a mail service either written by yourself(server-side presumably) or you could potentially send the data to a service like Campaign Monitor or MailChimp using JS.  Cheers

**Comment by jenssogaard** [comment]
@nukeourlimo Thanks for taking the time to answer. Spot on!

@dilshantharaka Have a look at the [submitCallback-option](https://github.com/space10-community/conversational-form/blob/master/docs/submit-callback.html). From the submit-callback, you could execute an AJAX request to your server, and then let your server handle login/create/email and that type of stuff. I'll go ahead and close this issue.
