### ISSUE TITLE
Will the latest version be released on NPM?

### ISSUE THREAD

**Issue by m4n3z40** [space10-community/conversational-form#185]
NPM package version is not up to date (still at `0.9.51`). Is there a plan to release the `0.9.6` version on NPM?

**Comment by alexgurr** [comment]
I too am wondering this. Including the script directly in my HTML isn't ideal.

**Comment by jenssogaard** [comment]
@m4n3z40 @alexgurr I've just published 0.9.6 to NPM. Let me know if you run in to any issues.

**Comment by pierlon** [comment]
@jenssogaard I still get the `0.9.51` version. My guess is that this still happens since `51` is greater than `6`.

**Comment by jenssogaard** [comment]
@pierlon you are right. That is absolutely not ideal. You'll have to hold out for a new release with proper version number before that is fixed. I'm sorry :unamused:
