### ISSUE TITLE
Would it work with TypeForm?

### ISSUE THREAD

**Issue by epleplepl** [space10-community/conversational-form#19]
Is there a way to turn TypeForm form into Conversational Form?

**Comment by m1guelpf** [comment]
Youshould contact the @typeform team

**Comment by felixnielsen** [comment]
@epleplepl from my limited experience with Typeform and from what I can scan from their documentation.
Then I see a few issue with adding ConversationalForm on top.

1. Typeform is rendered in an iframe tag, which proposes contextual communication issues as iframes are considered "blackbox".
2. Typeform does not seem to have an API that allows for input field snitching or submitting data to an endpoint of Typeform.

If one where able to "snitch" the input fields (json/output) of an Typeform form, then it would be rather easy to code some logic into ConversationalForm that builds tags from a Typeform form. This combined with a Typeform endpoint would allow for data to be sent to Typeform via ConversationalForm.

But again, I am not able to dissect anything useful, related to these matters, from the Typeform documentation. Let me know if you find anything :) @epleplepl

**Comment by LinusEkenstam** [comment]
You could head over to the new https://developers.typeform.com website and check out the new API's @epleplepl @felixnielsen
