### ISSUE TITLE
Angular 2 & 4 support

### ISSUE THREAD

**Issue by hossamElfar** [space10-community/conversational-form#191]
I am trying to use your awesome package in an angular 2 app. I was able to render the view but When I add ngModel to the form input the ngModel wasn't updated after submitting the form and I was not able to get the data by calling the public API method that you are providing

**Comment by glebmachine** [comment]
@hossamElfar you should create wrapper component
For good references look at: https://github.com/zefoy/ngx-swiper-wrapper

**Comment by jenssogaard** [comment]
Closing this issue. I will add an Angular example soon.

**Comment by CoderBees245** [comment]
Hello, Is an example for Angular done already? Please let me know how I can use this beautiful library in Angular?

**Comment by jenssogaard** [comment]
@CoderBees245 yes, here you go: https://stackblitz.com/edit/angular-conversational-form

**Comment by Vbboi24** [comment]
Wow this is awesome, But i try to wrap it around a div but it ends up occupying my whole page. I tried adding context while initializing using startTheConversation method, still i endup covering the whole page. I referred to this same stackblitz demo. No luck trying to wrap it within a div :( @jenssogaard
