### ISSUE TITLE
console.log in several places

### ISSUE THREAD

**Issue by alexgurr** [space10-community/conversational-form#192]
I seem to be seeing several debug logs. Not sure if they are supposed to be there - I would presume not.

Running 0.9.6 using the direct <script> injection in my HTML file.

Screen here: https://puu.sh/y59zh/cd4ddc2d0b.png

**Comment by jenssogaard** [comment]
Hi @alexgurr. I'll build in an option to suppress console.log messages in the next minor version release.

**Comment by jenssogaard** [comment]
@alexgurr by default log messages are disabled in the [latest release](https://github.com/space10-community/conversational-form/releases/tag/v0.9.70).
