### ISSUE TITLE
Multiple answers for one question

### ISSUE THREAD

**Issue by nukeourlimo** [space10-community/conversational-form#194]
Hi!

I am prototyping a project where we have several answers for a free text question using regex.  For instance "answer 1" would be true if "hello" is entered, "answer 2" would be true if "world" is entered.  However if "hello world" is entered then both answers would be required to be displayed.

At present, after showing the first answer and entering a blank response(ie " ") the second answer is displayed, this leads me to believe that it should be possible to display the answers one after the other without user interaction in between. To get this working could I be using the cf-validation tag or is there an event that would better suit my requirements?

Thanks.

**Comment by jenssogaard** [comment]
Hi @nukeourlimo. I'll be happy to help. Any chance that you can provide a codepen/jsfiddle example so we can see your code?
