### ISSUE TITLE
Questions do not show up

### ISSUE THREAD

**Issue by mhinc14** [space10-community/conversational-form#196]
Hi everyone,

This conversational form looks great but unfortunately I can't seem to get it to work properly.
 
For some reasons the questions don't show up on the screen.

Hopefully it's an easy fix and someone can point out my mistake.

Thanks

<img width="1144" alt="screen shot 2017-11-03 at 01 50 31" src="https://user-images.githubusercontent.com/14908278/32358017-ea8a843c-c039-11e7-8f22-9e204c10cf56.png">

**Comment by alexgurr** [comment]
Can you show us your code?

**Comment by felixnielsen** [comment]
@mhinc14 you cf-questions contains an problematic characters: https://www.dropbox.com/s/lrsgpje7unh5854/Screenshot%202017-11-03%2009.03.46.png?dl=0

**Comment by mhinc14** [comment]
@felixnielsen thanks for pointing that out. Even with the problematic character resolved I get the same issue.
@alexgurr here is example code of how i've been trying it

As shown in the picture in my original post, the text input field appears but none of the questions appear.

Im using chrome on mac and am up to date.

`<html lang="en">
<script type="text/javascript" src="https://cf-4053.kxcdn.com/conversational-form/0.9.6/conversational-form.min.js" crossorigin></script>

<head>
  <meta charset="utf-8">

  <title>The HTML5</title>
</head>

<body>
  <p>Hello world</p>
  <div id="contact-form">

    <form id="contact" method="post" action="" cf-form cf-context>
      <fieldset>

        <input type="text" pattern="^hello" cf-questions="Your answer needs to include 'hello'">

        <label for="email">E-mail</label>
        <input type="email" name="email">

        <label for="phone">Phone</label>
        <input type="text" name="phone">

        <label for="website">Website</label>
        <input type="url" name="url">

        <label for="message">Question/Comment</label>
        <textarea name="message"></textarea>

        <input type="submit" name="submit" id="submit" value="Send Message" />

      </fieldset>
    </form>

  </div>
  
</body>

</html>`

If someone can provide me a simple example of that I can just copy and paste and overwrite this code that would super helpful.

**Comment by alexgurr** [comment]
Try changing 

```
<form id="contact" method="post" action="" cf-form cf-context>
```
to

```
<form id="contact" method="post" action="" cf-form-element>
```

**Comment by mhinc14** [comment]
@alexgurr thanks for trying. I've copied your code across and it still isn't working.

I am building a static website and I wanted to use a conversational form instead of a normal one.

** silly question alert ** - should i be bundling / creating a build file of the website for it to work?

Is there any other things you can thing of that could be preventing it from working?

**Comment by alexgurr** [comment]
You don't need to do any of that stuff if it's a static site of HTML pages. I literally have just copied that code above into a foo.html file, opened it in chrome, and it loads fine.

**Comment by mhinc14** [comment]
@alexgurr I can confirm i am on the latest chrome version.

I get the same issue when i launch it in firefox too.

I just have an 'index.html' with the code you suggested above in it. But I see the following when I open it in the browser or launch a local server.

<img width="1435" alt="screen shot 2017-11-03 at 17 43 54" src="https://user-images.githubusercontent.com/14908278/32388212-e122b358-c0be-11e7-9230-ac614ff39236.png">
<img width="1435" alt="screen shot 2017-11-03 at 17 43 54" src="https://user-images.githubusercontent.com/14908278/32388214-e34bfa9a-c0be-11e7-811b-0dac3abc2392.png">

**Comment by mhinc14** [comment]
I've also just tried it on another computer and its the same issue.

here's the code for the entire index file

`<!doctype html>

<html>

<head>
  <script type="text/javascript" src="https://cf-4053.kxcdn.com/conversational-form/0.9.6/conversational-form.min.js" crossorigin></script>
</head>
<form id="contact" method="post" action="" cf-form-element>
  <fieldset>

    <input type="text" pattern="^hello" cf-questions="Your answer needs to include 'hello'">

    <label for="email">E-mail</label>
    <input type="email" name="email">

    <label for="phone">Phone</label>
    <input type="text" name="phone">

    <label for="website">Website</label>
    <input type="url" name="url">

    <label for="message">Question/Comment</label>
    <textarea name="message"></textarea>

    <input type="submit" name="submit" id="submit" value="Send Message" />

  </fieldset>
</form>
`

**Comment by alexgurr** [comment]
Try putting the script inside a <head> tag.

**Comment by alexgurr** [comment]
If it's the one in your repository - you don't need to wrap the <script> inside a div - that might be what's breaking it..

**Comment by mhinc14** [comment]
Thanks for the quick replies and pointing out how to include the code.

It is the one i have just added to my repos.

Even without the div tags around the script....same issue.

When i open the file without serving....same issue.

chrome console shows
<img width="1439" alt="screen shot 2017-11-03 at 17 44 07" src="https://user-images.githubusercontent.com/14908278/32389549-ddec2fa8-c0c2-11e7-8b6c-ab3f193ac34c.png">

**Comment by alexgurr** [comment]
Have you tried removing the extra HTML tag?

**Comment by mhinc14** [comment]
@alexgurr You legend! That has done it. It's working now. Thanks again!

**Comment by alexgurr** [comment]
You're welcome :)
