### ISSUE TITLE
Conditional Answers

### ISSUE THREAD

**Issue by sajadshafizadeh** [space10-community/conversational-form#197]
As far as I understood, there is just **one** route for every kind of answers. I want to implement four different reactions based on each option of a radio button _(or select-option button)_. Can I do such a thing with this library?

**Comment by jenssogaard** [comment]
Hi @sajadshafizadeh. Did you check the [Conditional-section of the Wiki](https://github.com/space10-community/conversational-form/wiki/Conditional-Flow)? You can also use the events to do some [custom logic after each answer/user input](https://github.com/space10-community/conversational-form/blob/master/docs/dynamic-questions.html).

**Comment by sajadshafizadeh** [comment]
I see, thanks for the links you provided.
And my last question is: Can the bot send  a message? Only a message
(without expecting any answer). Something like this:

bot: hello
bot: what's your name?
user: {waiting for the user's answer}

See? "hello" is a message without waiting for the response. Can I do such a
thing?
thx

**Comment by jenssogaard** [comment]
@sajadshafizadeh You can chain cf-question value by seperating cf-questions value with **&&** to allow for chained questions.
```
<input type="text" cf-questions="Hello?&&Please tell me your name." ..
```

**Comment by sajadshafizadeh** [comment]
Look, all I'm trying to do is implementing a nested conditional radio. Here is my code:

```
                    <fieldset cf-questions="Hi&&Are you ready to answer?">
                        <input type="radio" name="cfc-intro" id="intro-yes" value="yes">
                        <label for="intro-yes">Yes!</label>

                        <input type="radio" name="cfc-intro" id="intro-no" value="no">
                        <label for="intro-no">No!</label>
                    </fieldset>

                    <fieldset cf-questions="Ok good, do you like music?" cf-conditional-cfc-intro="yes">
                        <input type="radio" name="cfc-intro-music" id="music-yes" value="yes">
                        <label for="music-yes">Yes!</label>

                        <input type="radio" name="cfc-intro-music" id="music-no" value="no">
                        <label for="music-no">Not really!</label>
                    </fieldset>

                    <fieldset cf-questions="Ok, will you try it later?" cf-conditional-cfc-intro="no">
                        <input type="radio" name="cfc-intro-try-later" id="try-later-yes" value="yes">
                        <label for="try-later-yes">Yes, maybe!</label>

                        <input type="radio" name="cfc-intro-try-later" id="try-later-no" value="no">
                        <label for="try-later-no">Nope, whatsoever!</label>
                    </fieldset>
```

The expected result is asking always two questions. While sadly my code always asks those three questions. So that condition seems useless. Any idea how can I handle that?

**Comment by sajadshafizadeh** [comment]
Ok, thank you ..! 

Just one thing, as you know there is a option that you can use the answer of previous question in the next question. Good.

Now I need to do the same, but I don't want to use of the whole previous answer. For example:

```
First Question: You are a

1. person who takes photo
2. person who play music
```

The question above is a `radio`. Now I need to set a attribute for each case. For example I need to set `"Photographer"` for the first case and  `"Musician"` for the second one. And then use those attribute in the next question, like this:

```
 <!-- if the used has selected the first case -->
Second Question: Nice to meet you "Photographer", what's your name?
```

Can I do something like that?

**Comment by jenssogaard** [comment]
If your flow is static (you do not need to get questions and answer from your server after each user response) then you should be able to accomplish this just using conditionals. See these two links:
https://github.com/space10-community/conversational-form/wiki/Conditional-Flow
https://space10-community.github.io/conversational-form/conditional-flow.html

**Comment by sajadshafizadeh** [comment]
Nice .. thank you.

Recently I've faced with something which is like a bug. When I use conversational-form in my website (I initialize it to an element in the end of my site), and when I load my website, surprisingly my website scrolls to the bottom of it and stops when that element comes in the screen.

The strangest part of it is: the mentioned behavior happens sometimes, not always. And sometimes else it happens when I click on everywhere of the website.

Any idea what's the problem?

**Comment by jenssogaard** [comment]
@sajadshafizadeh Maybe try this option:
preventAutoFocus: false

Described here: https://github.com/space10-community/conversational-form#self-instantiate-with-vanilla-javascript

**Comment by sajadshafizadeh** [comment]
Yes, `preventAutoFocus: true` resolves the problem. Thank you. Also answering our feedback is nice of you.

**Comment by jenssogaard** [comment]
@sajadshafizadeh great! I'll close this issue now. Feel free to open a new one if you have more questions.
