### ISSUE TITLE
Specific class on robot response

### ISSUE THREAD

**Issue by MatteoPieroni** [space10-community/conversational-form#199]
Hi guys,
first of all great work! I used Conversational Forms on a couple of sites and I just managed to get it working on Modx as well :-).

I would like to know if there is any way to change the color of the Robot Responses (using addRobotChatResponse). I have tried for a specific class or something to pass to the function but so far I had no success.

Can you help me?

**Comment by jenssogaard** [comment]
Hi @MatteoPieroni. Thank you for your interest in this project. No, you can only pass the message to addRobotChatResponse. But maybe you could do something like this? https://codepen.io/jenssog/pen/aVqVyY

**Comment by MatteoPieroni** [comment]
Hi @jenssogaard unfortunately that cannot solve my problem, since I would have to change css every time I add or remove a question. Thanks a lot anyway, for now I solved by going for a green text! It could be an interesting feature to think of implementing though, for UI purposes. :-) Again thanks for the great work!

**Comment by jenssogaard** [comment]
@MatteoPieroni I see. So your idea would be to be able to pass a class name addRobotChatResponse(), correct? Eg. addRobotChatResponse("Thank you.", "green")

**Comment by MatteoPieroni** [comment]
That could be great for compliance with any used frameworks like bootstrap or else.
For me any preset class would be more than enough to target via css. Eg. <cf-chat-response class="robot peak-thumb show robot-response">

**Comment by jenssogaard** [comment]
Hi @MatteoPieroni. I have discussed this with the team and we do not believe that there currently is a strong enough case for this discussed feature. Thank you for suggesting and you are always welcome to [do a PR](https://space10-community.github.io/conversational-form/docs/0.9.70/build-the-source/) if you feel the need for a feature. That can sometimes increase the chances of it being adopted in the project :)

**Comment by MatteoPieroni** [comment]
Hi @jenssogaard, thank you very much for taking the time to discuss this! I hope it will be addressed in the future if the case for its use will grow stronger. In the meantime keep up the great work!
If you would like to include cases of real use on the web in the docs I have some... :-)
