### ISSUE TITLE
A simpler way to add reactions to some response

### ISSUE THREAD

**Issue by kandebonfim** [space10-community/conversational-form#200]
First of all, I'm in love with this project! Thanks for building this awesome library.

I'm building a form and a want to add some quick reactions to a user's response, for example:

```
fieldset cf-questions="Nice name, {name}!&&What kind of activity are planning to do?"
      input type="radio" name="atividade" id="intro-yes" value="yes"
      label for="intro-yes" Recreational

      input type="radio" name="atividade" id="intro-no" value="no"
      label for="intro-no" Professional
input type="text" cf-questions="Cool! We're in the same boat!" cf-conditional-atividade="yes" value="ok"
input type="text" cf-questions="Uh... We gotta a professional here!" cf-conditional-atividade="no"
```

The problem is that when the reaction appears, the user has to type something to move to the next question. It would be good to pass an attribute like `cf-input-skip` to automatically move to next step.

I know that we have `addRobotChatResponse('You have reached the end of the form!')` but to do this I'll have to initiate the ConversationalForm manually and seems much more complicated than just using the markup to do it...

Am I doing this right? 😬

**Comment by jenssogaard** [comment]
@kandebonfim We are happy to hear that you like the project! I totally understand what you are looking for and especially when mentioning that you would like to do accomplish this sans javascript. I'll discuss this with the team to see if we can squeeze this in to an upcoming release.

**Comment by kandebonfim** [comment]
@jenssogaard sounds good! Let me know if you need any help, ok? I'm interested in contributing to this repo.

**Comment by jenssogaard** [comment]
@kandebonfim still interested in doing this? We think your suggestion is a good idea and we intend on making a `cf-robot-response`-tag that takes `cf-questions`-attribute. 

Ideally it will also accept `cf-conditional` (and maybe a few more that I forgot).

Example use:
```
<form>
   <cf-robot-response cf-questions="Hi. Welcome on board." />
   <cf-robot-response cf-questions="We will now start by asking you a few basic questions about yourself." />
   <input cf-questions="Your name?" />
   <cf-robot-response cf-questions="Now that we got that out of the way we would like to know about your favorite colors?" />
   <input cf-questions="Your favorite colors?" />
</form>

**Comment by kandebonfim** [comment]
Loved the idea! I'll try to run the dev environment on my machine to implement it.

**Comment by jenssogaard** [comment]
@kandebonfim I've already implemented it in this branch: https://github.com/space10-community/conversational-form/tree/CfRobotMessage

And here is a CodePen: https://codepen.io/space10/pen/zRNKwE

Feedback is appreciated.
