### ISSUE TITLE
cf-input-placeholder doesn't work on radio buttons

### ISSUE THREAD

**Issue by MikeSwider** [space10-community/conversational-form#202]
looks like you can add/change the placeholder on radio buttons using the formless option but not by adding an attribute to the question.

**Comment by jenssogaard** [comment]
Hi @MikeSwider. I'm not exactly sure what you are asking about or what I would like to accomplish. Can you provide a simple code example? Here are a couple of clean CF examples that might be helpful: https://codepen.io/jenssog/pen/mqXMQW, https://jsfiddle.net/Jenssog/nq4z68hw/
