### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by al2spark** [space10-community/conversational-form#203]
Hi there, I'd like to know if it is possible to add and display emojis in children tags (answers).

I tried many times (via cf-label) but didn't work...

Thanks :)

**Comment by jenssogaard** [comment]
Hi @al2spark. I'll be happy to help you. Can you provide a code example? Here's to vanilla CF-examples that might speed up a code example: https://codepen.io/jenssog/pen/mqXMQW, https://jsfiddle.net/Jenssog/nq4z68hw/
