### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetHeight' of null

### ISSUE THREAD

**Issue by marcelopc** [space10-community/conversational-form#205]
![error](https://user-images.githubusercontent.com/29096180/33390448-0c86c148-d51d-11e7-8647-b7d5d0816611.jpg)

**Comment by maisnamraju** [comment]
Running into the same issue here, I tried the exact code mentioned in the submit callback

**Comment by jonasaurus** [comment]
Having this issue when requiring conversational-form from NPM and bundling.

**Comment by CallistusWD** [comment]
Sorry to ASk has this been fixed because i am experiencing this isse

**Comment by jenssogaard** [comment]
@CallistusWD this has been fixed in [the latest v0.9.90 release](preventSubmitOnEnter) that I just published.
