### ISSUE TITLE
emojify.min.js file not found

### ISSUE THREAD

**Issue by KannaDinesh** [space10-community/conversational-form#207]
emojify.min.js file not found in conversational form
![conversationalform](https://user-images.githubusercontent.com/19591721/34348988-5e62e2f4-ea34-11e7-8043-9db740e40817.jpg)

**Comment by jenssogaard** [comment]
Hi @KannaDinesh. I just checked and the file loads fine here: cdnjs.cloudflare.com/ajax/libs/emojify.js/1.1.0/js/emojify.min.js

Could maybe have been a minor outage that was out of our control. Before New Year we will release a minor update where Emojify will be removed as well as a bunch of other improvements regarding styling (SCSS, useful variables).

**Comment by jenssogaard** [comment]
@KannaDinesh The [latest release](https://github.com/space10-community/conversational-form/releases/tag/v0.9.70) has removed emojify support which might be of interest to you.

**Comment by KannaDinesh** [comment]
Tanq 😇

On Jan 3, 2018 11:48 PM, "Jens Soegaard" <notifications@github.com> wrote:

@KannaDinesh <https://github.com/kannadinesh> The latest release
<https://github.com/space10-community/conversational-form/releases/tag/v0.9.70>
has removed emojify support which might be of interest to you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/space10-community/conversational-form/issues/207#issuecomment-355085825>,
or mute the thread
