### ISSUE TITLE
How do I submit form via PHPmailer?

### ISSUE THREAD

**Issue by winadv** [space10-community/conversational-form#209]
I am trying to send the form data to my email address via PHPmailer but I am not able to in any way would like a help how to send using PHPmailer or via javascript to my email address.
Thank you.

**Comment by jenssogaard** [comment]
Hi @winadv. You need to use the [submit callback](https://space10-community.github.io/conversational-form/docs/0.9.70/functionality/submit-callback/) method and do an AJAX request to your server with the form data.

**Comment by winadv** [comment]
@jenssogaard  
Thank you I managed to do the integration with SMTP using AJAX, to send to my email now I'm having just one more problem regarding the integration of MailChimp this always appears this message in my console of errors.
`Failed to load https://space10.us12.list-manage.com/subscribe/post-json?u=a168b507fc8033ce61a467329&amp;id=c6f366f53b&FNAME=XXXX&LNAME=XXXX&EMAIL=test@email.com: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://s.codepen.io' is therefore not allowed access.`
I checked the documentation and saw that it has the same error as I do to fix?
Thank you.

**Comment by jenssogaard** [comment]
@winadv I'm glad to hear. Right, that is a cross-origin issue since we are posting to a different domain. You need to implement **JSONP**. See this jQuery example below of a JSONP request:
`$.ajax({
        url: 'YOUR URL',
        type: 'GET',
        data: $('#your-form').serialize(),
        dataType: 'jsonp',
        contentType: "application/json; charset=utf-8",
        success: function (data) {
           if (data['result'] != "success") {
                //ERROR
                console.log(data['msg']);
           } else {
                //SUCCESS - Do what you like here
           }
        }
    });`

**Comment by jenssogaard** [comment]
EDIT: @winadv I just updated the mailchimp example with a better jQuery example: https://codepen.io/space10/pen/mpPvaW

**Comment by winadv** [comment]
@jenssogaard Everything worked.
I just needed to make some changes.
For who needs it is below the code that I used.

```
var mailchimpUrl = 'https://XXX.us13.list-manage.com/subscribe/post-json?u=XXX&amp;id=XXX';
					mailchimpUrl += '&FNAME=' + formDataSerialized.name;
					mailchimpUrl += '&LNAME=' + formDataSerialized.lname;
					mailchimpUrl += '&EMAIL=' + formDataSerialized.email;		
													
							$.ajax({
								url: mailchimpUrl,
								type: "GET",
								data: formDataSerialized,
								dataType: "jsonp",
								jsonp: "c",
								success: function(data) {
								console.log(data);
								}	
							});
```
Thank you
