### ISSUE TITLE
How can I control the speed of showing messages?

### ISSUE THREAD

**Issue by sajadshafizadeh** [space10-community/conversational-form#210]
I have multiple *(three)* messages which show right after each other:

    <input name="your_opinion" type="text" cf-questions="Ok!&&So what's your opinion about it?&&Thanks." cf-conditional-idea="yes" />

Those three messages (which are chained with `&&`) will be shown faster than what I need. I mean, that speed destroys a real-chat feeling. *(actually I want to see that "is typing" expression for a longer time)*

Anyway, is there any solution I can control that speed? Thank you.

**Comment by jenssogaard** [comment]
Hi @sajadshafizadeh. Default values are defined in [this interface](https://github.com/space10-community/conversational-form/blob/develop/src/scripts/cf/interfaces/IUserInterfaceOptions.ts). Which is also a good place to get a feeling of parameters.

`conversationalForm = window.cf.ConversationalForm.startTheConversation({
	userInterfaceOptions:{
		controlElementsInAnimationDelay: 250,
	        robot: {
			robotResponseTime: 0,
			chainedResponseTime: 400
		},
		user:{
			showThinking: true,
			showThumb: true
		}
	}
});`

**Comment by sajadshafizadeh** [comment]
Great .. thank you .. it worked exactly as expected.
Just do you know how can I activate "is typing ..." feature? I see it in the demo, but not in what I implemented.

**Comment by jenssogaard** [comment]
@sajadshafizadeh Try this:
`user:{
    // to show thinking state or not, defaults to false;
    showThinking: false
}`

**Comment by sajadshafizadeh** [comment]
Great .. thank you. 
As my last question, is it possible to write HTML tags as the value of messages? For example I need to give a download link as the answer. Here is my code:

    <input name="d" type="text" cf-questions="Click <a href="./path">here</a> to download your invoice." cf-conditional-dw="yes" />

But that `<a>` tag will be removed. Why? Do you use strip_tags in your code? Anyway is there any solution how can I handle that?

**Comment by jenssogaard** [comment]
You are using " inside a value defined by "" which is your problem. Try this:
`cf-questions="Click <a href='./path'>here</a> to download your invoice."`

**Comment by diedea** [comment]
Is there a possibility to stall the display of response options e.g. radio buttons too? So that the user can first read the question thoroughly?

**Comment by jenssogaard** [comment]
@diedea no, not out of the box. You could solve it using some custom CSS to delay the animation.
