### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by adantoscano** [space10-community/conversational-form#211]
```markdown
## Documentation
Conversational Form's documentation is included in /docs of this repo as well as being <a href="https://space10-community.github.io/conversational-form/docs/">hosted on github pages</a> 
```
This link goes to nowhere

**Comment by jenssogaard** [comment]
Thank you for noticing @adantoscano. This has been fixed and the link is now forward to the latest version of the documentation: https://space10-community.github.io/conversational-form/docs/

Cheers

**Comment by adantoscano** [comment]
Thank you for this awesome project.
