### ISSUE TITLE
Restart or Reset after Form Submit 

### ISSUE THREAD

**Issue by johnnyMick** [space10-community/conversational-form#213]
Hello,
is their a way to restart or reset the conversation after Submit Callback ? currently i refresh the page but looking if their is a better way to restart the form again from start .

**Comment by tstkenny** [comment]
You may just call the following api:

window.ConversationalForm.remapTagsAndStartFrom(0, 0, 1);

https://space10-community.github.io/conversational-form/docs/0.9.70/public-api/

**Comment by jenssogaard** [comment]
@tstkenny Thanks for helping @johnnyMick with his question 🔥
