### ISSUE TITLE
Conditional form on select not working

### ISSUE THREAD

**Issue by bharuma** [space10-community/conversational-form#215]
I'm trying to show a fieldset based on the value of Select value. For e.g. 

```
<select name='country' id='country'>
<option  value='United States'>United States</option>
<option  value='United States'>United Kingdom</option>

<fieldset cf-conditional-country='United States'

```
However, the fieldset is shown irrespective of the select value. Maybe select values need to be checked differently? Any help is appreciated

**Comment by jenssogaard** [comment]
Hi @bharuma. I put together a [simple form here demonstrating the selected option](https://codepen.io/space10/pen/ZrzNeM). Is that of help to you?

**Comment by bharuma** [comment]
thank you @jenssogaard for your quick response. 

I updated the original question with the code (I forgot to wrap it inside <code>)

Select works great, no problems with that. However, I'm trying to show a fieldset based on a specific value from select (selected option from select dropdown). 

- can conditional be applied on fieldset?
- can 'selected option' be used in conditional value?

**Comment by jenssogaard** [comment]
No, adding them on fieldset does not work [per the documentation](https://space10-community.github.io/conversational-form/docs/0.9.70/functionality/conditionals-and-branching/).

I've extended [the example](https://codepen.io/space10/pen/ZrzNeM) a bit to reflect select value used in conditional

**Comment by luispadron** [comment]
Question about this is it possible to ask a question, like in your example, and then ask another question (with radio buttons)?

i.e Radio button question -> Radio button question
