### ISSUE TITLE
problem with an appearance change

### ISSUE THREAD

**Issue by igormoviic** [space10-community/conversational-form#217]
I do not know where I instantiate loadExternalStyleSheet to accept my formatting

**Comment by jenssogaard** [comment]
Hi @igormoviic. The docs does not describe this option correctly. It's a boolean, so if you set it to true when instantiating your CF then the default CF CSS will just not be loaded. 
```
new cf.ConversationalForm({
    formEl: myForm,
    loadExternalStyleSheet: true
});
