### ISSUE TITLE
Include !default on your SASS variables and include main .scss file

### ISSUE THREAD

**Issue by jorditarrida** [space10-community/conversational-form#219]
Hi,
I have a project where I imported `conversational-forms` using NPM and the Webpack module bundler. I would like to customize the appearance by customizing the SASS variables, importing your project's SASS files into my codebase and setting `loadExternalStyleSheet` to `false`. However, there is a big problem with your SASS files. I cannot overwrite the variables because they are loaded via an `@import` inside your `src/styles/cf/cf.scss` (a file that needs to be included) and the variables themselves are not overridable by the [`!default` option](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_default). It would be truly great if the variables could be overriden.
Another nice addition to your project for this use case would be a main .scss file which would import all the required files. This way, when a user wanted to load all the .scss files into their own project, they would only need to `@import` a single .scss file which would then load all the required partials. This would be way more handy, and it would also have the advantage of not having to manually check the dependencies on project updates. This file could also be the entry point for your Gulp building routine.
Thanks for your time :)
Jordi

**Comment by jenssogaard** [comment]
Hi @jorditarrida. You are absolutely right. I converted existing Stylus to SASS but didn't spend enough time on the issues you are referring to. Do you want to do a [PR](https://github.com/space10-community/conversational-form#contributing) for this? (might speed up the process a bit 👍)

**Comment by jorditarrida** [comment]
@jenssogaard I will try to do the PR next week, cannot guarantee it tho :)

**Comment by jorditarrida** [comment]
Hi,
I submitted a pull request fixin this issue last week, can you merge it?
Thanks,
Jordi

**Comment by jenssogaard** [comment]
Hi @jorditarrida. I'll test the PR Wednesday. I would appreciate if you could clean up the PR a bit:
- Do not change package.json, gitignore, package-lock.json (Might be valid changes but should not be included in this PR)

Thanks

**Comment by jorditarrida** [comment]
Hi @jenssogaard,
Just pushed another commit which fixes the changes in package.json and .gitignore. Sorry about being so clumsy :)
Hope you can integrate the PR with these changes :)
Thanks for your time,
Jordi

**Comment by jenssogaard** [comment]
@jorditarrida great, I'll take a look at it now.
