### ISSUE TITLE
Modularize and publish via NPM

### ISSUE THREAD

**Issue by mattbasta** [space10-community/conversational-form#22]
It would be useful to be able to `import` this from NPM. Using something like webpack to build the project would generate smaller file sizes and produce cleaner output. It would also enable integration with React, and more:

```js
import ConversationalForm from 'conversational-form';

const MyForm = ({onSubmit}) =>
  <form
    onSubmit={event => {
      event.preventDefault();
      onSubmit(event.target.elements);
    }}
    ref={formEl => formEl && new ConversationalForm({formEl})}
  >
    <input /* ... */ />
  </form>;
export default MyForm;
```

**Comment by findborg** [comment]
I looked for an number distribution as well

**Comment by findborg** [comment]
Npm

**Comment by felixnielsen** [comment]
hi @mattbasta good to hear that you see a use-case like this. Will add the feature asap and ping you when ready.

**Comment by findborg** [comment]
Nice

**Comment by smcelhinney** [comment]
Beautiful, I'd like this too. If I can help, let me know.

**Comment by eschaefer** [comment]
In the meantime you can point `conversation-form` to your own repo on GH and import that.

```
npm install yourusername/repo --save
```

And include a properly formatted `package.json` in your GH repo

**Comment by FanaHOVA** [comment]
@felixnielsen Need any help with this? Would be happy to help, but you'll still need to add the package to the npm repo

**Comment by felixnielsen** [comment]
@kalinchernev check [release v0.9.2](https://github.com/space10-community/conversational-form/releases/tag/v0.9.2)
