### ISSUE TITLE
How to submit the post/send the form data to mail.php

### ISSUE THREAD

**Issue by smacbca** [space10-community/conversational-form#220]
sir your forms are grate and its nice but i have one problem i am using simple contact form which post the data to mail.php page to submit the data but the conventional form is not submitting the data please help...

Sample code of my form:
`<form role="form" action="mail.php" method="POST" id="my-form-element" cf-form>
 <label for="name">Name</label>
 <input type="text" placeholder="" name="name" id="name" class="form-control" required>
<label for="email">Email</label>
<input type="email" placeholder="" name="email" id="email" class="form-control" required>
<label for="phone">Phone</label>
<input type="text" name="phone" id="phone" class="form-control" required>
<button class="btn btn-info" type="submit">Submit</button>
 <button class="btn btn-info" type="reset" >Clear</button>
 </form>`

**Comment by jenssogaard** [comment]
@smacbca Have a look at issue #223 which also relates to form submitting. If you need more help please submit a code example including JS - preferably on GitHub or CodePen.
