### ISSUE TITLE
Does it support in mobile android chrome? Error "audio input not supported"

### ISSUE THREAD

**Issue by bubesh03** [space10-community/conversational-form#222]
I have tried your conversational form which works in desktop chrome whereas the same doesn't work in mobile devices, i have tried multiple devices like Iphone and android devices(tried in android version 7, 7.1, 8).
Once the page loads it speaks the first question and after that it shows <strong>"audio input not supported"</strong> and still the notification bar shows the message that <strong>"chrome is accessing the audio input"</strong> and though my headset is connected properly after that error i am able to use only keyboard and not the voice input.

![image](https://user-images.githubusercontent.com/36659735/36417187-3f57c62e-1651-11e8-9a69-6c2411f3c6aa.png)

<strong>screenshot details:</strong>
android version: 8.0
Chrome version: 63.0.3239.111
Phone model: Xiaomi Mi A1

**Comment by jenssogaard** [comment]
Hi @bubesh03. Have you used the voice support example? If that is the case you must load your page over https.

**Comment by bubesh03** [comment]
@jenssogaard I even tried opening your example link "[voice input](https://space10-community.github.io/conversational-form/landingpage/voice-input-output.html)" in mobile, it shows the same error message after speaking the first question and yes I am loading the page over https.

**Comment by jenssogaard** [comment]
@bubesh03 It is somewhat experimental so there is a chance that it will not work. Can you share a link? It's hard for me to help you without any code to test/look at.

**Comment by bubesh03** [comment]
@jenssogaard here is the codepen [link](https://codepen.io/webstuff/full/BYxKEd/)

**Comment by jenssogaard** [comment]
I do not have an Android handset to test on at the moment. But given it's a fairly bleeding edge implementation it is like to not work on some devices: [see the docs](https://space10-community.github.io/conversational-form/docs/0.9.71/functionality/voice/).

**Comment by jenssogaard** [comment]
@bubesh03 I'll close this issue for now. If you figure it out or want to do a different implementation that works then please let me know.

**Comment by RobertoVJ** [comment]
Hi.. there's a way to show the re captcha in the conversational form?..

**Comment by jenssogaard** [comment]
Hi @RobertoVJ. How would you like to use it? Please explain in more detail. Preferably open a new issue.
