### ISSUE TITLE
"Custom submit callback reached, removing Conversational Form, see markup of this file"

### ISSUE THREAD

**Issue by Hotaquet** [space10-community/conversational-form#223]
Hello!
 I'm trying to configure a conversational-form for my contact page, i have an issue when submitting the form (Searched quite a lot on the internet but couldn't manage to figure it out, (for now!)).
So the thing is that i would like the form to be submitted by Formspree(that's possible right?)
I already have a classic form working (Post method to Formspree) on **the same** page (i want the user to have the choice between both classical form and conversational form maybe this is the pb: causing some kind of conflict?
When clicking on Submit the form (Envoyer le formulaire de contact?(in french) at the end of my conversational form i get the following error/warning/alert:

"Custom submit callback reached, removing Conversational Form, see markup of this file"

I did not call any custom submit, that i know of. Ideally i'd like the form submit activation to collect data from my form, email it to me via a "formspree-like-system" and redirect me to a "succes-submit-form-page"

The code of my conversational form:  [Code snippet](https://gist.github.com/Hotaquet/8b5d1be66e06ceb0147eda1a18037d92)
You can also see it online on [My Github Page](https://hotaquet.github.io/) (will not be up to date)
Running Mozilla Firefox 54.0 // Linux Mint

Thanks in advance for any help/advices/suggestions!

Edit: Tried some alternatives to Formspree but the problem is still there: probably caused by having two forms on the same page?
I wish i could do the mailing system myself but my contact page has to be hosted on Github for now (static js/html only sadly)

**Comment by jenssogaard** [comment]
@Hotaquet Have you tried removing the below from your CF-instance?

`submitCallback: function() {
    alert(
      "Custom submit callback reached, removing Conversational Form, see markup of this file"
    );
  }`

**Comment by Hotaquet** [comment]
@jenssogaard  I just did it, everything working, Thanks a lot!

**Comment by jenssogaard** [comment]
@Hotaquet Your are welcome. I'm glad it worked out :)
