### ISSUE TITLE
Help required

### ISSUE THREAD

**Issue by sohelamin** [space10-community/conversational-form#225]
Can I add a custom response to downloadable URL?

Can I use datepicker input or calendar?

**Comment by jenssogaard** [comment]
@sohelamin datepicker, no. We are working on implementing a natural language parser for dates.
I do not understand your first question.

**Comment by sohelamin** [comment]
@jenssogaard I meant, I need to show the user a custom downloadable link based on their answers.
How can I achieve this?

**Comment by jenssogaard** [comment]
@sohelamin alright, first look at conditional logic i [the docs](https://space10-community.github.io/conversational-form/docs/0.9.71/functionality/conditionals-and-branching/). 
For the download link you can do:
`<input type="text" cf-questions="Click <a href='./path/to/some/file.pdf'>here</a> to download your invoice." />`

**Comment by sohelamin** [comment]
@jenssogaard Thanks for the help.
But how can I use a default answer to that question to complete the conversation?

**Comment by jenssogaard** [comment]
@sohelamin in yesterdays release we have added <cf-robot-message> tag that can do that for you:

https://space10-community.github.io/conversational-form/docs/0.9.80/functionality/cf-robot-message/

**Comment by sohelamin** [comment]
Thank you @jenssogaard, very much appreciated 😃

**Comment by jstillwa** [comment]
I think you are still debating putting this feature in or not, but just checked the codepen on a few different browsers and the workaround example doesn't seem to work anymore. More of just an FYI as it doesn't seem like this topic has been chatted about for some time.

**Comment by imsgx** [comment]
@jenssogaard, it is possible to use cf-robot-message with a link tag < a href> ?

I tried here without success

> @sohelamin in yesterdays release we have added tag that can do that for you:
> 
> https://space10-community.github.io/conversational-form/docs/0.9.80/functionality/cf-robot-message/
