### ISSUE TITLE
[question] how to inject a tag and render it not in the flowStepCallback

### ISSUE THREAD

**Issue by mdelantes** [space10-community/conversational-form#226]
Hello,

i am working with a formless conversational form.

Using the flowStepCallBack i can inject and render a tag but i need to inject and render a tag when the user click on a previous answer.

I have add the tag successfully but i can not render it.
What method should i call like the `success()` method to render the tag ?

Thanks you.

**Comment by jenssogaard** [comment]
Hi @mdelantes. Have you tried playing around with `remapTagsAndStartFrom`?
Also if you could post a Codepen that would make it much easier for me to help you.

**Comment by mdelantes** [comment]
@jenssogaard I have try to play with `remapTagsAndStartFrom` .

It fails as the tag has never been render before.

It is difficult to post a codePen as the code is a bit complicated but i will try to do one.

What i don't understand with a formless conversation is how to render a tag without using the `flowStepCallBack` (and it's magic function `success()` ).

using `addTags()` is not enough. In the `flowStepCallBack` `success()` acts as a render method... but how to call a render method in another context ?

In the example of a formless conversation form provided in the doc, there is an initial tag in the json and then all the new tags are added using the `flowStepCallBack`.

But is it possible to start without an initial tag, meaning render a tag not only in the `flowStepCallBack`?

Thanks for your help

**Comment by jenssogaard** [comment]
Hi @mdelantes I'm not quite sure how to help you as of now. Any progress on the CodePen?

**Comment by v3new** [comment]
Hi @mdelantes! Did you do it?

**Comment by jenssogaard** [comment]
@mdelantes  I haven't heard more from you so I assume things worked out. Closing this issue.
