### ISSUE TITLE
Form Submit functionality issue. Should be a simple fix.  : )

### ISSUE THREAD

**Issue by dolanb12** [space10-community/conversational-form#227]
Hello and thank you for the wonderful application!

I've set this up with formspree.io to receive automatic emails with the form data. However, I'm only able to submit the form correctly when typing and sending an additional message after all the fieldsets are completed. I basically just need to understand how to correctly submit the form, and then afterward give some conclusion text to the user. I tried to replicate the example in the appearance section, but no luck. 

Everything else is working great!

[Here's the Wordpress page with the code.](http://qz1.d9c.myftpupload.com/form-test/)

v 0.9.71
Chrome 64

Please forgive me if this is in the documentation--I couldn't find it.

Thank you very much!

**Comment by dolanb12** [comment]
Anyone able to help? Thanks much. : )

**Comment by jenssogaard** [comment]
Hi @dolanb12. Great that you are using Conversational Form. A few ideas to can improve your implementation.

1. Using an AJAX request to submit data to formspring so the user is not redirected. This requires that you use a [custom submit callback](https://space10-community.github.io/conversational-form/docs/0.9.80/functionality/submit-callback/) and here is [someones method for posting to formspring](https://gist.github.com/edmundojr/975b08c39ab0a7a1b514)
2. The last 3 messages can be implemented using `cf-robot-message`-tag. This is new in 0.9.80 and [heres a link to the documentation](https://space10-community.github.io/conversational-form/docs/0.9.80/functionality/cf-robot-message/).

**Comment by dolanb12** [comment]
Saw the close, but wanted to give a late thank you for the help!

Formspree decided to block AJAX callbacks last month, but I can still redirect users to a confirmation page.

=)

**Comment by jenssogaard** [comment]
@dolanb12 you are welcome. Yeah, I think you have to be a premium subscriber of Formspree now to take advantage of AJAX requests. Glad it worked out though.

**Comment by egan-interplay** [comment]
@jenssogaard https://fulfillment-functional6.github.io/fright82/
