### ISSUE TITLE
data-cf-form-element

### ISSUE THREAD

**Issue by laudeco** [space10-community/conversational-form#23]
Why don't you allow the cf-form-element to be prefixed by the standard  data- ?

**Comment by felixnielsen** [comment]
@laudeco from a code perspective, data- would refer to your application so appending data-* to all Conversational Form related attributes would make it seem like those parameters are related to your application. So decision was made to separate concerns clearly.
But to allow for the data-* attribute as a "fallback" would be very easy to implement.

**Comment by laudeco** [comment]
I think this fallback will be useful ;-)

**Comment by felixnielsen** [comment]
@laudeco you are welcome to make a pr ;) It's added to the pipeline from our side, but not a high priority.
