### ISSUE TITLE
multi-line labels for radio buttons

### ISSUE THREAD

**Issue by diedea** [space10-community/conversational-form#230]
I need users to choose between different responses with an average length of 50 words. 

However, radio buttons with long labels are displayed on only two lines with the need for scrolling sideways if I want to read the whole text (or see the second option - see picture). Ideally, I'd display the buttons vertically stacked, with each label spanning multiple lines.
Once selected, the input displays perfectly.

Any idea on how to achieve this? I wasn't able to find the styles necessary to make the right changes - any help is appreciated.

![radiobutton](https://user-images.githubusercontent.com/22870915/37910501-f4fab10e-310d-11e8-999e-a34b45eea65a.PNG)

**Comment by jenssogaard** [comment]
Hi @diedea. I suggest solving it with custom CSS as it's not something I think we will address in CF.
Try this:
`cf-radio-button.cf-button.animate-in {
			display: block;
			max-width: 200px; // Adjust this to whatever width fits your form
		}`

**Comment by diedea** [comment]
Hey @jenssogaard,

unfortunately, this doesn't solve the issue for me, the width doesn't change at all - solving it with custom CSS is completely fine for me, I'm just unable to find the right parameters for finetuning.

**Comment by jenssogaard** [comment]
@diedea Ok, I can help you if you provide me a link. Maybe you can do a CodePen?

**Comment by diedea** [comment]
I posted a minimal example here: https://codepen.io/diedea/pen/pLZywK/
My only worry is really the display of the radio buttons in question 3 since I need some space for other content on the left and right.

Thanks a lot for your help!

**Comment by jenssogaard** [comment]
@diedea I tweaked things a bit - not perfect but it might get you moving forward:

https://codepen.io/space10/pen/qoymMd

**Comment by diedea** [comment]
thanks a lot, this is completely sufficient for my purposes
