### ISSUE TITLE
How to read checkbox and radio button selected values?

### ISSUE THREAD

**Issue by venkateshp1231** [space10-community/conversational-form#231]
When I use below code to read checkbox and radio button selection values I am just getting the input text values but not checkbox and radio button selected values.

`var formData = conversationalForm.getFormData(true);`

I am getting values for textboxes, but for checkbox and radio buttons I am getting string array containing "on"
I am having a radio button list in form to select the position of the job applying for

`var position = formData.position; // ["on"]`

I am also having a checkbox list to select skills, and I selected two skills from conversional form and selected values would be like below

`var skills = formData.skills; // ["on","on"]`

Please post the code how to read radio button and checkbox selection values.

**Comment by jenssogaard** [comment]
@venkateshp1231 see [this example](https://codepen.io/space10/pen/xWYGOq). It seems that you haven't set any values on your fields?

Please post more code or a CodePen if you need further assistance.

**Comment by venkateshp1231** [comment]
@jenssogaard Thank you
