### ISSUE TITLE
How to show different error messages for required, pattern and maxlength validation

### ISSUE THREAD

**Issue by venkateshp1231** [space10-community/conversational-form#232]
How to show different error messages for required, pattern and maxlength validation for a input text element.

Below is the input field in my form with pattern, required and cf-error attributes.

`<input required cf-questions="Hi there! What's your firstname? 😊" type="text" class="form-control" name="firstname" id="name" required="required" maxlength="10" pattern="^[a-zA-Z ]+$" cf-error="Only alphabets are allowed."/>`

Only the error message which is set to cf-error attribute is displayed for three validations I want to show  different messages for required, pattern and maxlength validations. If cf-error attribute is not set then it is showing **Input is required...** for three of these validations. Please help me how to do it.

Also when I set maxlength attribute to input field, in the chat box it is not restricting if we cross the max length.

Please check below code sample which I have done.

[https://codepen.io/VENKATESHP1231/pen/RMQjrO](url)

**Comment by jenssogaard** [comment]
Hi @venkateshp1231. maxlength is not implemented yet so I recommend adding that to your pattern or implement [flowStepCallback validation](https://space10-community.github.io/conversational-form/docs/0.9.80/functionality/validation/). Currently, only one error message is supported.
