### ISSUE TITLE
Inconsistent documentation for addTags and multiple option

### ISSUE THREAD

**Issue by melicerte** [space10-community/conversational-form#235]
The example at [https://space10-community.github.io/conversational-form/docs/0.9.80/functionality/formless/](https://space10-community.github.io/conversational-form/docs/0.9.80/functionality/formless/) does not work as intended concerning the "multiple" attribute on the select tag for choosing between USA and UK.

On the example, user can choose USA **AND** UK.
Replacing _multiple_ with _isMultiChoice_ works. 
Either the parameter name is buggy, or the documentation is not up to date.

**Comment by jenssogaard** [comment]
@melicerte you are right, it is `isMultiChoice` and the example in the docs must be changed. Thank you for pointing this out 👍

**Comment by jemikanegara** [comment]
Hi, I just want to ask why there's no difference between setting isMultiChoice to true and false? checkbox only works if I add "multiple" https://codepen.io/space10/pen/EoKMLg
