### ISSUE TITLE
Uncaught TypeError: CustomEvent is not a constructor

### ISSUE THREAD

**Issue by mjhough** [space10-community/conversational-form#237]
I'm currently using the latest version (0.9.80) of the ConversationalForm package for React, and have been testing in chrome (v65). 

I am running into an issue where I keep getting the below error in my Javascript console, resulting in the ConversationalForm not loading.
![image](https://user-images.githubusercontent.com/31525719/38665524-f1c717f0-3e7f-11e8-844e-b2ed3766a639.png)

My code is just a test form at the moment and looks like this:
```
import React from 'react';
import ConversationalForm from 'conversational-form';

export default class SurveyForm extends React.Component {
    constructor(props) {
        super(props);
        this.cf = null; // <-- Conversational Form ref
    }
    componentDidMount() {
      this.cf = ConversationalForm.startTheConversation({
        formEl: this.refs.form,
        context: document.getElementById("cf-context"),
        flowStepCallback: function(dto, success, error){
            success();
        },
        submitCallback: function(){
            // this callback could also be added to the React.createElement it self...
            alert("You made it!")
            console.log("Form submitted...");
        }
      });
    }
    render() {
      return (
        <div className='col-md5 col-sm-7'>
          <form ref='form' id='survey'>
            <fieldset>
              <input cf-questions='Your name?' placeholder='Name (required)' />
              <input cf-questions='Your email?' ref='email' placeholder='Email (required)' />
              <input cf-questions='Description?' ref='description' placeholder='Description (required)' />
            </fieldset>
          </form>
          <div id='cf-context' className='dark-theme' role='cf-context' cf-context='true' />
        </div>
      )
    }
};
```

**Comment by jenssogaard** [comment]
@mjhough I'm about to look into a possibly related React issue and will try to take a stab at the above issue as well 🙏

**Comment by jenssogaard** [comment]
@mjhough I just tried the above code and did not get any errors. It's hard for me to pin point what your issue is. If you can provide a git repo I'll be happy to take a look.

**Comment by mjhough** [comment]
@jenssogaard Unfortunately I can't provide a repo because it's private. Here is the package.json if that helps. I might try it in a test app as well to see how that goes.

`{
  "scripts": {
    "storybook": "start-storybook -s ./public -p 6006",
    "build-storybook": "build-storybook"
  },
  "dependencies": {
    "@rails/webpacker": "^3.2.2",
    "babel-preset-react": "^6.24.1",
    "conversational-form": "^0.9.80",
    "howler": "^2.0.9",
    "moment": "^2.20.1",
    "prop-types": "^15.6.0",
    "react": "^16.2.0",
    "react-chat-form": "^0.0.13",
    "react-conversation-form": "^2.0.1",
    "react-dom": "^16.2.0"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^3.3.12",
    "@storybook/addon-links": "^3.3.12",
    "@storybook/addons": "^3.3.12",
    "@storybook/react": "^3.3.12",
    "babel-core": "^6.26.0",
    "webpack-dev-server": "^2.11.2"
  }
}
`

**Comment by jenssogaard** [comment]
@mjhough Ok, then my best advice would be to try and make a new branch of your project and strip out dependencies and see if something is messing with Conversational Form.

**Comment by PradhumnaPancholi** [comment]
I have the same kind of issue where it says "Survey is not a constructor".
I still can't fix it but I guess I found the reason that my DB model for survey didn' load by the time.

Can anyone help?
Here is my git repo: https://github.com/PradhumnaPancholi/Mail-it

**Comment by jenssogaard** [comment]
@PradhumnaPancholi hmm, are you in the wrong repository? I don't see you using CF. If I am wrong then please expand on your problem so that we have a decent chance of helping you.

**Comment by PradhumnaPancholi** [comment]
> @PradhumnaPancholi hmm, are you in the wrong repository? I don't see you using CF. If I am wrong then please expand on your problem so that we have a decent chance of helping you.

Sorry, my bad. I forgot to push my recent changes. It's up to date now.

**Comment by jenssogaard** [comment]
@PradhumnaPancholi I still don't see it. Also please refer to where exactly in your code you encounter the issue. Please help me help you.
