### ISSUE TITLE
Uncaught TypeError: Cannot read property 'skipUserInput' of null

### ISSUE THREAD

**Issue by beevelop** [space10-community/conversational-form#238]
Affected version of Conversation-Form: `v0.9.80`

ConversationalForm instantiates the ChatResponse with `options.tag` set to null explicitly https://github.com/space10-community/conversational-form/blob/589a276944bacdf5fff03a969f94c85ecfcff9df/src/scripts/cf/ConversationalForm.ts#L335

But the ChatResponse later checks for the `skipUserInput` attribute:
https://github.com/space10-community/conversational-form/blob/589a276944bacdf5fff03a969f94c85ecfcff9df/src/scripts/cf/ui/chat/ChatResponse.ts#L238

This leads to the following exception:
> Uncaught TypeError: Cannot read property 'skipUserInput' of null at conversational-form.js:4742

**Comment by jenssogaard** [comment]
@beevelop thank you for the bug report. I really appreciate that. Can you provide an example or more detail on when the error occurs?

**Comment by ofuochi** [comment]
I'm still having getting this error. I'm pointing to this.

https://cdn.jsdelivr.net/gh/space10-community/conversational-form@0.9.80/dist/conversational-form.min.js

It hasn't taken effect yet.

**Comment by jenssogaard** [comment]
@ofuochi It has not been released yet. You can however find a pre-release in the develop branch.

**Comment by jenssogaard** [comment]
This has been fixed in the latest [v0.9.81 bugfixes release](https://github.com/space10-community/conversational-form/releases/tag/v0.9.81).
