### ISSUE TITLE
Bug when editing previous answer

### ISSUE THREAD

**Issue by luisdil** [space10-community/conversational-form#239]
Hello there,

I've encountered a bug when editing a previously given answer in combination with the new "cf-robot-message" tag. If you try to edit a input/question which is followed by a "cf-robot-message" tag, the input which follows the "cf-robot-message" tag will be skipped.

Steps to reproduce:
1. Visit my codepen https://codepen.io/luisdl/pen/pLMdPY
2. Select "Yes, ready to begin"
3. Click on the answer you just gave in the chat
4. Click on "Yes, ready to begin" again.

The next question which should be "What is your firstname?" will be skipped...

Afaik the bug appears on all browsers and platforms.

**Comment by jenssogaard** [comment]
@luisdil you are absolutely right. Good catch.

**Comment by luisdil** [comment]
Thank you for making this great stuff in the first place! Can you already estimate when the fix will be in production?

**Comment by jenssogaard** [comment]
@luisdil I'll try to do a patch in the coming week.

**Comment by sijiahahaha** [comment]
@luisdil I'm facing the same issue but I found a way to solve it.

Just add a name and value attribute inside the "cf-robot-message" tag, such as name="info", id="info", value="1".

For the following input or select tag, just add a condition like cf-conditional-info="1".

Then when you editing the tag following "cf-robot-message" tag, it won't skip.

**Comment by jenssogaard** [comment]
@sijiahahaha are you using the latest version? It's fixed in [v0.9.81](https://github.com/space10-community/conversational-form/releases/tag/v0.9.81)

**Comment by sijiahahaha** [comment]
@jenssogaard Oh I'm using the v0.9.80 lol. I will update! Thank you for the amazing work!
