### ISSUE TITLE
Adding html tags to questions and responses

### ISSUE THREAD

**Issue by BenRacicot** [space10-community/conversational-form#240]
Just a simple question about adding html to questions and response text. 

I've seen that some of the examples show the use of tags such as `<strong>gr8</strong>`. How would we go about adding a link with `<a href="">link text</a>`?

**Example:**
`<cf-robot-message cf-questions="Thanks! Do you have <a href="/#">more ideas</a>?"></cf-robot-message>`

**Custom buttons done right**
I'm also trying to track down the button at the end of the example form [here](https://space10-community.github.io/conversational-form/landingpage/). It seems to be a custom button that refreshed the page. Can you help me understand how to properly add a linkable button within a form?

Right now I'm cheating with `cf-validation`

``` 
<fieldset cf-questions="Visit another page?">
        <input type="radio" value="yes" cf-validation="window.location.hash = '#another-page' ">
        <label for="above">Let's go!</label>
</fieldset>```

**Comment by jenssogaard** [comment]
Hi @BenRacicot Have a look at #225 where I answer the question about how to add a link. The key is escaping. 

The button and the end of the page you are refering to. That is just a single button as the last element i the form and once done it submits the form. You can then add a [custom form callback](https://space10-community.github.io/conversational-form/docs/0.9.80/functionality/submit-callback/). You could then do a simple window.location.href = "/some-other-page/" if you wanted to send the user to somewhere.
