### ISSUE TITLE
Conditional fields

### ISSUE THREAD

**Issue by demian1985** [space10-community/conversational-form#241]
Hi!

An amazing plugin you guys have build!

I have a question about conditional fields, this [thread](https://github.com/space10-community/conversational-form/issues/18) is not clear for me how to use the attribute cf-conditional for the form (provided links of the thread are broken). Are you able to provide a HTML example how I can add this in CF7?

On a sidenote, CF7 has a [Conditional Fields](https://wordpress.org/plugins/cf7-conditional-fields/) add on plugin, it works for the regular CF7 forms, but it doesn't collaborate 100% with Conditional Forms.

Thanks in advance!

Demian

**Comment by jenssogaard** [comment]
@demian1985 thank you, we really appreciate your feedback. Have you checked out [this section of the documentation pages](https://space10-community.github.io/conversational-form/docs/0.9.80/functionality/conditionals-and-branching/)?

The conditional plugin for CF7 is specific for CF7 and will not work with Conversational Form. So if you want to do conditionals in Conversational Form you must look at the docs above. 

Let me know if you have additional questions.

**Comment by demian1985** [comment]
@jenssogaard Thank you! That link was broken in the original thread.

**Comment by jenssogaard** [comment]
@demian1985 you are welcome. I'll close this issue for now. Feel free to reopen if needed.
