### ISSUE TITLE
Other option in multiple select

### ISSUE THREAD

**Issue by demian1985** [space10-community/conversational-form#242]
Hi,

I went through the existing issues, and more have talked about this, but can't see a final solution. It's the "other" answer and able to type a different answer from the existing answers (in this case in **multiple select** input ). So for example:
Which color do you like?
- blue
- red
- yellow
- green
- other, such as.

And when "other" is selected, user can type a free answer. I tried the conditional input, but it's not working in a multiple select input. Is this actually possible?

Many thanks!

Demian

**Comment by jenssogaard** [comment]
@demian1985 Good question. I have made a demo showing you how achieve this using conditionals: https://codepen.io/space10/pen/RyogMg

**Comment by demian1985** [comment]
@jenssogaard  Thank you for the demo. In this demo the "other" option will be in the next question, but is it possible to answer other in the current input box and disable the "type to filter"?

**Comment by jenssogaard** [comment]
@demian1985 I don't believe it's possible to disable 'type to filter'.

**Comment by TakesTheBiscuit** [comment]
@demian1985 @jenssogaard if you see pull #245 i've added an event for clicking multiple choice, there's already an event for radio buttons; you could simply hook that event and if they click an option with the 'other' label you could programmatically move to the next question?
