### ISSUE TITLE
hideUserInputOnNoneTextInput input text field focus is broken

### ISSUE THREAD

**Issue by demian1985** [space10-community/conversational-form#243]
Hi,

I use the hideUserInputOnNoneTextInput option (see below). It does what it should do; hides the input fields except when `type='text'`. Perfect!

```
new cf.ConversationalForm({
  formEl: form,
  hideUserInputOnNoneTextInput: true,
});
```

However, when this is enabled, the text input fields are not working anymore how they should work. After typing each single character the cursor focus disappears and the input field needs to be selected again. I tested it in your [demo pages](https://codepen.io/space10/pen/ZrzNeM) as well, same result. Is this normal and do I need to add an extra event or is this a bug?

Thanks!

**_edit_**
One extra issue I came across: the button is missing when arriving on a `<select multiple` question. Answers on a mobile phone can not be submitted.

**_update_**
Above button being missed, can be resolved by creating an `<input type="checkbox"` (not ideal). Only with this option the previous answer cannot be modified correctly. Seem to be related to [#239](https://github.com/space10-community/conversational-form/issues/239). All by all, one alternative solution gives a new issue. Please, use the below html to see the result for this issue. See also my request to use 'other' in multiple select option at #242 .

```
<fieldset cf-questions="What do you like to do in the weekend?">
<input type="checkbox" id="creating-forms" name="weekend" value="creating-forms"><label for="creating-forms">Creating forms</label>
<input type="checkbox" id="chatting" name="weekend" value="chatting"><label for="chatting">Chatting on Github</label>
<input type="checkbox" id="sleeping" name="weekend" value="sleeping"><label for="sleeping">Sleeping</label>
<input type="checkbox" id="other" name="weekend" value="other"><label for="other">Other</label>
</fieldset>
<fieldset cf-questions="You selected 'Other'. Please, let me what else you do?">
<input type="text" cf-conditional-weekend="^other$">
</fieldset>
```

**Comment by TakesTheBiscuit** [comment]
hey @demian1985 what device model & operating system & browser (with version) are you seeing this issue?

**Comment by demian1985** [comment]
On Windows 10 pro version 1703, Chrome browser latest version. And iPhone 6S iOS 11.3. I did some cross checks on friends’ devices. Same issue.

**Comment by jenssogaard** [comment]
@demian1985 I am fixing the issue where submit button is missing for `multiple` right now.

_"the text input fields are not working anymore how they should work"_ I can not reproduce this issue.

**Comment by demian1985** [comment]
@jenssogaard Sorry this was too long time ago, I remember that the cursor focus disappeared after each typed character, happened on desktop and mobile devices. This was also the reason for me to stop using the robot chat survey. 

I have tried to duplicate this scenario as well, but it's too long time ago for me to remember. Sorry.

**Comment by jenssogaard** [comment]
@demian1985 alright, I'll close this for now. Fill free to open another issue if needed.
