### ISSUE TITLE
No piping between web and conversational form's field values.

### ISSUE THREAD

**Issue by hassantauqeer** [space10-community/conversational-form#246]
In this [example](https://space10-community.github.io/conversational-form/landingpage/)  when I update a field in the conversational form it successfully updates it in web form but it doesn't update conversational form's field when I update it in web form.

**Comment by jenssogaard** [comment]
hi @hassantauqeer. That example is not using the latest version of CF and I don't think value piping is enabled on that.

Have a look at the documentation which includes a working example:
https://space10-community.github.io/conversational-form/docs/0.9.80/functionality/value-piping/

**Comment by hassantauqeer** [comment]
When I update Web form only values in <textarea/> get updated but I've to press enter every time to show them in <scrollable/>. Isn't there something that when I update Web form (1 or more fields) and then I switch to CF it shows me all the updated fields in <scrollable/> like it shows when I updated them in CF itself. Databinding will be a correct term instead of piping as u said.
