### ISSUE TITLE
Can't use cf in React App. EventDispatcher is not a constructor

### ISSUE THREAD

**Issue by hassantauqeer** [space10-community/conversational-form#247]
Here is my code:

`
import cf from "conversational-form";
console.log(cf, window.cf, "cf moiunted");
`
**cf** (console) = 
`ƒ ConversationalForm(options) {
            this.version = "0.9.80";
            this.cdnPath = "https://cdn.jsdelivr.net/gh/space10-community/conversational-form@{version}/dist/";
            this.isD…`

**window.cf** (console) = {Helpers: ƒ, EventDispatcher: ƒ, TagsParser: ƒ, BasicElement: ƒ, ControlElementEvents: {…}, …}

Now both cf instances give different functions, window.cf can be used but as described in [docs here](https://space10-community.github.io/conversational-form/docs/0.9.80/events/#events) when I use imported **cf** it doesn't work as described in docs.

**Comment by jenssogaard** [comment]
@hassantauqeer have a look at #218
