### ISSUE TITLE
Doesn't fill up form fields automatically

### ISSUE THREAD

**Issue by hassantauqeer** [space10-community/conversational-form#248]
If I set values of all some form fields in the form and convert it to Conversational Form. The <scrollable/> doesn't fill up automatically with the prefilled values of input, but it should.

Am I missing something or this can't be done currently?

**Comment by jenssogaard** [comment]
@hassantauqeer yes, the idea is that if value attribute is set it will be prepopulated. Do you have an example that shows the issue?

**Comment by hassantauqeer** [comment]
@jenssogaard Yes, in [demo app here](https://space10-community.github.io/conversational-form/landingpage/) When i Fill values in conversational form and toogle back to Web Form i values of Web forms are filled with respective to Conv form, but unlike this when I filll values in web form and toggle to Conversational Form Value attributes are filled and appear only in <textbox/> for each particular Question and then I've to press enter tho show tha Question and answer in <Scrollable/> while it should put all the filled question(fields) and answers(values) in <scrollable/> as i fill its value in web Form like it do in Conversational form.

**Comment by jenssogaard** [comment]
@hassantauqeer I'm sorry. I'm not exactly sure what you are requesting and I have a hard time seeing the big issue. Sorry. Feel free to do more documentation on the issue and we can discuss further. A Pull Request is also always more than welcome.
