### ISSUE TITLE
conversational form and meteor.js

### ISSUE THREAD

**Issue by diedea** [space10-community/conversational-form#249]
Created a separate issue from [#218](https://github.com/space10-community/conversational-form/issues/218) since there seems to be another (meteor specific?) problem:

When using the npm package in meteor, the chat form is displayed and works partly (e.g. robotResponseTime can be set unusually high), however other options such as robotImage/userImage cannot be set, fieldset/radio buttons does not work properly (all buttons from several fieldsets are displayed together) and cf.EventDispatcher throws the infamous "cf.EventDispatcher is not a constructor" error (#218, #247)

I put together a sample repository [here](https://github.com/diedea/conv_bot).

Do the form options somehow differ from each other so that one works and the other one doesn't? Does anyone using Webpack/React... have similar issues? I'm a little confused and don't really know where to start reading/digging into.

**Comment by jenssogaard** [comment]
Thanks @diedea. I'll try to take a look very soon.

**Comment by diedea** [comment]
got it to work by including the script (not the package) and setting my options directly in there - not ideal, but working at least
