### ISSUE TITLE
window.ConversationalForm.addTags() does not displaying in ajax error response

### ISSUE THREAD

**Issue by ofuochi** [space10-community/conversational-form#250]
Hello, thanks for this plugin. I'm using the 0.9.80 version
I found that if I make an ajax call and an error was returned from the server, using the window.CoversationalForm.addTags() method does not add any element to the DOM as expected. However if the server returns successfully, call this same method adds element to the DOM as expected. Find below an example.

```
flowStepCallback:{
    $.ajax({
      url: "/api/pathToMyResource",
      data:someData,
      type: "POST"
    }).done(()=>{
      //this adds element to the DOM as expected
      window.ConversationalForm.addTags([{
                                        tag: "input",
                                        "cf-questions": "Display success message in DOM"
                                    }]);
      success();
     }).error(()=>{
       //this does NOT add element to the DOM as expected
       window.ConversationalForm.addTags([{
                                        tag: "input",
                                        "cf-questions": "Display error message in DOM"
                                    }]);
         error("an error has occured");
    });
}
```

I don't seem to understand the reason for this.

**Comment by jenssogaard** [comment]
@ofuochi that's a good question. I can see that you don't call success(); when error() is resolved. You might want to look into that.
