### ISSUE TITLE
Suggested Response?

### ISSUE THREAD

**Issue by mj66** [space10-community/conversational-form#251]
So far I loved this project. However, this does lack some functionality...

Is it possible under my current version (0.9.70) to provide "suggested responses" (UI wise it will look like radio buttons) but still allow users to type in their own response? 

If yes, where is the documentation provided for that? If not, any suggestions for me to implement this on my end? 

Apologize for this not being an actual "issue". Keep up the work!

**Comment by jenssogaard** [comment]
@mj66 thank you - I'm always happy to hear feedback. There is a few ways that could be done:
- Allow own response for [radio group](https://space10-community.github.io/conversational-form/docs/0.9.80/functionality/image-answers/)
- Add actual typeahead support using custom attribute

**Comment by mj66** [comment]
@jenssogaard Can you provide an example of how I can achieve it with radio groups? I could not figure out how to accept custom responses for that. 

Thanks!
