### ISSUE TITLE
Hide radio and only show after typing in and filterd

### ISSUE THREAD

**Issue by sijiahahaha** [space10-community/conversational-form#253]
Hi,

I'm using this project and it's awesome! 

In my survey, I have some questions with so many choices(like choose which state you live in).

I want to hide the radio at first and be shown after typing in some letters (like show Washington after typing in wa). I'm trying to set up a UserInputEvents.KEY_CHANGE dispatcher on this particular question by id rather than the whole form, but I failed....Is it possible to do that?

Or, is it possible to have a drop-down selection? How can I achieve that?

Thank you!

**Comment by jenssogaard** [comment]
@sijiahahaha I see that you are discussing a possible solution in a different thread. I'll close this issue for now.
