### ISSUE TITLE
Support for Autocomplete? 

### ISSUE THREAD

**Issue by mearleycf** [space10-community/conversational-form#255]
Are you considering providing support for autocomplete? I've got a field with thousands of possible selections, and our current implementation allows the user to type to see a shortened list (in a dropdown) of possible values.

**Comment by jenssogaard** [comment]
@mearleycf you are not the first asking and yes, it might be something that we'll look into very soon.

**Comment by Jeanromain** [comment]
Hi, Do you have any news about this feature ?

**Comment by jenssogaard** [comment]
Native autocomplete support has been implemented in the latest release. Closing this issue for now.
