### ISSUE TITLE
XML Parsing errors in Firefox, IE and Edge.

### ISSUE THREAD

**Issue by AfaanBilal** [space10-community/conversational-form#256]
Hi,

Thank you for your amazing work on this!

The recent versions of CF (after 0.9.6) are showing up errors in XML parsing of some files. I'm not sure what's causing them but I think they're in the blue up arrow files.

Can you please have a look?

Thanks!

**Comment by jenssogaard** [comment]
@AfaanBilal Thank you very much for reporting, I'll investigate tomorrow and if needed apply a hot fix.
