### ISSUE TITLE
Submission by e-mail

### ISSUE THREAD

**Issue by godinho29** [space10-community/conversational-form#257]
Hi,
I have already read and applied about customization, but I can't found anything about the submission. Can you give some informations about how can I sent the data from the form by e-mail?

Thank you! This is an  awesome innovation and it's really awesome

**Comment by jenssogaard** [comment]
Hi @godinho29. You can use the [custom submit callback](https://space10-community.github.io/conversational-form/docs/0.9.80/functionality/submit-callback/) and then do an AJAX request to your server which then sends the form data in an email.
