### ISSUE TITLE
Can't edit on Chrome

### ISSUE THREAD

**Issue by Moorst** [space10-community/conversational-form#259]
Can't edit user inputs on chrome, though seems to work fine in Edge & Firefox. When clicking the previous response nothing happens.

Noticed this has stopped working on a version of the bot I've had running a while on a site. Tested on your demo https://space10-community.github.io/conversational-form/landingpage/ and broken there too.

**Comment by jenssogaard** [comment]
Hi @Moorst. They landingpage you are refering to is using an older version 0.9.6 - I just tried [this demo that uses the latest version](https://codepen.io/space10/pen/JMXzGX) and editing works fine here. Can you tell me which version you are using? Also I would recommend that you upgrade to the latest version.

**Comment by jenssogaard** [comment]
@Moorst I see. I just tried using Browserstack (Win 10, Chrome 68.0.3440.75) and I had no issues editing using the before mentioned Codepen. Hmm, not sure what's going on? 😕

**Comment by Moorst** [comment]
Yeah really strange, there's no error or anything, not sure what's going on.

**Comment by jenssogaard** [comment]
@Moorst yeah, really weird. I'm going to close this issue for now. Feel free to reopen if needed.
