### ISSUE TITLE
Skipping questions

### ISSUE THREAD

**Issue by xclntdesign** [space10-community/conversational-form#26]
It seems that all fields are required. I think it would be nice to be able to skip a question by hitting enter and get a response like "OK, we don't need that information to proceed." or even better, a programmed response, similar to the question field.

**Comment by felixnielsen** [comment]
@xclntdesign we could make it so if the [standard attr](http://www.w3schools.com/TAgs/att_input_required.asp) `required` is not present then the field can be blank. Also I like the idea of having a standard blank-input answer for the Dictionary. Could be an extra attr to a tag:
```html
<input cf-empty-response="OK, we don't need that information to proceed." ...
```

**Comment by danielfriis** [comment]
+1

And let's use the standard `required` attribute.

**Comment by SampsonCrowley** [comment]
@felixnielsen the pull request I submitted utilizes this behavior with the standard `required` attr
