### ISSUE TITLE
Options spanning more than 2 lines?

### ISSUE THREAD

**Issue by AfaanBilal** [space10-community/conversational-form#261]
Hi,

Thank you for your amazing work on this!

Sometime, we have a lot of options for a `<select>` input and the options are shown spanning two lines and scrolling horizontally. Could we have a method to make them appear on more than two lines so that we could get rid of the horizontal scrolling?

Thank you.

**Comment by jenssogaard** [comment]
Hi @AfaanBilal. I suppose we could add a no-scroll option. So if you have lots of options, as you describe, would you then just want vertical scroll instead?

**Comment by AfaanBilal** [comment]
Hi @jenssogaard Thank you for taking some time with this!

Yes, a vertical scroll would solve the problem!

Thanks again!

**Comment by jenssogaard** [comment]
@AfaanBilal this request has not been implemented and it will not get any focus in the upcoming release. I'll close this issue for now but will keep it on the list of potential features we will work on at some point.
