### ISSUE TITLE
Replace submit icon by text

### ISSUE THREAD

**Issue by ricocaldeira** [space10-community/conversational-form#262]
Hi everyone! Is there a possibility to replace that form "up arrow" by a text, just like "OK" or "Submit"?

<img width="628" alt="captura de tela 2018-09-03 as 02 22 10" src="https://user-images.githubusercontent.com/38027/44968958-29828000-af21-11e8-9342-bd522560efe6.png">

I searched a lot inside documentation, but found no answer.

**Comment by jenssogaard** [comment]
You can override the CSS and add your own background-image at `cf-input-button.cf-input-button div.cf-icon-progress`

**Comment by ricocaldeira** [comment]
Only images are allowed?

**Comment by jenssogaard** [comment]
It's a css property, so you can use whatever is allowed per CSS specifications. We have added a `background-image` and you can start by overriding that property.
