### ISSUE TITLE
Upload of document or image using conversarional

### ISSUE THREAD

**Issue by anyasorc** [space10-community/conversational-form#263]
Hi Guys,

Saw your excellent work on converting boring forms into a more customer engaging forms.

Kudos to you guys and am really excited about it.

I am having a challenge which I believe you guys can assist with code same to help out with.

The issue
I have a web form that requires users to upload their cv or an image and am wondering how this could also turn conversational and also how I can upload to a path.

Will be glad to hear from you.

**Comment by jenssogaard** [comment]
Hi @anyasorc. We are happy that you like our work. I assume you post to a url when the user is done and you collect the form information. That would be the same place where you would handle the file upload/move it to a directory of your choice.

To where do you submit your form now and what do you do with the data?
