### ISSUE TITLE
edit answer feature not working?

### ISSUE THREAD

**Issue by benneynens** [space10-community/conversational-form#264]
Please check the list below to make sure we can provide you the best possible support :star: 

- I have provided a code example. (Two examples to get you started https://codepen.io/jenssog/pen/mqXMQW, https://jsfiddle.net/Jenssog/nq4z68hw/)
- If I encountered an issue I have provided:
  - a description of the actual and expected behavior
  - what version of Conversational Forms I am using
  - what browser and version I am using
  - the output of the browser console

**Comment by benneynens** [comment]
Is the edit previous answer function working?

I have tried clicking on an previous answer here, and there is no response to click on the blue bubble containing that answer: https://space10-community.github.io/conversational-form/landingpage/click-edit-previous-answer.html

Not sure if I'm doing something wrong, or if there is a bug..??

**Comment by Moorst** [comment]
I've had the same issue (https://github.com/space10-community/conversational-form/issues/259), though I thought it was just in Chrome.

I've just tested in Firefox and having the same problem. Works fine in Edge though.

**Comment by jenssogaard** [comment]
@benneynens could you do a video of what you see? I would like to clear up any potential misunderstandings (actually @Moorst, if you could do the same?)

**Comment by Moorst** [comment]
@jenssogaard I included a gif in the issue I raised, https://github.com/space10-community/conversational-form/issues/259. I'm clicking when hovering the previous answers

**Comment by jenssogaard** [comment]
@Moorst do you see any errors in the console? Again I can not reproduce this :/
