### ISSUE TITLE
How to show that a robot is thinking?

### ISSUE THREAD

**Issue by chrismuiruriz** [space10-community/conversational-form#265]
Please check the list below to make sure we can provide you the best possible support :star: 

- I have provided a code example. (Two examples to get you started https://codepen.io/jenssog/pen/mqXMQW, https://jsfiddle.net/Jenssog/nq4z68hw/)
- If I encountered an issue I have provided:
  - a description of the actual and expected behavior
  - what version of Conversational Forms I am using
  - what browser and version I am using
  - the output of the browser console

**Comment by jenssogaard** [comment]
Hi @chrismuiruriz. Just pass the `userInterfaceOptions` like the below example:

```
var conversationalForm = conversationalForm.startTheConversation({
    formEl: document.getElementById("form"),
    context: document.getElementById("cf-context"),
    userInterfaceOptions:{
        robot: {
            robotResponseTime: 2000
        }
    }
 });
