### ISSUE TITLE
flowStepCallBack not working

### ISSUE THREAD

**Issue by b4rracuda** [space10-community/conversational-form#266]
Hello, this is a good lib but flowStepCallBack is just not working for me, I have copied it from Docs > Validation, but it just does not work, none of console.logs are showing.

CodePen:
https://codepen.io/anon/pen/zJyepX

What could be the problem?
Thanks

**Comment by b4rracuda** [comment]
Alright, I fixed it with putting the actual initialization in **window.onload** :
`window.onload = function(){
		$("form#chatbot").conversationalForm(parameters)
}`

Please add this to docs, this is not an obvious thing. Spent like two evenings straight trying to fix this

**Comment by jenssogaard** [comment]
@b4rracuda thanks for your feedback. I'll consider adding it to the documentation.
