### ISSUE TITLE
Question: Can we make condition based on previous response?

### ISSUE THREAD

**Issue by MuyBien** [space10-community/conversational-form#27]
Amazing work guys!!!
I was just wondering if it was possible to propose form inputs based on a previous response?

For example, if for the possible answers for question 3 depends on answer for question 2?

Thanks!

**Comment by felixnielsen** [comment]
@MuyBien already working on a proposal, please see this [thread](https://github.com/space10-community/conversational-form/issues/18) let me know if you have any thoughts.
