### ISSUE TITLE
Force to use the "submit" button instead of enter button on keyboard.

### ISSUE THREAD

**Issue by AlbertNessa** [space10-community/conversational-form#270]
I am running this fantastic script in my Unbounce landing page. Since in Japanese you hit the enter button on the keyboard(on Desktop PCs) to select the Kanji before proceeding to the next word, it always jumps directly to the next question before they are able to enter their full name. For example the user wants to enter the name "Hiro Kato", they type in Hiro on their Keyboard, select the kanji with "Enter" and then type in "Kato" in Kanji and hit enter again. The script currently behaves that after entering "Hiro" they press enter (to select the Kanji) and it jumps directly to the next question. So they cannot enter their full name. Is there a possibility to force pressing the right submit button only when entering text? Thanks!

**Comment by jenssogaard** [comment]
Hi @AlbertNessa. Thank you for bringing this to my attention. That definitely makes sense for the scenario you describe and I'll put it on the roadmap for v1.0.0

**Comment by jenssogaard** [comment]
Hi @AlbertNessa. I have just released [v0.9.90](https://github.com/space10-community/conversational-form/releases/tag/v0.9.90) with a `preventSubmitOnEnter` option. I hope it works for your situation.

**Comment by Firetrip** [comment]
Hi @jenssogaard
I cannot find any more infos on this feature. Is it just an attribute for a input field or how is it designed to work?

**Comment by jenssogaard** [comment]
@Firetrip you can find it on the [options page](https://space10-community.github.io/conversational-form/docs/0.9.90/options/). It is a global setting for your Conversational Form. Let me know if you have any more questions.
