### ISSUE TITLE
Documentation not complete

### ISSUE THREAD

**Issue by Firetrip** [space10-community/conversational-form#271]
Hi everybody,

so I started out with conversational forms two weeks ago and my starting point was the doc [ here](https://space10-community.github.io/conversational-form/docs/0.9.80/getting-started/).

However, after looking through all the issues and talks on the github page I am sure that a lot of hidden features are not included in the doc.  For example the option to make the answers fixed and not being able to edit them (by removing pointer events).
Is there a plan on making the documentation more complete? Or is there a project on adding information to the documentation where I could help? I would also love to add some ideas on how to do certain things, like removing the scrollbar for firefox and I think it would be great to add all of that to the documentation so new developers have an easier start :)

**Comment by jenssogaard** [comment]
Hi @Firetrip. As with most open project here on Github help is always much appreciated and that is what makes things move forward.

We always try to add to the documentation and to make it as easy as possible to digest without adding too many edge-case examples.

You are welcome to submit a PR with additional documentation or create individual tickets with concrete suggestions to the documentation.
