### ISSUE TITLE
Question: Why my form disappears?

### ISSUE THREAD

**Issue by yukyolol** [space10-community/conversational-form#272]
Hello, I'm starting to use forms on my app and look's amazing!!

Atm I'm using this from this example: https://space10-community.github.io/conversational-form/docs/0.9.90/functionality/custom-questions/  (Example - {One way value-binding})

https://codepen.io/space10/pen/eyZXBO

Why the HTML fields are visible? And also happens something weird on my website. When I press right-click and use Inspect tool, the conversational form disappears and only the HTML forms are visible

Another question: Is there any way to init the form using code like: Conversational.form(initiate) or something like that? Maybe if initing the form manually it will fix the issue.

Thanks!

**Comment by jenssogaard** [comment]
Hi @yukyolol. I am glad that you like Conversational Forms. I'll try to answer your questions below:

**Initiate manually**: See [this example](https://codepen.io/space10/pen/mqXMQW).

**Right click** I have no idea. Sounds strange.

**HTML fields are visible** I guess you just need to hide your form with CSS.

I hope that helps you.

**Comment by jenssogaard** [comment]
I'll close the issue but feel free to ask more questions in this thread :)
