### ISSUE TITLE
Web accessibility

### ISSUE THREAD

**Issue by jw-miaem** [space10-community/conversational-form#273]
Hello,

Just wanted to ask if this has been optimised for screen readers and assistive devcies. I'm considering using this for a project that is optimsied for web accessbility

Thanks

**Comment by jenssogaard** [comment]
Hi @jw-miaem. It has not been optimized for screen readers and web accessibility. If you have good experience in the field I would be happy if you could report back on your findings and I would then be happy to take them into serious consideration.

**Comment by jw-miaem** [comment]
Hi @jenssogaard Thanks for reply. If product owners want to go ahead then I think some work will be made in this area so will definitely report back. Of the top of my ahead I'd imagine aria-live may be useful for this situation...testing will need to be carried out

**Comment by jenssogaard** [comment]
@jw-miaem sounds good. Keep me posted. In the meantime, I'll take a look myself.
