### ISSUE TITLE
Clearing user input with formless

### ISSUE THREAD

**Issue by MSBPeace** [space10-community/conversational-form#277]
When using the formless implementation the user input field retains the last text input value until a new tag is added. Is there a way to prevent this and clear the value immediately upon submit?

**Comment by jenssogaard** [comment]
Hi @MSBPeace. Could you cook up a quick example that shows the issue? Maybe fork [this formless codepen](https://codepen.io/space10/pen/EoKMLg)?

**Comment by MSBPeace** [comment]
@jenssogaard Yes I have made a rough illustration of how I use it currently in [this codepen](https://codepen.io/anon/pen/zyaoRj?editors=1111).

I hope it sufficiently illustrates my problem. I'm currently using a similar setup since I use sockets to communicate back and forth and will not know in advance how long this form will be (it's dynamic).

**Comment by MSBPeace** [comment]
@jenssogaard Hey is there anything else I can help with to speed towards a solution to this problem?
Implementing a manual clear action seems simple enough but I'm still unsure as if that is the desired approach.

**Comment by jenssogaard** [comment]
Hio @MSBPeace sorry for the late reply. How about using the below when needed?
`window.conversationalForm.userInput.resetValue()`

**Comment by MSBPeace** [comment]
@jenssogaard YES! this definitely solves my problem, I'm calling it right now right after calling 
`success()` in `onStepCallback` and it resets the input field to the default value while still correctly submitting the inputted ones. Was this function mentioned anywhere in the docs? If not want me to make a PR for people having similar issues in the future?

**Comment by jenssogaard** [comment]
@MSBPeace happy to hear that it solved your issues. It is not documented - I am about to update the docs later this week so I'll add it then. No need for you to do a PR at this point in time (although I am always happy when people contribute).
