### ISSUE TITLE
How to have validation only if one more checkbox is selected ?

### ISSUE THREAD

**Issue by tibewww** [space10-community/conversational-form#278]
Hi All,

Great script;

one thing I'm trying to achieve is the following using some checkbox:
How can we have the validation only working if one or more checkbox is selected ? 
Currently if the user does not choose any checkbox, he can go to the next step . . .

Any help with that will be awesome !

Many thanks !

**Comment by jenssogaard** [comment]
@tibewww can you provide a Codepen, thanks.

**Comment by jenssogaard** [comment]
Hi @tibewww. Since you haven't added a codepen I'll go ahead and close this issue. Feel free to reopen or open a new issue at a later point.
