### ISSUE TITLE
Validation adjustment

### ISSUE THREAD

**Issue by xclntdesign** [space10-community/conversational-form#28]
I needed to pass the field name as a second parameter for validation.

Changed this:
`Tag.prototype.setTagValueAndIsValid=function(t){var e=!0,A=t.text;return this.pattern&&(e=this.pattern.test(A)),e&&this.validationCallback&&(e=this.validationCallback(A)),""==A&&(e=!1),e&&"file"!=this.type&&(this.domElement.value=A),e}`

To this:
`Tag.prototype.setTagValueAndIsValid=function(t){var e=!0,A=t.text,B=t.input.currentTag.name;return this.pattern&&(e=this.pattern.test(A)),e&&this.validationCallback&&(e=this.validationCallback(A,B)),""==A&&(e=!1),e&&"file"!=this.type&&(this.domElement.value=A),e}`

**Comment by felixnielsen** [comment]
@xclntdesign makes sense, should I make it so the second paramter is the tag? Just to broaden the options.
