### ISSUE TITLE
Bot Breaks the page once embded

### ISSUE THREAD

**Issue by dominatelj** [space10-community/conversational-form#280]
I am embedding the bot inside my web page, but it is appearing at the top of the page overlapping with other sections and containers. 

Please let me know how to fix it, the error was inside the css for the bot  i tried to remove the top it disappeared. i want it to inherit the size of the bootstrap div element. Please let me know if you can help with this. Thank you. 

```
.conversational-form {
 visibility:visible!important;
 font-family:'Helvetica Neue',sans-serif;
 font-size:12px;
 line-height:1.416666667;
 position:absolute;
 top:0;
 left:0;
 right:0;
 bottom:0;
 z-index:999;
 margin:auto;
 background:#fff;
 overflow:hidden;
 opacity:0;
 will-change:opacity
}
```

**Comment by jenssogaard** [comment]
@dominatelj I would suggest looking at the element you use for cfContext, meaning the parent element to the selector you refer to. 

How are you instantiating CF? Via Javascript or `cf-form` on the form element?

**Comment by jenssogaard** [comment]
@dominatelj these examples from Codepen could maybe be of use to you: https://codepen.io/space10/

**Comment by dominatelj** [comment]
Hi @jenssogaard , Thank you for your reply and for the link you provided. i am using cf-form on the form element instead of the JS. I will check the examples and let you know if the error still persist. Thanks again

**Comment by jenssogaard** [comment]
@dominatelj cool. If you change to the javascript instantiation it will likely be a bit easier for you.
