### ISSUE TITLE
Input type tel not working

### ISSUE THREAD

**Issue by jacobclyne** [space10-community/conversational-form#281]
Hello.

So I was trying to add input with type 'tel', and it's not working. The input type is keep switching to 'input'. Tested on last two versions.

**Comment by jenssogaard** [comment]
Hi @jacobclyne. We do not at the moment support type tel. However, I definitely see the use for it and will put it on the roadmap.

**Comment by jacobclyne** [comment]
Thank you @jenssogaard can we expect that for the next release?

**Comment by jenssogaard** [comment]
@jacobclyne yes, I think it should be a pretty straight forward implementation. And thank you for bringing it to my attention.

**Comment by jenssogaard** [comment]
@jacobclyne this has been implemented now. Feel free to give it a try 😄
