### ISSUE TITLE
re captcha 

### ISSUE THREAD

**Issue by aimer2695** [space10-community/conversational-form#282]
Hi.. there's a way to show the re captcha in the conversational form?..

**Comment by jenssogaard** [comment]
As mentioned in one of the other two threads you wrote in. Please explain how you see reCaptcha being used and I will be happy to help you cook up a solution.

**Comment by aimer2695** [comment]
I used Gravity Form for the  Conversational Form, I used re captcha field from Gravity Form and the problem is I can't see the re captcha Field in my preview but the the some fields works on me.

**Comment by jenssogaard** [comment]
@aimer2695 I am not sure how you can make it work with Gravity Form - you might need to get your hands dirty and do some javascript to accomplish this.

**Comment by aimer2695** [comment]
@jenssogaard But This is possible in Gravity Form.? There's a steps how can I make it?

**Comment by jenssogaard** [comment]
@aimer2695 can you post a link to your site so I ca see how it works and then guide you from there? I'll be happy to help.

**Comment by aimer2695** [comment]
@jenssogaard Here's the Link: http://peupeup.eu/test/test-form/

I already set up only the re captcha Field. and there's no display. Thanks

**Comment by aimer2695** [comment]
@jenssogaard This is possible in Gravity Form? I hope this is possible I will apply it to my site after testing it in my testing site.. Thanks a lot..

**Comment by aimer2695** [comment]
Here's the Link: http://peupeup.eu/test/test-form/
I hope this is possible, I will apply it to my site after testing in my testing site. Thanks a lot.

**Comment by aimer2695** [comment]
@jenssogaard Here's the Link: http://peupeup.eu/test/test-form/
I hope this is possible, I will apply it to my site after testing in my testing site. Thanks a lot.

**Comment by aimer2695** [comment]
@jenssogaard This is possible in Gravity Form.? I can't still find any solution on this.  I'll need help here.
