### ISSUE TITLE
Event on valid input radio not working

### ISSUE THREAD

**Issue by alexsonnay** [space10-community/conversational-form#283]
Hello,

I'd like to use a progress bar with the form. I'd like that when a user selects an option between two radio inputs, the data-value of the svg progress bar increases. 

However, it doesn't seem to return any information when using `.checked` in JS once a I select an option from two input radios.

I checked issue #152 but I didn't see any fix about the id attributes on the current releases.

Any idea ?

**Comment by stanfaire** [comment]
I have the same issue.

**Comment by alexsonnay** [comment]
🥺

**Comment by jenssogaard** [comment]
@alexsonnay how about using flowstep callback and look at the forms step and maxStep values?
https://codepen.io/jens-s-gaard/pen/QojXvb?editors=0011
Outputs progress in console.

**Comment by alexsonnay** [comment]
Thanks I'll try that !

**Comment by alexsonnay** [comment]
It works, yay ! But only if you never edit previous answers. If you do, it resets everything and all the steps are out of order unfortunately.

**Comment by jenssogaard** [comment]
@alexsonnay do you have an example? Eg. a CodePen. Are you making sure to always call either error() or success() on the callback?
