### ISSUE TITLE
Support to use link in RobotChatResponse

### ISSUE THREAD

**Issue by anderson7play** [space10-community/conversational-form#284]
Guys, 

Congratulations for your work!

I need to use a link inside de text RobotChatResponse, there are someone method to do this?

Thanks :)

**Comment by jenssogaard** [comment]
@anderson7play sure thing, you just need to encode the HTML inside your attribute value. See [this example](https://codepen.io/jens-s-gaard/pen/Zwmowb) where I encoded my a-tag using [this tool](https://mothereff.in/html-entities) and added it to my first cf-questions value.

**Comment by anderson7play** [comment]
It Works!
