### ISSUE TITLE
Remove and replace all instances of eval()

### ISSUE THREAD

**Issue by matt3224** [space10-community/conversational-form#286]
Although this isn't a bug per-se it felt like this was still the right area.

https://github.com/space10-community/conversational-form/search?l=JavaScript&q=eval%28

There are a couple instances where the eval() function is used and this is usually discouraged for security reasons. Perhaps a different solution should be used?

**Comment by jenssogaard** [comment]
@matt3224 thank you for pointing this out. We are indeed using this for executing custom validation functions for input elements and we do note this in our [documentation](https://space10-community.github.io/conversational-form/docs/0.9.90/functionality/validation/). That said we should always strive to do better so I'll take a look and see if I should possibly change it to something like `window[functionNameString]` instead.

**Comment by matt3224** [comment]
That's great to hear! Keep me posted
