### ISSUE TITLE
problem with Appearance Behavior

### ISSUE THREAD

**Issue by null-saad** [space10-community/conversational-form#288]
**What I am trying to do ?**
I am trying to use the formless option and change the appearance at the same time.

**Expected Behavior**
if loadExternalStyleSheet : false then <div id="cf-context" class="dark-theme" role="cf-context" cf-context></div>should use the provided css 

**Actual Behavior**
Couple of issues here 
1. Even without setting loadExternalStyleSheet : false its picking the provided css (i.e. even when loadExternalStyleSheet : true )
2. if you initialize loadExternalStyleSheet :true no CSS is loaded hence nothing appears on the screen.

**Browser :**
Chrome Version 72.0.3626.119 

I am referring to the example provided here https://space10-community.github.io/conversational-form/docs/0.9.90/appearance/ but even here they have not set the **loadExternalStyleSheet : false** anywhere in the code.

**Comment by jenssogaard** [comment]
@null-saad have a look at [this example](https://codepen.io/jens-s-gaard/pen/GewzXr) where I do formless and pass the option to disable the default stylesheet. I hope this helps.
