### ISSUE TITLE
Links not clickable after form submitted

### ISSUE THREAD

**Issue by fladouceur** [space10-community/conversational-form#289]
When introducing links in messages like this for example:
`      <cf-robot-message cf-questions="<a href='http://www.google.com'>Google</a>" />
`
... they work fine until the form is submitted, but then they become unclickable.

**Comment by jenssogaard** [comment]
Hi @fladouceur. Once submitted we disable the form using the below CSS, you can override it yourself if needed:
`.conversational-form.done cf-chat-response {
    pointer-events: none;
}`

add:

`.conversational-form.done cf-chat-response {
    pointer-events: auto !important;
}`

**Comment by fladouceur** [comment]
Yes I found that afterwards, thanks for the reply though. I actually ended up using a custom class and some jQuery:
`          $(".cf-link").closest("cf-chat-response").css("pointer-events", "unset !important");
`
