### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by jhonnymoreira** [space10-community/conversational-form#29]
## Description

The image below shows the result when trying to execute some code through the input. The message was: `<img src="x" onerror="alert('XSS Vulnerability')">`. Since there isn't an image with name 'x', it causes to trigger the `onerror` function, which means the input value isn't getting sanitized and it is opening a security breach.

![XSS on Demo](https://cloud.githubusercontent.com/assets/2177742/20778952/8e8a39c4-b758-11e6-9c92-9322e79b40e6.png)

## How to solve?

Whenever dealing with user input, sanitize the input with a `safeString` method, otherwise, the vulnerability will persist.

## How to simulate the problem

1. Open the demo
1. Type a code that triggers some function related to error, such as `<img src="x" onerror="document.location = 'https://twitter.com'">`
1. The expected result is to get redirected to Twitter

**Comment by jhonnymoreira** [comment]
I would be glad to help on the issue and send a patch to solve this problem. While reviewing the code I saw a piece of code that I'm almost sure is causing the security breach:

https://github.com/space10-community/conversational-form/blob/master/src/scripts/cf/ui/UserInput.ts#L102-L104

```typescript
// /src/scripts/cf/ui/UserInputs.ts
// Lines: 102 to 104
public getInputValue():string{
  return this.inputElement.value;
}
```

**Comment by felixnielsen** [comment]
@jhonnymoreira nice! You are more than welcome to make a PR with a fix.

**Comment by jhonnymoreira** [comment]
Hey, @felixnielsen, today I wasnt able to work on the patch, tomorrow I'll have a free time to fix this, ok?

**Comment by felixnielsen** [comment]
Thanks @jhonnymoreira just ping me if any questions.
