### ISSUE TITLE
Serverside rendering of questions and logic?

### ISSUE THREAD

**Issue by voordev** [space10-community/conversational-form#290]
Amazing concept.
What I could not find if its possible to render questions and then" conversational logic / flow " serverside?

That is the webform/site would load all questions and logic from the server. Thus not the full form is in the webpage.

Is this possible and are there some examples on how one would implement this? Kind regards

**Comment by jenssogaard** [comment]
Hi @voordev. Excellent question. You could use flowstepcallback like in [this example](https://codepen.io/space10/pen/BJKbYq) to do an AJAX request and get the next question based on previous question. Does that make sense?

**Comment by jenssogaard** [comment]
@voordev Since I have not heard from you I assume you resolved your issue. I'll close this for now.
