### ISSUE TITLE
upload  files , documents, images

### ISSUE THREAD

**Issue by pankajbadatia** [space10-community/conversational-form#291]
Hi 

Thanks for your Convesational form.. its awesome work.. 

I am working in flask .  
I have managed to make simple form and save it to database. But the problem comes only when i try to upload a file , image , documents... 
I get a fake path at the backend..
I believe we are sending in json form from frontend.
 `{
'name': 'pankaj',
'dplace': 'mumbai',
'dtime': 'morning', 
'dage': '20',
'dduration': '10',
'fileupload': 'C:\\fakepath\\resume.pdf',
 'submit-form': ['Submit'] 
}`

----------------------------------------------------------------------------------
At server end I used
 `content = request.json
print("name testing = ",content)
`
`names = content['name']`

request.files gives none value
______________________________________________________

This gives me all the key value pair . But now the question arise
how will i use content['fileupload']
and save the file in any place in server

It is giving me fakepath..
Hoping anyone could help me out. atleast with an example or idea to continue.

I have read that fakepath cannot  and should not be accessed by anyone. because it deals with the browsers security.

But then how should i upload a resume or curriculum document from a candidate in server 

I used the following in input form

          <input type="file" name="fileupload" value="fileupload" id="fileupload" accept="image/*" cf-max-size="10000000000000000">
          <label for="fileupload"> Select a file to upload</label>

Plz help me
Following Attachement is just an example of flask and database connection.   i want  an uploading method 

[chats.tar.gz](https://github.com/space10-community/conversational-form/files/2982680/chats.tar.gz)

`

**Comment by jenssogaard** [comment]
Hi @pankajbadatia. I assume you do an AJAX request using [submit callback](https://space10-community.github.io/conversational-form/docs/0.9.90/functionality/submit-callback/), correct? If so you need to implement logic for loading the content of the file the user selected or do a traditional form submit.
