### ISSUE TITLE
double registration of conversational-form div with formless

### ISSUE THREAD

**Issue by MSBPeace** [space10-community/conversational-form#292]
For a code reference you can check the [official codepen](https://codepen.io/space10/pen/EoKMLg/) on how to use the formless feature.

When using the formless feature 2(!) instances of conversational-form are added to cf-context. (this can be seen in the codepen) 

MOST of the time this is not an issue since the actual active instance is usually registered last causing it to be rendered on top and everything appears fine.

I ran into an issue when implementing the form on some Wordpress sites where the two forms render in reverse order causing the form data not to be visible. 
The behavior appears timing dependent. (rendering the same form in an otherwise blank page works just fine)

```
<form id="form" cf-form>
                <!-- The form is freakin' empty -->
</form>
<div id="cf-context" class="custom-theme" role="cf-context" cf-context></div>

<script src=".../conversational-form/0.98.3/conversational-form.min.js"></script>
<script src="../customscript.js"></script>
```

Where the contents of customscript.js are:

```
window.onload = function () {
        var json = {
            "options": {
                "preventAutoAppend": true,
                "preventAutoFocus": false
            },
            "tags": []
        };
        // add callback hooks..
        json.options.submitCallback = onFormlessSubmitted.bind(window);
        json.options.flowStepCallback = onStepCallback.bind(window);
        
        // start convo w. json
        conversationalForm = window.cf.ConversationalForm.startTheConversation(json);
        var existingContext = document.getElementById("cf-context");
        existingContext.appendChild(conversationalForm.el);
}
```

**Comment by jenssogaard** [comment]
Hi @MSBPeace. The issue in that example is likely that the attribute `cf-context` is added to the div which would auto instantiate. Could you try removing it and see if that helps you?

**Comment by MSBPeace** [comment]
@jenssogaard Thanks, I tried it and indeed the form now becomes visible but this is only due to the fact that the inner form is rendered in some other random location:

```
<form id="form" cf-form>
                <!-- The form is freakin' empty -->
</form>
<div id="cf-context" class="custom-theme" role="cf-context"></div>

<script src=".../conversational-form/0.98.3/conversational-form.min.js"></script>
<script src="../customscript.js"></script>
```

This can also be tested and seen inside the earlier linked codepen.

**Comment by jenssogaard** [comment]
@MSBPeace I notice in the above that you use `role="cf-context"` and not just the attribute `cf-context` - the latter is the correct one, and should solve your issue.
