### ISSUE TITLE
cf-robot-message shows textarea to user

### ISSUE THREAD

**Issue by stormsson** [space10-community/conversational-form#295]
Adding `<cf-robot-message>`  to the html form has some odd behaviour when `hideUserInputOnNoneTextInput` is true:

i forked the pen linked in the documentation here: https://space10-community.github.io/conversational-form/docs/0.9.90/functionality/cf-robot-message

adding only `hideUserInputOnNoneTextInput: true` to the original configuration
modified pen:  https://codepen.io/anon/pen/VNPKXN

**Behavior**
When the  robot-messages are shown, there is the input textarea available to the user.

**Expected behavior**
When the  robot-messages are shown, no user input is available, because it is not an input request, same behavior as starting the conversation without `hideUserInputOnNoneTextInput`

debugging a bit for informations i found that 
1) the textarea is correctly hidden by adding the `hide-input` class by the check at:
https://github.com/space10-community/conversational-form/blob/f15bd28325c186e1a089552ee055a7f8bafc4a20/src/scripts/cf/ui/inputs/UserTextInput.ts#L360 

2) after a few lines it is re-enabled and shown to the user by the condition at
https://github.com/space10-community/conversational-form/blob/f15bd28325c186e1a089552ee055a7f8bafc4a20/src/scripts/cf/ui/inputs/UserTextInput.ts#L373

**Comment by jenssogaard** [comment]
Hi @stormsson. Thank you for bringing this to my attention. Let me take a look.

**Comment by jenssogaard** [comment]
@stormsson I'll sort out this issue in the upcoming v1.0.0 release.

**Comment by jenssogaard** [comment]
@stormsson this is already fixed in the upcoming v1.0.0 release.
