### ISSUE TITLE
How can I change the thinking bots style or class before robot and user response?

### ISSUE THREAD

**Issue by RJCAM** [space10-community/conversational-form#296]

**Comment by jenssogaard** [comment]
@RJCAM changing the class would be a lot of work for you. Why not just override the existing style with CSS?

**Comment by RJCAM** [comment]
Thanks for the reply. Overriding the style seems good too. What I want exactly is to change the bots style to this example (eg: 7):
https://tobiasahlin.com/spinkit/?fbclid=IwAR1F-6qw9I60nridgDayztD7B4-a5FxNOJnLlJlnxoiW6kRVPdml7TngBzg

So if I change or override the style it doesn't matter, I just need it to work. Sorry for my english.

**Comment by jenssogaard** [comment]
@jenssogaard Did you manage to resolve your issue. I assume you know how to use your browsers webinspector to find the class names you need to override?

**Comment by RJCAM** [comment]
Yes. Thanks for the help. I resolve my issue overriding the css styles.
Sorry if I didn't tell you.
You can consider the problem resolved and the issue solved. Thanks

Em qui, 30 de mai de 2019 às 13:12, Jens Soegaard <notifications@github.com>
escreveu:
