### ISSUE TITLE
Next JS (SSR) React support

### ISSUE THREAD

**Issue by YElyousfi** [space10-community/conversational-form#297]
How can this be made to not rely on window being defined? Trying to integrate this with Next.JS / server-side-rendering but this means that on the server window is not defined.

**Comment by jenssogaard** [comment]
hi @YElyousfi. That is a good question. Could you skip SSR for the CF integration and integrate when `typeof window !== undefined` ?

**Comment by jenssogaard** [comment]
@YElyousfi I haven't heard from you so I will assume that my answer solved your issue. Feel free to open a new issue if needed.

**Comment by jonrrivera** [comment]
how can we go about doing this?

**Comment by pfortes** [comment]
Use dynamic imports or check if `typeof window !== undefined`

**Comment by jonrrivera** [comment]
I imported the module using 

```
import dynamic from 'next/dynamic';
const ConversationalForm = dynamic(import('conversational-form'), { ssr: false });
```

now I'm getting this when copying the get started [code](https://stackblitz.com/edit/react-conversational-form-example?file=myForm.js):

<img width="1001" alt="Screen Shot 2020-11-10 at 11 57 12 AM" src="https://user-images.githubusercontent.com/18686388/98726860-e9628780-234b-11eb-8344-e1439cb8dac2.png">

**Comment by jonrrivera** [comment]
dynamically importing like this made ConversationalForm = undefined

`
const ConversationalForm = dynamic(import('conversational-form'), { ssr: false });
`

**Comment by pfortes** [comment]
@jonrrivera maybe try adding conversational form inside a component and then importing that component dynamically .

i use suspense

```
const isSSR = typeof window === 'undefined';

{!isSSR && (
    <React.Suspense fallback={<div />}>
         <ContactChat />
    </React.Suspense>
 )}
```

in the ContactChat component i import conversationalform normaly:
`import { ConversationalForm } from 'conversational-form';`

**Comment by jonrrivera** [comment]
you legend, this actually worked!

**Comment by pfortes** [comment]
@jonrrivera Glad to hear that!

**Comment by jonrrivera** [comment]
another question... how would I add an attribute to the <form /> that if I'm using the React implementation that uses Formless.

it needs to look something like this 

```
        <form
          onSubmit={this.submitForm}
          action="https://link.com"
          method="POST"
        >
```

Would we do this using the [tags optionhttps://space10-community.github.io/conversational-form/docs/1.0.0/options/url) ?
