### ISSUE TITLE
How to add image for questions

### ISSUE THREAD

**Issue by thavamm** [space10-community/conversational-form#298]
We have requirement to add images along with questions. Please guide us.

**Comment by jenssogaard** [comment]
Hi @thavamm. You can use [image answers](https://space10-community.github.io/conversational-form/docs/0.9.90/functionality/image-answers/), or you can just add img tag in your `cf-questions`. Just don't forget to escape your HTML if you add HTML in the questions. You can find other issues . where I show how to add links in `cf-questions`.

**Comment by thavamm** [comment]
Thank you @jenssogaard . It is working after I add img tag in cf-questions.
