### ISSUE TITLE
how to add event listner to tag in angular 6

### ISSUE THREAD

**Issue by thavaamm** [space10-community/conversational-form#299]
Hi,

I added event listener to my tag (click)="onMyTest()" in my angular form, but event not firing.

<input type="radio" (click)="onMyTest()">

Please guide me.

version of Angular: 6

**Comment by jenssogaard** [comment]
Hi @thavaamm. We do not transfer events attached to your form to the CF instance. You could check to see if `cf.OptionButtonEvents.CLICK` does the trick. See event documentation [here](https://space10-community.github.io/conversational-form/docs/0.9.90/events/).

**Comment by thavaamm** [comment]
Thank you @jenssogaard
