### ISSUE TITLE
Conversational Form error, the formEl needs to be defined

### ISSUE THREAD

**Issue by aireeria** [space10-community/conversational-form#30]
Hi,

First of all congratulations!!
Is a very good idea.

But, I'm trying to test it and I get this error:
Uncaught Error: Conversational Form error, the formEl needs to be defined.

I instantiate converstaional form this way (but I had test it with jQuery too):

```
if(!window.ConversationalForm){
      window.ConversationalForm = new cf.ConversationalForm({
        formEl: document.getElementById("contact-form-1234"),
        context: document.getElementById("wpcf7-f455-p450-o1")
    	});
    }
```

Any idea?

**Comment by felixnielsen** [comment]
hi @aireeria thanks :)
When creating the instance you need to make sure that the formEl isnt null/undefined.
So from your code it would seem that
```javascript
document.getElementById("contact-form-1234")
```
is null.

One would normal include the Conversational Form script and custom code below the rest of your code-base.

Can you confirm?

**Comment by aireeria** [comment]
hi @felixnielsen 
thanks for your work!

It's loaded. 
document.getElementById("contact-form-1234") in console throws the form element but it keeps throwing 
the Uncaught Error: Conversational Form error, the formEl needs to be defined.

**Comment by aireeria** [comment]
I'm dumb!
Sorry!

You can delete all the thread!
My big stupid mistake.

It works like a charm!!!
