### ISSUE TITLE
A Couple of questions - textbox text formating, creating a loading effect

### ISSUE THREAD

**Issue by amandaIaria** [space10-community/conversational-form#300]
Hello there,

Just a couple of questions. This form uses the formless version with about 40 or so questions. This includes any questions that are dynamically inserted via addTags(). With the last question if you want me to take it out of this post and put it in a post label bug I will. I just thought that one post might be a good idea.

**First question**
What do you think is the best way to add formatting to the textbox? For instance adding a typing effect for phone numbers so the user won't have to add dashes or parentheses. We only want this for one question.  Should it be via flowback? or events?

**Second question**
I saw a couple of posts on here that if you want to increase the robot "thinking" to make it look like it's loading you need to increase the animation in CSS. However I can't seem to figure out what specifically should be targeted in CSS. I'm using the flowback (maybe it should be events) since it'll only happen after the last important question, and I'm able to target the robot response but not when it's thinking.

**Third question**
I can't seem to get the dispatacher/custom events to work with the formless. I tried something like what you can do to set up the flowback, but it doesn't work. Here's an example of what I tried. I added the flow back so you can see what I was thinking:

javascript
```javascript
data.options.submitCallback = onFormlessSubmitted.bind(window);
data.options.flowStepCallback = onFlowBack.bind(window);

data.options.eventDispatcher = dispatcher.bind(window);

conversationalForm = window.cf.ConversationalForm.startTheConversation(data);
document.getElementById("prop-quote-buy-form").appendChild(conversationalForm.el);
dispatcher.addEventListener(cf.FlowEvents.FLOW_UPDATE, function(event){}, false);
```

formless json
```json
"eventDispatcher":"window.dispatcher",

"submitCallback": "window.onFormlessSubmited",
"flowStepCallback":  "window.onFlowBack",
```
This was just an assumption since it's not stated on the events page on how you can do it for the formless version.

Thanks.

**Comment by jenssogaard** [comment]
@amandaIaria 

1. Change input type - yes, use flowStepCallback. You could also hook an onKeyPress listener to the input field and check what question is being answered and the manipulate the input based on keyboard input. Does that make sense?

2. Have you checked the `userInterfaceOptions` option in the [docs](https://space10-community.github.io/conversational-form/docs/0.9.90/options/)? 

3. Where do you create an instance of `EventDispatcher()`? I could not find that in the code above.

In general, I can help you better if you can provide a code example. Eg. using [Codepen](https://codepen.io/space10/pen/mqXMQW) or [StackBlitz](https://stackblitz.com/edit/react-conversational-form-example)

**Comment by jenssogaard** [comment]
And @amandaIaria, I am sorry for the late reply.

**Comment by amandaIaria** [comment]
1. I think so. I'll have to dig into it and see if that will do it.

2. Yes, but that's for a general. I was looking to create a fake loading after a certain amount of questions were answered. There was a question that had mentioned something of the same.

3. `data.options.eventDispatcher = dispatcher.bind(window);` As I said I was doing something like what was documented for flowStepCallback/submitCallback

Here is the example I have on the bug one:  https://codepen.io/amandaIaria/pen/arwwqJ

**Comment by jenssogaard** [comment]
@amandaIaria 
2. We do not currently have an option that would allow that. But what you could do is use the event dispatcher and control the flow using `flowManager.stop()` and `flowManager.nextStep()`
I have created a crude example for you here: [CodePen](https://codepen.io/jens-s-gaard/pen/wbNOBa?editors=1010)

3. I made a few changes. See lines 237-240 and 244. At least you now have an eventDispatcher callback: https://codepen.io/jens-s-gaard/pen/QRYPvB?editors=0010

I hope this helps.

**Comment by amandaIaria** [comment]
Thanks for that. I'll check it out and see if that helps.
