### ISSUE TITLE
Editting Bug

### ISSUE THREAD

**Issue by amandaIaria** [space10-community/conversational-form#301]
Please check the list below to make sure we can provide you with the best possible support :star: 

- I have provided a code example. 
https://codepen.io/amandaIaria/pen/arwwqJ

- If I encountered an issue I have provided:
  - a description of the actual and expected behavior
see below
  - what version of Conversational Forms I am using
latest/cdn
  - what browser and version I am using
Chrome
  - the output of the browser console
  See below

At first, we thought it might be an edge case, but after testing with a few test users found that they were seeing it.

If you are, let's say, a few questions in and need to edit the first question. It lets you edit it, but it doesn't bring you back to the correct question you left off of. This isn't even with questions that would be inserted dynamically. 

Then sometimes after editing the question and going to the next question one, and answering that question, it would go to the to the previous one of that one. Then shoot out an error: 

```
conversational-form.min.js:4 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
```

I have a quick time video that shows what is going on. Along with the full error in the console
https://youtu.be/5Mb-6ZZf0vE

**Comment by amandaIaria** [comment]
I may have found the culprit, but I'm not sure how to go about with it. This particular bug seems to go away when I not doing any validation in the flowback method.

When I comment out my switch statement that looks at the tags, for example this is the switch statement.

```
switch(dto.tag.id){
 case "specific_id":
  if(dto.tag.value[0] === "Yes") {
       methodToStopForm();
   }
 break;
}
```
It won't do that weird behavior as shown in the video. It'll remove the other answers and start as if you started at that answer. In this example, the answer ends the form, removes the textbox, and doesn't allow you to edit your answers.

Another point, could this flowback switch statement not be working with the formless conditions? For instance in the JSON `cf-conditional-specific_id`?

**Comment by amandaIaria** [comment]
Another thing I found is that this behavior only happens when I'm looking for a specific tag. AKA

```
if(dto.tag.id == "specific_id"){
  console.log(dto.tag.id);
}
```
Even doing something as simple as that breaks it.

Which is how your documentation is saying it should be done in https://space10-community.github.io/conversational-form/docs/0.9.90/functionality/validation/

However, I *might* (I need to do some more testing) found a solution. Instead of using `dto.tag.id`, it seems that `dto.tag.name` does not do the above behavior.

**Comment by jenssogaard** [comment]
Hi @amandaIaria. I'll make sure to take a look later today and try to help you out.

**Comment by amandaIaria** [comment]
For the moment I've had to switch to the regular form version instead of the formless. I still haven't been able to pinpoint an exact cause other than guessing what it might be.

**Comment by jenssogaard** [comment]
@amandaIaria with your custom validation. Have you made sure that you always call either `success()` or `error()`?

Any chance you can post a Codepen that would replicate the error? Then I can take a look and work with it on my end.

**Comment by amandaIaria** [comment]
Outside of my `switch`, I have a `return success()` since there's no need to have it in. Otherwise, there is always a `return error()`. I'll have to recreate it with more questions.

**Comment by jenssogaard** [comment]
@amandaIaria I'll close this one for now. Feel free to post again when you have more and we can re-open.
