### ISSUE TITLE
Screen flickering 

### ISSUE THREAD

**Issue by Ilja-developer** [space10-community/conversational-form#302]
On the submit of the form, the HTML form with no styling appears for a sec flickering before submitting. So I enter all values, and on ENTER on the last question the chat disappears and I see my HTML form for a sec, then it redirects as I setup in the FORM action.

Anything I configured wrong?

![flick2](https://user-images.githubusercontent.com/29120151/58348125-0a859e80-7e60-11e9-9b5e-952b45605215.png)
![flick](https://user-images.githubusercontent.com/29120151/58348032-bb3f6e00-7e5f-11e9-9802-0e7690d29b2f.png)

**Comment by jenssogaard** [comment]
Hi @Ilja-developer. If the path you are submitting to would be faster your would hardly notice it? :) But I understand. Ideally, the form would not change appearance on submit. I'll put it on the list of tasks but I can not assign it a high priority as of now.

I would suggest that you instead use the custom submit callback and do an AJAX request. That would in most cases always make for better user experience as you could then also show potential errors in the form. See [this example](https://codepen.io/space10/pen/mqXMQW).

**Comment by Ilja-developer** [comment]
Haha, very true.

I think I fixed it a little. I've hidden the form with opacity and height (display gave errors in chrome). Now it's cool.

Thanks so much, amazing stuff.

**Comment by jenssogaard** [comment]
You are more than welcome, @Ilja-developer. Happy you resolved it.
