### ISSUE TITLE
addtags inside a subscribe not working

### ISSUE THREAD

**Issue by Doss12** [space10-community/conversational-form#306]
Hello, 
 I have an issue with addTags inside a subscribe , it displays the question after the addRobotResponse randomly and most of the time it's not displaying it , here is my code  : 

    function onFlowBack (dto, success, error) {
            switch (dto.tag.id) {
                  case "account_number":
                       this.account_num = dto.tag.value[0];
                       this.accountDetail.getAccountDetails(this.account_num).subscribe(data => {
                               this.cf.addRobotChatResponse(GetAccountDetails(data));
                               this.cf.addTags(AddTransactionDetails(), true);
                       });  }

many thanks

**Comment by jenssogaard** [comment]
@Doss12 do you call success(); at the end of your callback?

**Comment by Doss12** [comment]
yes , i think is an issue of async , is addTags function asynchronous ?

**Comment by Doss12** [comment]
thanks for your replay , 
I just call a return success at the end of the function but not in the case , so the problem is resolved thanks a lot :D

**Comment by jenssogaard** [comment]
@Doss12 awesome, happy to help.
