### ISSUE TITLE
<input> tags not displayed on bootstrap modals

### ISSUE THREAD

**Issue by MaximeLagresle** [space10-community/conversational-form#308]
Hello,

I want my user to click on a cta that will trigger a bootstrap modal with a conversational form embedded inside. 

I've been doing it and it seems to work except that only the `fieldset` (inside my `form` tag) with a `select` tags are displayed but not the `input` ones. 

I couldn't figure out why? Any idea on what I'm doing wrong? 

Here is a codepen showing my issue:
https://codepen.io/maximelagresle/pen/PrENYz

Thanks for your help!

**Comment by jenssogaard** [comment]
Hi @MaximeLagresle. Just move your form out of the modal body. When the form is `display:none;` CF has a hard time parsing the form fields.

**Comment by MaximeLagresle** [comment]
Hi Jens,

Thanks for your reply!

Just to make sure I got your point, you're saying that I shouldn't embed a CF in a modal at all, right? 
What would you recommend then if I want my CF to pop up once the user clicks on a CTA?

Thanks for your help!

**Comment by jenssogaard** [comment]
@MaximeLagresle you just need to move the `<form>...</form>` part out of the modal - like this: https://codepen.io/jens-s-gaard/pen/vqpdxN?editors=1100

See how the form is moved to line 9 - not nested in the modal anymore. Remember, the <form> tag is basicly just your dataset that you are using for your Conversational Form.

**Comment by MaximeLagresle** [comment]
Awesome @jenssogaard that works! Thanks a lot for your precious help :)

**Comment by jenssogaard** [comment]
You are more than welcome, @MaximeLagresle.
