### ISSUE TITLE
image cf-robot-message

### ISSUE THREAD

**Issue by mploux** [space10-community/conversational-form#309]
Hi !
First of all thanks a lot for your work, it is amazing !
I am having issues with rendering a full image inside the cf-robot-message. I managed to render one by simply placing an <img /> inside the cf-questions but I have a huge padding around and it's not at all what I want. So I was wondering if there was a way to simply render a cf-robot-message as an image, without text.

Thanks again !

**Comment by jenssogaard** [comment]
Hi @mploux. Thank you for your kind words. We do not support any other way presenting an image inside of `cf-questions` than using HTML. But you could easily just apply a bit of CSS to take care of the styling, right?

**Comment by mploux** [comment]
Hi @jenssogaard, thanks for the response ! I did took care of it with css but I don't feel like it's a nice way to do it. If there was a proper way I guess it would make me feel better but as of now it's maybe not important.
Anyway, thanks again and good luck on the project !
