### ISSUE TITLE
Submit with AJAX

### ISSUE THREAD

**Issue by xclntdesign** [space10-community/conversational-form#31]
First off, amazing job on this.

Second, perhaps submitting with AJAX by default should be considered. After the final field is entered, the form is submitted with AJAX, and a message is returned in the chat window.

I think we, as developers, understand what's going on, but the average user filling out a contact form might be a little confused by being redirected to a thank you page. Sort of "I was just talking to someone, what happened?" The last question you have at the end of your demo is a great idea for a submit button replacement, but if they don't answer it and just leave, then the form never gets submitted.

I have tried various methods, like using submitCallback and removing the action from the form, to attempt this, but so far I have been unsuccessful as the form submit redirects, either to the action form or the current page.

**Comment by felixnielsen** [comment]
thanks @xclntdesign ! There was a bug related to submitCallback ... Which you would use in this case.
Please see [this closed issue.](https://github.com/space10-community/conversational-form/issues/32) where there is also a [JSbin link.](https://jsbin.com/kipejexaju/edit?html,js,output)

Regarding a final (and welcome) message, then this is something we will roll out with a official release very soon.
