### ISSUE TITLE
Blank modal after submission

### ISSUE THREAD

**Issue by MaximeLagresle** [space10-community/conversational-form#311]
Hi @jenssogaard,

I've integrated cf into a bootstrap modal. The whole flow works properly however from time to time (on average 2 out of 10) my forms aren't submitted and I get this blank modal.

I'm using a 3rd party email service and thought that could come from it. But I tried another one (FormSubmit) and still get that issue...

Unfortunately, I haven't been able to see a recurring pattern that leads to that bug and I don't get any error in my console.

Any idea on what could be the issue?

<img width="910" alt="Screenshot 2019-07-16 at 18 10 45" src="https://user-images.githubusercontent.com/16308588/61311893-94663e00-a7f7-11e9-9ecf-a9af050ae47a.png">

**Comment by jenssogaard** [comment]
Hi @MaximeLagresle. Can you share some of your code? How does the submit logic look like? AJAX or traditional form request?

**Comment by MaximeLagresle** [comment]
My submit logic is a traditional form request. I use formsubmit.co and redirect my users to my own thank-you page (but I had the same issue before when I redirected my users to formsubmit own thank you page.

Here's part of my code:

HTML Code
`
<form id="form" action="https://formsubmit.co/admin@random.co" method="POST">

    <fieldset>
        <label for="name">What's your name?</label>
        <input required cf-questions="Hi there! What's your name? 😊" type="text" class="form-control" name="name" id="name" />
      </fieldset>

      <fieldset>
        <label for="position">Article Brief</label>
        <input required cf-questions="Last question. What is your position?" type="text" class="form-control" name="position" id="position">
      </fieldset>
      <input type="hidden" name="_next" value="https://helloworld.co/thank-you.html">
  </form>

<div class="modal fade bd-form-modal-lg" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">

        <div>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"><img src="img/cancel.svg" alt="close"></span>
          </button>
        </div>

        <div class="modal-body">
          <div class="embed-responsive embed-responsive-4by3 embed-mobile">
            <div class="embed-responsive embed-responsive-item" id="cf-context" role="cf-context" cf-context>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
`

JS Code
`window.onload = function() {
  var conversationalForm = window.cf.ConversationalForm.startTheConversation({
    formEl: document.getElementById("form"),
    context: document.getElementById("cf-context"),
    userImage: "text:🧑",
    hideUserInputOnNoneTextInput: true
  });
};`

**Comment by MaximeLagresle** [comment]
Hey @jenssogaard,

Can that issue be related to that error? 

![66912343_617876115384847_179360862232903680_n](https://user-images.githubusercontent.com/16308588/61496704-62063d80-a9bd-11e9-90de-dc31c96b3f87.png)

**Comment by MaximeLagresle** [comment]
@jenssogaard do you think that issue can be related to the fact that my `<form>...</form>` part is outside of the modal code? 

cf. https://github.com/space10-community/conversational-form/issues/308

**Comment by jenssogaard** [comment]
@MaximeLagresle if still guessing since I can't try it out myself. It looks like you are redirected back, so it must be on your end. What is supposed to be in the white frame that the user comes back to?
