### ISSUE TITLE
Robot Message Callbacks

### ISSUE THREAD

**Issue by WiFuchs** [space10-community/conversational-form#313]
**Is your feature request related to a problem? Please describe.**
I often add more information to the robot responses (eg an image carousel) based on the previous user response. However, right now I have no way of knowing when the robot message has been added, so I do not know when I can append the image carousel to it (without using MutationObserver, that is).

**Describe the solution you'd like**
I would like to be able to add an optional callback parameter to addRobotChatResponse that would be called as soon as the cf-chat-response is added to the DOM, to populate it.

**Describe alternatives you've considered**
I am currently doing this with the MutationObserver API, but it is a bit hacky and does not feel maintainable. 

**Additional context**
I would be happy to try and add this feature, I think that I know how, I just want to make sure it is a valid feature and not something with an easy workaround first! Please let me know asap if I should start working on it or if there is a simple solution that exists already.

**Comment by jenssogaard** [comment]
Hi @WiFuchs. You can use the eventDispatcher and the event `FlowEvents.FLOW_UPDATE` that will tell you when eg. a robotMessage is added. Look for `event.detail.tag` which contains all the details about the tag added. 

One detail: if you load CF using imports you will run into an issue because `EventDispatcher` is not exported. This is fixed in the upcoming v1.0.0 which will be released this Thursday.

**Comment by WiFuchs** [comment]
Hi @jenssogaard. Thanks for your quick reply!

I ended up using the `FlowEvents.FLOW_UPDATE` to call a callback passed as a custom attribute to the `cf-robot-message`. Is there any way to pause the flow of the conversational form? I am displaying a long list of images, and I would like to delay the next question until the user scrolls through them. My current idea is to change it from a `cf-robot-message` to a text input, and then using JS to trigger submit once the user has scrolled through the list.

Is there a more native way to do this? Something like `ConversationalForm.pause()`...

**Comment by jenssogaard** [comment]
@WiFuchs glad it worked out. We do not have a pause functionality. How about use the same `FlowEvents.FLOW_UPDATE` event and disable the input field when a certain question is rendered and enable once the user scrolls to the end of your options?
