### ISSUE TITLE
Conversational-form@1.0.0 CDN Failing

### ISSUE THREAD

**Issue by lysterjason** [space10-community/conversational-form#314]
Hello,

I am attempting to upgrade from v0.9.90 to v1.0.0 based on the newest documentation page (https://space10-community.github.io/conversational-form/docs/1.0.0/getting-started) and when using the CDN with 

<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/space10-community/conversational-form@1.0.0/dist/conversational-form.min.js" crossorigin></script>

the console in chrome (Version 75.0.3770.142) outputs the following error

GET https://cdn.jsdelivr.net/gh/space10-community/conversational-form@1.0.0/dist/conversational-form.min.js 404

I am expecting my conversational form to be instantiated but instead, I get this error and no conversational form is instantiated. Nothing in my markup was changed in the migration except for changing the CDN script to upgrade from v0.9.90 to v1.0.0.

**Comment by jenssogaard** [comment]
Hi @lysterjason. We released 1.0.0 yesterday but had to pull it back due to internal issues around communication. It will be available on Thursday. Apologies for the inconvenience. The docs link has been updated to avoid confusion.
