### ISSUE TITLE
robotImage Not Working in Version 1.0.1

### ISSUE THREAD

**Issue by lysterjason** [space10-community/conversational-form#315]
I have upgraded to the new conversational form (Version 1.0.1) which I am super excited about! One issue is that the robotImage option does not appear to be working. I have set the image to a hosted image that I have used in Version 0.9.90 which worked very well, but now in Version 1.0.1 it appears not to work because the dark theme background-image is overriding it. I am using Chrome, Version 76.0.3809.87. I am also provided a working CodePen example which can be found here:

https://codepen.io/anon/pen/ymoMNW

Here is the same code, just in Version 0.9.90 instead, and as you can see it is working with a different robot image.

https://codepen.io/anon/pen/dxzvGW

**Comment by jenssogaard** [comment]
Hi @lysterjason. Thank you for reporting this - you are correct. This is an issue only relating to the `dark` theme. As a workaround, I suggest you set them using CSS:
```
cf-chat-response.robot thumb {
    background-image: url('https://avatars0.githubusercontent.com/u/620738?s=88&v=4') !important;
}

cf-chat-response.user thumb {
    background-image: url('https://avatars1.githubusercontent.com/u/36202406?s=88&v=4') !important;
}

I'll put this bug on the todo list for a minor patch that can be released soon.

**Comment by lysterjason** [comment]
Awesome, thank you very much!

**Comment by jenssogaard** [comment]
A patch has been pushed to develop branch and will be released Thursday. Closing this issue for now.
