### ISSUE TITLE
Input Mask within Conversational Form?

### ISSUE THREAD

**Issue by lysterjason** [space10-community/conversational-form#317]
Hi,

I am wondering if it is possible to put an input mask within specific questions in the conversational form. For example, if a question is "Please type 1 million?" instead of the user seeing 1000000, they would see a mask, so as they type they would see commas in between in proper currency format ($1,000,000). I know this is possible in regular HTML input boxes but I am having difficulty figuring out how to do it for specific questions in the conversational form.

Thanks in advance.

**Comment by jenssogaard** [comment]
Hi @lysterjason. We do not currently support input masks - could be something I would bake into CF. You could use the EventFlow and trigger/apply your own input masks when a specific question is rendered. Does that make sense?

**Comment by lysterjason** [comment]
I'll give it a try! Thanks so much

**Comment by lysterjason** [comment]
In case anyone stumbles across this problem [here](https://codepen.io/jasonly/pen/eqrebd) is a CodePen with an example of a currency mask in the Conversational Form using @jenssogaard Event suggestion. Implemented using [this](https://igorescobar.github.io/jQuery-Mask-Plugin/) jQuery plugin.

**Comment by lysterjason** [comment]
> In case anyone stumbles across this problem [here](https://codepen.io/jasonly/pen/eqrebd) is a CodePen with an example of a currency mask in the Conversational Form using @jenssogaard Event suggestion. Implemented using [this](https://igorescobar.github.io/jQuery-Mask-Plugin/) jQuery plugin.

Also a very hacky solution, you can easily assign an input mask to just a simple field

**Comment by jenssogaard** [comment]
@lysterjason thanks for sharing your solution. I greatly appreciate your updating the issue with your findings 🥇
