### ISSUE TITLE
Greeting Message using addRobotChatResponse

### ISSUE THREAD

**Issue by lysterjason** [space10-community/conversational-form#319]
Hi, I am wondering if there is a way to use addRobotChatResponse at the very beginning of the form for the purpose of a greeting message? I have an AJAX call before the beginning of the form and I would like to pipe some of the values from it into a greeting message but I am struggling to figure out how. Thanks in advance!

**Comment by lysterjason** [comment]
I am sure there is a better way to do it, but I did find a little hacky solution which you can view [here.](https://codepen.io/jasonly/pen/eYOzpbm) You can see how this can easily be adapted to use values from something like an AJAX call.

**Comment by jenssogaard** [comment]
@lysterjason you could [define your form as a JSON object](https://space10-community.github.io/conversational-form/docs/1.0.0/functionality/formless/) and wait with instantiating the form until your have your data from your backend.
