### ISSUE TITLE
submitCallback does not trigger

### ISSUE THREAD

**Issue by Richardxlin** [space10-community/conversational-form#32]
I may be missing something, but I can't get the callback function to work in the constructor.
Here is a jsbin: https://jsbin.com/kipejexaju/edit?html,js,output

**Comment by felixnielsen** [comment]
@Richardxlin thanks for discovering this. See related commit for fix. Your jsbin is also working for me know.

**Comment by Richardxlin** [comment]
@felixnielsen Works great. Thanks!
