### ISSUE TITLE
It is possible to get the user answer from another form/container

### ISSUE THREAD

**Issue by Gigiart** [space10-community/conversational-form#322]
To begin with, I want to thank you for the fabulous work here. I studied this plugin, but to use it I need the following functionality:

The user clicks on an option and then an overlay opens where the user can upload photos and certain fields. On the "Submit" button, the resulting data I want to be displayed back as the answer of the user.
Is it possible to do this? If Yes, how can I do it? Thanks!

**Comment by jenssogaard** [comment]
Hi @Gigiart. Thank you for the kind words - much appreciated. What you describe is absolutely possible. Your description is open for interpretation, but I would look into [Events](https://space10-community.github.io/conversational-form/docs/1.0.0/events/) and [FlowStepCallback](https://space10-community.github.io/conversational-form/docs/1.0.0/functionality/flowStepCallback/) which would allow you to interrupt the flow and have the user perform additional tasks.

On regards to displaying the resulting data you can using [custom submit callback](https://space10-community.github.io/conversational-form/docs/1.0.0/functionality/submit-callback/) and obtain the data and then present it however you like it.

I hope this can get you started.
