### ISSUE TITLE
Documentation link in landing page menu leads to an older version of docs 

### ISSUE THREAD

**Issue by sergeyfilimonov** [space10-community/conversational-form#324]
The documentation link in landing page menu leads to an older version of the docs https://space10-community.github.io/conversational-form/docs/0.9.90/getting-started/, it should be https://space10-community.github.io/conversational-form/docs/1.0.0/getting-started/

**Comment by jenssogaard** [comment]
Hi @sergeyfilimonov. Thank you for noticing and reporting. I updated the link now.
