### ISSUE TITLE
Google Analytics Integration Chat not Working

### ISSUE THREAD

**Issue by kittcarson** [space10-community/conversational-form#325]
https://codepen.io/space10/pen/YYqBWP

It does not display the name inputted

**Comment by lysterjason** [comment]
I could be wrong but I don't see any Google Analytics metadata in the CodePen example, so it has no idea what to do inside of the flowStepCallback? That is where it is getting stuck.

**Comment by lysterjason** [comment]
https://codepen.io/jasonly/pen/ExYNpqq

Here is the fix. I added the 2 script tags required for Google Analytics to work (Got this from docs/1.0.0/integrations/index.html). It was simply missing from the CodePen example you provided.

**Comment by jenssogaard** [comment]
@kittcarson the purpose of the example is not to show how you install GA on your site but rather how you can access CF data and call your own GA event tracking or a different 3rd party tracking service in your application :)
