### ISSUE TITLE
Response bubbles are displaying next to each other instead of under

### ISSUE THREAD

**Issue by buesing** [space10-community/conversational-form#329]
I keep running into this issue where text bubbles are display like this: http://files.wild.as/tptwwl
Using 1.0.1, happens in Chrome, FF and Safari on OSX. Adding these styles to the  wrapping `<text>` component fixed the issue for me: 
```
    display: flex;
    flex-flow: column;
    align-items: start;
```

**Comment by jenssogaard** [comment]
@buesing thank you for reporting. I'll take a look and a fix can be added in an upcoming patch.

**Comment by jenssogaard** [comment]
A patch has been pushed to develop branch and will be released Thursday.
