### ISSUE TITLE
Question: any chance this will work on native-mobile (cordova) ?

### ISSUE THREAD

**Issue by m-abisaad** [space10-community/conversational-form#33]
Hi,
any idea if this will work with cordova? anyone tried it? 
if no, is there any plan to do so?

Thanks.

**Comment by felixnielsen** [comment]
@m-abisaad I have not tried to have it compiled to another code-base, in theory it should work.
Please let me know if you start testing this.

**Comment by m-abisaad** [comment]
it worked, 
i had to download conversationaform.min.js and include it in the solution.

**Comment by felixnielsen** [comment]
@m-abisaad awesome! Please let me know if one can access the implementing at some point.
