### ISSUE TITLE
preventAutoFocus: 'true' does not work when hideUserInputOnNoneTextInput is also 'true'

### ISSUE THREAD

**Issue by egyptik** [space10-community/conversational-form#332]
I noticed the following issue:

When both of `preventAutoFocus` and `hideUserInputOnNoneTextInput` are set to `true`, cf will still autofocus on the first option if the input is a none text input. For now, I'm using the follow code as a workaround:

```
dispatcher.addEventListener(UserInputEvents.CONTROL_ELEMENTS_ADDED, function(event) {
     document.activeElement.blur();
}, false);
```

**Comment by jenssogaard** [comment]
@egyptik, thank you bringing this to my attention. I'll take a look and possibly include in a minor patch release.
