### ISSUE TITLE
Conditional is being ignored

### ISSUE THREAD

**Issue by buesing** [space10-community/conversational-form#335]
I set up a codepen here:
https://codepen.io/moriz/pen/ydooBp
Could you have a look and select "I don't have breakfast" in the first question? When giving this answer, CF seems to go directly to the next question, although it has a conditional so that this question should only be asked if the answer "Toast" is given to the first question. I replaced all name and value tags with generated IDs so I don't have troubles with duplicates in conditions.

But if you take a look the second question has the conditional
```
 "cf-conditional-A3oyaL8bgtEgQIJt": "1ritXcN9MTNVMkQP"
```
and altough the given answer has the value `RYUvcUBYM6M9nGLP`, it is still being asked.

**Comment by buesing** [comment]
I have reduced the test case a little and made all ids alphabetic and lowercase to rule out these errors, still the same issue: https://codepen.io/moriz/pen/oNvpLpx
When I remove everything after the first 2 sets of inputs, the second question doesn't show up anymore.. Any ideas?

**Comment by jenssogaard** [comment]
Hi @buesing. Try wrapping each of the groups in a `tag group`:
```
{
    // tag group
    "tag": "fieldset",
    "type": "Checkboxes",
    "cf-input-placeholder": "Tag group is injected",
    "cf-questions": "Choose an injected tag",
    "children":[
        {
            "tag": "input",
            "type": "checkbox",
            "name": "checkboxes-buttons-1",
            "cf-label": "checkbox-x1",
            "checked": "checked"
        },
        {
            "tag": "input",
            "type": "checkbox",
            "name": "checkboxes-buttons-1",
            "cf-label": "checkbox-x2"
        }
    ]
}
```

**Comment by buesing** [comment]
Hi, I worked around this issue now by generating unique ids for repeated questions.
