### ISSUE TITLE
Keyboard Issue on a device

### ISSUE THREAD

**Issue by neel2468** [space10-community/conversational-form#336]
When restarting the conversational form using button click , in the textbox after typing one letter keyboard disappears. This is the issue when opening on a real mobile device

**Comment by jenssogaard** [comment]
Hey @neel2468. How do you restart the form? what device are you referring to

**Comment by neel2468** [comment]
Actually I was restarting the form in a wrong way in my code. I changed the
way of restarting it.Intially I was just restarting the form in ngOnInit
method im my angular code and I changed my code put it on whole refresh of
the page and its working fine as expected.
Thanks for attention.I will close the issue.
I am building a cross platform mobile app using ionic and I needed a
chatbot.
I was testing it on my android phone.
I will close the issue.
Thanking you.

**Comment by jonrrivera** [comment]
Hi @jenssogaard 

Really enjoying implementing conversational form into my next js project. 

I am getting this issue on mobile every time I answer a question. Each time a question in answered the mobile keyboard hides and I have to tap on the input every time to toggle the keyboard back up and write an answer for each new question. 

Ideally, I would want the mobile keyboard to stay opened consistently as the form is filled. 

Any recommendations? thanks!

**Comment by pfortes** [comment]
Duplicate of #224 
Not sure if there is a solution yet, i haven't tested this.

**Comment by jonrrivera** [comment]
gotcha, I am happy to help you with it.
