### ISSUE TITLE
W3C Validation

### ISSUE THREAD

**Issue by hajar-alpha** [space10-community/conversational-form#338]
I found this project promising and can get more recognition, I just hope that the structure of code (tags and attributes etc) to follow the W3C standards and have more cross browser compatibility, I just integrated a small conversational form into a page and after passing it in W3C Online Validator, I got a lot of errors.

I searched in the documentation and here, but this wasn't mentioned anywhere.

**Comment by jenssogaard** [comment]
Hi @hajar-alpha. Thank you for your input. Maybe you could help improve CF? How about publishing your list of findings and then we can discuss how to fix them?
