### ISSUE TITLE
preventSubmitOnEnter doesn't work without rows property

### ISSUE THREAD

**Issue by MSBPeace** [space10-community/conversational-form#339]
Some of my users rely on Japanese text input and as such use the enter key to autocomplete Chinese characters in words, because of this I would like to disable the Enter key from triggering submit actions altogether.

I initially though the preventSubmitOnEnter option would do the trick as the documentation suggests:

```
 var json = {
            "options": {
                "preventAutoAppend": true,
                "preventAutoFocus": true,
                "preventSubmitOnEnter": true,
            },
            "tags": []
        };
```

Unfortunately hitting the enter key still triggers the submit action even after.
Upon reading some of the source code I noticed that whenever preventSubmitOnEnter is mentioned other checks are also ran:

```
 

// If submit is prevented by option 'preventSubmitOnEnter'
--
495 | if (this.cfReference.preventSubmitOnEnter === true && this.inputElement.hasAttribute('rows') && parseInt(this.inputElement.getAttribute('rows')) > 1) {

```

This suggests to me that the suggested option only works for TextArea type inputs and not regular fields. As such I would like to request the possibility to have an option disable the Enter behavior for all types of input like the documentation suggests.

**Comment by jenssogaard** [comment]
Hi @MSBPeace. Good feedback. I'll try and patch it.

**Comment by MSBPeace** [comment]
Hey @jenssogaard any update on this? If you feel like there are particular reasons for limiting the scope for preventSubmitOnEnter then I'd be happy to discuss.

If you think it would help for me to prepare a PR I'd be happy to do that too.

**Comment by jenssogaard** [comment]
Hi @MSBPeace. I was just about to do a patch for this issue but I can't recreate the issue you describe. I indeed can use enter without submitting a question. Can you create a Codepen (or similar) that shows your issue?

**Comment by MSBPeace** [comment]
this seems to have been fixed with the never version. Thank you for the support!
