### ISSUE TITLE
How to stop jumping page to the conversational-form after page loaded.

### ISSUE THREAD

**Issue by Artkoch** [space10-community/conversational-form#34]
HI!

After my page is loaded it scrolls down to footer to the conv-form. Is it the default behaviour of the conv-form?

I'm implementing conv-form in my React project vie componentDidMount with .setAttribute command.

**Comment by felixnielsen** [comment]
Hi @Artkoch it is scrolling down because it sets auto-focus on the Conversational Form's input field, browser native behaviours scrolls the active input field into view.
Either you want to instantiate the Conversational Form manually when user has the form in view. Or I could add an option to the constructor that disallows for auto-focus upon instantiation.

Let me know.

**Comment by Artkoch** [comment]
It would be great to have auto-focus option set to false by default. Often times forms on landing pages or not the main element. But how long would it take to create that option?

**Comment by felixnielsen** [comment]
@Artkoch did it the other way around, please see the commit which closed this issue. We will think about adding it pr. default. You are also very welcome to fork it and switch the implementation around.

**Comment by torresf** [comment]
Hi, I have the same problem using formless. In the DOM I don't have any <form> element as my form is instantiate by the line `document.getElementById("cf-context").appendChild(conversationalForm.el);` How and where should I set the attribute `cf-prevent-autofocus` ?

**Comment by felixnielsen** [comment]
@torresf i've added an optional attribute `preventAutoFocus` (boolean) to the constructor options. Check develop branch.

**Comment by m-luqman** [comment]
The problem still persists. With the conversation form initialized, if we try to type into any other text box, we get dragged into the conversational form.
