### ISSUE TITLE
save form data into google sheets

### ISSUE THREAD

**Issue by nitin365** [space10-community/conversational-form#340]
i am trying to save the form input into google sheet but having multiple issues.
- how to send the data into get request after submitCallback
- there is not way to run javascript function on button click event or option change event
-i am using the sample code from the post https://medium.com/@dmccoy/how-to-submit-an-html-form-to-google-sheets-without-google-forms-b833952cc175

but it does not suppor post request and json datatype

**Comment by jenssogaard** [comment]
@nitin365. Instead of posting directly to Google Sheets I would suggest using https://zapier.com

You can use the submit callback logic described and with an example [here](https://space10-community.github.io/conversational-form/docs/1.0.0/functionality/submit-callback/).
