### ISSUE TITLE
is that possible to get the value selected among radio button or check box in the response form .

### ISSUE THREAD

**Issue by RekhaMadhavan1211** [space10-community/conversational-form#344]
For example we are having a radio button for gender, the response is like gender:[0:"on"]. This is actually difficult to find which value is selected. It will be better if we could get the id of the selected value

**Comment by jenssogaard** [comment]
Hi @RekhaMadhavan1211. Have a look at [this CodePen](https://codepen.io/space10/pen/mqXMQW?editors=1111) and check the console on submit. Why can't you just add a non-numeric value for each option?
