### ISSUE TITLE
Use with Svelte/Sapper

### ISSUE THREAD

**Issue by TheGuyInApt42** [space10-community/conversational-form#346]
How would i use this with Svelte/Sapper? When i import it with npm install, I get an error
ReferenceError: window is not defined

**Comment by jenssogaard** [comment]
@TheGuyInApt42 - have you tried doing like this guy in #347 ?

**Comment by TheGuyInApt42** [comment]
Thanks, I think I got it. I used the example from the Sapper docs 
```javascript
import { onMount } from 'svelte';

	let MyComponent;

	onMount(async () => {
		const module = await import('my-non-ssr-component');
		MyComponent = module.default;
	});
```

@jenssogaard Thanks for the help

**Comment by jenssogaard** [comment]
@TheGuyInApt42 awesome. Happy to hear.

**Comment by TheGuyInApt42** [comment]
I got it to work but I also get the circular dependency warning #287

**Comment by TheGuyInApt42** [comment]
Question, is there an example of how to use Events? I want to hit an API on 'keyup' in input box, is that FlowEvents.USER_INPUT_UPDATE? I can't find an example of how to implement Events. Thanks for your help.

**Comment by jenssogaard** [comment]
@TheGuyInApt42 thank you for noting the circular dependency. The event. Have a look at the `cf.UserInputEvents.KEY_CHANGE` event described in the [docs](https://space10-community.github.io/conversational-form/docs/1.0.0/events/).

**Comment by TheGuyInApt42** [comment]
I have gotten the Events to work with an API but im having trouble displaying the results. I can see the API response in the console.log and I have gotten it work with showing one input with response data. However I need a checkbox and/or radio button and it will not work with those, ie using the response as a set of checkbox values. Im not sure if the problem has to do with Svelte data-binding. 
Example: 

```javascript
{if results}
    <select name="conditions" cf-questions="Test" multiple>
            {#each results as condition}
                <option value={condition.name} >{condition.name}</option>
            {/each}  
            
    </select>
{/if}
```
