### ISSUE TITLE
Gatsby / React Window is Not defined or ConversationalForm is not a constructor

### ISSUE THREAD

**Issue by joebentaylor1995** [space10-community/conversational-form#347]
CF obviously replies on window, which cant be used until componentDidMount... or else you get the error in build of ``window is undefined`` etc etc.

I've tried requiring the file after this, and I then get the error of
``ConversationalForm is not a constructor``

Surely theres got to be an easier way to get around this?

My codes pretty simple at the moment:

```
import React from 'react';
import { ConversationalForm } from 'conversational-form';

class Form extends React.Component {
    activateForm = () => {
        var ConversationalForm = require("conversational-form");
        const cfInstance = new ConversationalForm({
            formEl: this.contactForm,
            context: this.formJacket
        });
    }

    render() {
        return (
            ... Not needed to show at this point
        );
    }

    componentDidMount() {
        this.activateForm();
    }
}

export default Form;
```

**Comment by jenssogaard** [comment]
Hi @joebentaylor1995. Just remove the import on line 2 and replace the require with this line:
`const { ConversationalForm } = require("conversational-form");`

And I would like to remove the use of window from this project. It's somewhat of a legacy-issue...

**Comment by joebentaylor1995** [comment]
@jenssogaard Awesome, cheers!
