### ISSUE TITLE
The Scroll is not showing inside the conversational form 

### ISSUE THREAD

**Issue by lujain-abaki** [space10-community/conversational-form#348]
Please if you can help out with the below: 
- The scroll to show all messages is Hidden- when i click on the option it shows then disappears. 
Another question: 
How to prevent auto focus because once the page is loaded it auto scroll to the conversational form section. 
Appreciate your help - i am using Mozilla Firefox newest version.

**Comment by jenssogaard** [comment]
Hi @lujain-abaki. Please see the [docs](https://space10-community.github.io/conversational-form/docs/1.0.0/options/) and find `preventAutoFocus` :)
