### ISSUE TITLE
Skip "disabled" fields

### ISSUE THREAD

**Issue by ssteynfaardt** [space10-community/conversational-form#35]
**Issue:**
The form currently expects input from the user for all fields, including disabled fields.

**Expected behavior:**
The disabled attribute is a boolean attribute.
When present, it specifies that the `<input>` element should be disabled.
A disabled input element is unusable and un-clickable.
The disabled attribute can be set to keep a user from using the `<input>` element until some other condition has been met (like selecting a checkbox, etc.). Then, a JavaScript could remove the disabled value, and make the <input> element usable.

How it should work with conversational form is open for debate, but here is the way I see it working.

1. When creating the tags add all fields including the disabled fields.
2. Before asking the next questions, check if the form element is disabled
3. If the `<input>` is disabled, skip the question and move on to the next question.

**How to test:**
Add the `disabled` attribute to a form input
```HTML
<input type="text" name="name" cf-questions="Good day what's your name?" disabled="disabled" >
```
The question should not appear if the input is still disabled.

**Comment by felixnielsen** [comment]
@ssteynfaardt good observation. It makes sense to check at runtime if the ITag is disabled or has has changed to disabled.

**Comment by Toilal** [comment]
Maybe it could display a message instead of only skipping it. 

Also, a form field can be [readonly](http://www.w3schools.com/tags/att_input_readonly.asp), maybe we could have a distinct behaviour between disabled and readonly.
