### ISSUE TITLE
How I can use Conversational Form with Nuxt.js?

### ISSUE THREAD

**Issue by devmansurov** [space10-community/conversational-form#350]
I seen demonstration of this repository with Vue.js [here](https://stackblitz.com/edit/vue-conversational-form-example) but when I install it in nuxt js and use get error message:

> window is not defined

Then I solved it by requiring Conversational Form inside `mounted()` hook:

```
mounted: function() {
  var cf = require('conversational-form')
  this.setupForm()
},
```
But when `cf` called inside of any **methods** return error message:

> "cf" is not defined

Example method:

```
setupForm() {
  const formFields = [
    {
      tag: 'input',
      type: 'text',
      name: 'firstname',
      'cf-questions': 'What is your firstname?'
    },
    {
      tag: 'input',
      type: 'text',
      name: 'lastname',
      'cf-questions': 'What is your lastname?'
    }
  ]

  this.cf = cf.startTheConversation({
    options: {
      submitCallback: this.submitCallback
    },
    tags: formFields
  })
  this.$el.appendChild(this.cf.formEl)
}
```

How I can fully integrate this repository with nuxt js correctly? Thanks!

**Comment by jenssogaard** [comment]
Try const { ConversationalForm } = require('conversational-form');

Also you assign `var cf` inside mounted, but you are trying to access it in another function. I believe you have a scope issue. Maybe this is your answer:
`this.cf = require('conversational-form');`

I hope it helps.

**Comment by devmansurov** [comment]
> Try const { ConversationalForm } = require('conversational-form');
> 
> Also you assign `var cf` inside `mounted()`, but you are trying to access it in another function. I believe you have a scope issue. Maybe this is your answer:
> `this.cf = require('conversational-form');`
> 
> I hope it helps.

Now I created new [codesandbox](https://codesandbox.io/embed/codesandbox-nuxt-conversational-form-ssxnf) with conversational form and now I don't have any errors on console but conversation view is not display. Please see where I have errors in my code.

**Comment by jenssogaard** [comment]
@devmansurov it seems you got it sorted on your own? https://www.dropbox.com/s/xdqrwv2gw3wtunh/Screenshot%202019-10-29%2021.26.30.png?dl=0
