### ISSUE TITLE
How I can make conversational form responsive for mobile devices?

### ISSUE THREAD

**Issue by devmansurov** [space10-community/conversational-form#353]
I use conversational form in my project with JQuery. I seen what current version of the repository is not responsive for mobile devices. On mobile devices messages is smaller then PC.

You can see here result on mobile device [here](https://imgur.com/a/2VATBmT)

[Here ](https://imgur.com/a/SGdiA7q)you can see PC version result

How I can solve problem with design & style on mobile devices?

**Comment by jenssogaard** [comment]
Hi @devmansurov. It is indeed response. Have you tested on an actual device? Try the [landingpage](https://space10-community.github.io/conversational-form/landingpage/) for instance and you see it renders nice and pretty.

**Comment by amulyaparmar** [comment]
Hi @jenssogaard @devmansurov, I actually had the same problem.

One thing I am not sure about is whether we need put our own container around the form?

I have noticed the landing page instance has a container around the form.

How would we add a container around this form?? Nothing I do seems to be containerize the form

**Comment by amulyaparmar** [comment]
Also I am using cf-form script (one line embed), not using NPM
