### ISSUE TITLE
using the select and options tags in formless

### ISSUE THREAD

**Issue by keyboardbreaker** [space10-community/conversational-form#362]
I've been following the [Angular](https://space10-community.github.io/conversational-form/docs/1.0.0/getting-started/#angular) guide to making a formless conversational form.

It's unclear how to add select tags then child options with the select tags.

how would you make this excerpt formless?

```
<select id="color" multiple>
		<option val="red">red</option>
		<option val="blue">blue</option>
		<option val="green">green</option>
		<option val="other">other</option>
</select>
```

**Comment by keyboardbreaker** [comment]
ok I found it, admittedly I should have tested the [formless example](https://space10-community.github.io/conversational-form/docs/0.9.80/functionality/formless/) more.

```
    {
      'tag': 'select',
      'name': 'af',
      "cf-questions": "First tag value: {first-tag}&& + follow-up",
      "cf-input-placeholder": "Some copy",
      'isMultiChoice':false,
      "children":[
        {
            "tag": "option",
            "cf-label": "USA",
            "value": "usa"
        },
        {
            "tag": "option",
            "cf-label": "UK",
            "value": "uk"
        }
      ]
    },
```

**Comment by danileao** [comment]
Did you get to use 'cf-input-placeholder' with tag select?

**Comment by keyboardbreaker** [comment]
> Did you get to use 'cf-input-placeholder' with tag select?

I opened another issue:
https://github.com/space10-community/conversational-form/issues/364
