### ISSUE TITLE
Form not rendering in Firefox

### ISSUE THREAD

**Issue by richardhj** [space10-community/conversational-form#365]
The form is not rendered nor generated in current Firefox.
I cannot see the demo on your website. I disabled "enhanced protection" in Firefox, as it may be subject to change the block contents on the website. No errors in the console.

![Screen Shot 2019-11-07 at 14 58 00](https://user-images.githubusercontent.com/1284725/68363709-23b0ac00-016f-11ea-98fd-4e62951c4522.png)

IMHO not related to #316

**Comment by jenssogaard** [comment]
@richardhj thanks for reporting. This has been fixed. Purely an implementation issue on the landingpage - it had nothing to do with CF.
