### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by ImaCrea** [space10-community/conversational-form#397]
Hi there,
thank you for such work. It's stunning and I'm very interested in playing with it. Still, before starting I checked a bit the activity around and it looks like the projet is not really moving forward at the moment. Was it a one-shot project or is there any community around maintaining it?

cheers

**Comment by sashareds** [comment]
Wondering as well. 
I am looking for a tool/framework to create a small but fun and engaging questionaire this popped in google. Looks very promising

**Comment by cgarrovillo** [comment]
Looks to be one shot at this point.

**Comment by pfortes** [comment]
I just implemented it and it works great for what i needed.

**Comment by ImaCrea** [comment]
I guess we all have the answer now. I close the ticket.
