### ISSUE TITLE
Form Primer Responses

### ISSUE THREAD

**Issue by iamtheream** [space10-community/conversational-form#40]
For an added level of conversation, I was wondering if there is a way to tag an element that, on page load or whenever in the form, would trigger a timed response. For example, if I wanted to welcome guests when they first arrive on the form, wait 2-3 seconds then prompt them with the first input field.

**Comment by felixnielsen** [comment]
@iamtheream we are working on a welcome (could be used in your case) and bye messages, will be pushed out next week.

You can also instantiate the form yourself, like, psuedo code:
```javascript
setTimeout( () => {
   // check https://github.com/space10-community/conversational-form#self-instantiate-with-vanilla-js
}, 3500);
```

Here you should avoid the `cf-form-element` attribute
