### ISSUE TITLE
How to fit in a structured page?

### ISSUE THREAD

**Issue by airjoshb** [space10-community/conversational-form#41]
How do you have it fit into columns, such as in your demo? When I add it to the page, it takes over the whole thing.

**Comment by felixnielsen** [comment]
hi @airjoshb please use the `cf-context` attribute to append the Conversational Form into a different context than the body, as described [here](https://github.com/space10-community/conversational-form#optional-attributes)

If you are doing it manually you can use `context` parameter as described [here](https://github.com/space10-community/conversational-form#parameters-to-pass-the-constructor-of-conversationalform-conversationalformoptions)

**Comment by xerosanyam** [comment]
I am facing the same problem. It appears like following:
![image](https://cloud.githubusercontent.com/assets/3167278/22617405/a47781cc-eaea-11e6-84c7-4da2b93e1b9e.png)

**Comment by felixnielsen** [comment]
@xerosanyam are you adding the `cf-context` attribute on the element where you want to append conversational form?

**Comment by xerosanyam** [comment]
I am doing it via `context: document.getElementById("formOuter")` but tried the `cf-context` also, still getting same result.

**Comment by felixnielsen** [comment]
@xerosanyam `cf-context`you did it like [this?](https://jsfiddle.net/xfufbwo8/)

**Comment by xerosanyam** [comment]
yes

**Comment by felixnielsen** [comment]
@xerosanyam ok, please supply more info for me to able to help you out.
