### ISSUE TITLE
Suppress default cf-questions in fieldset tags

### ISSUE THREAD

**Issue by MackoHacko** [space10-community/conversational-form#416]
Is there a way to suppress the default _"I need you to select one of these"_  behaviour of `cf-questions` in `fieldset` tags? See screenshot:

![image](https://user-images.githubusercontent.com/32510775/96254347-6e5cba00-0fb5-11eb-841d-46b4b12be90e.png)

All I want is the OK radio button.

**Comment by yzalvov** [comment]
@MackoHacko I'm happy you found the answer. Would you be so kind to share though?
