### ISSUE TITLE
Next.JS Compatibly

### ISSUE THREAD

**Issue by jonrrivera** [space10-community/conversational-form#418]
Installing this dependency via NPM on a Next.JS v10 project gives this error. It usually has to do with SSR. 

<img width="1004" alt="Screen Shot 2020-11-10 at 11 11 21 AM" src="https://user-images.githubusercontent.com/18686388/98721441-a9000b00-2345-11eb-895f-5618cb639b34.png">

**Comment by pfortes** [comment]
Duplicate of  #297

**Comment by jonrrivera** [comment]
see #297 for solution
