### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by hamaff** [space10-community/conversational-form#43]
**Issue:**
There is no validation of the fields. 
Example: email field
When user is writing an invalid email there is no validaiton.
If the server return an invalid message the user must fill all of the fields again.

**Expected behavior:**
 There should be realtime validation or validation on submit with option to edit fields.

**Comment by m1guelpf** [comment]
+1 for this

**Comment by felixnielsen** [comment]
@hamaff @m1guelpf please see the readme file, you have multiple options to validate at runtime.

pattern attribute: `<input type="email" pattern="/(\w+)\@(\w+)\.[a-zA-Z]/g"` [link](https://github.com/space10-community/conversational-form#input-pattern-attribute)

or/and `cf-validation`: [link](https://github.com/space10-community/conversational-form#cf-validation)

and you have `submitCallback`: [link](https://github.com/space10-community/conversational-form#parameters-to-pass-the-constructor-of-conversationalform-conversationalformoptions)

Regarding edit previous fields then this is already an [open issue](https://github.com/space10-community/conversational-form/issues/9) waiting to be implemented in an upcoming version.

**Comment by hamaff** [comment]
```
<div class="form-group">
   <label for="your-email">Email</label>
   <input cf-questions="..." pattern="/(\w+)\@(\w+)\.[a-zA-Z]/g" type="email" class="form-control" name="your-email" id="your-email">
</div>
```

When I enter "example@email.com" that should be a valid email the validation says that its NOT valid. I think it doesnt work properly.

**Comment by felixnielsen** [comment]
@hamaff sry, the e-mail regex was just a quick copy-paste from the interwebs. You should find a regex that works for you.
Validation works fine: [jsbin](https://jsbin.com/xodusumala/edit?html,js,output)

**Comment by slowflyer** [comment]
I'm struggling with the same problem, no matter what pattern I tried, validation never succeed.

**Comment by felixnielsen** [comment]
@slowflyer @hamaff  please see this [jsbin](https://jsbin.com/zepelihece/1/edit?html,js,output)

@hamaff you need to exclude the modifier /g and starting forward slash.
[valid regex](https://regex101.com/r/zckq85/1/)
[not valid regex](https://regex101.com/r/qHai7g/1)

**Comment by slowflyer** [comment]
:+1: got it! Thanks!

**Comment by chug2k** [comment]
Just leaving a note here in case anyone else has this issue ... it took me longer than I'd like to admit to realize that when you are creating formlessly, you need to escape the backslashes in the string, so: `pattern: '(\\w+)\@(\\w+)\\.[a-zA-Z]'`.
