### ISSUE TITLE
End the conversation before the end of the form

### ISSUE THREAD

**Issue by christophe77** [space10-community/conversational-form#44]
I was wondering if it was posible to make the form end prematurely when clicking on an answer.
In case of a customer interview for exemple, if the customer is not in the age range that interests the reviewer then the form needs to end.

**Comment by felixnielsen** [comment]
hi @christophe77 you can do this by adding a validation method as described [here](https://github.com/space10-community/conversational-form#cf-validation) then you can check if `value` is what you expect else you can call: 
```javascript
window.ConversationalForm.remove();
```
