### ISSUE TITLE
Question: how to use textarea as an input

### ISSUE THREAD

**Issue by andrewskip** [space10-community/conversational-form#45]
Awesome job guys! I'm a university student and I'll use your code for a project in computer programming 1 course. My problem is that I can't use a <textarea> instead of an <input> field: in fact I want to ask a longer question to the user. It seems that the code only accepts input fields, the following code doesn't work:

 <div class="form-group">
                      <label for="your-trip">Describe your summer trip</label>
                      <textarea form="conversational" cf-questions="Great {previous-answer}! Could you describe your last summer trip in less than 250 words?" class="form-control" name="your-trip" id="your-trip"></textarea>
                    </div>

How can I use a textarea with your code? Sorry if this is a stupid question, I'm a real beginner! Thanks, Andreas

**Comment by felixnielsen** [comment]
@andrewskip great that you have a use for it! atm. it does not accept textarea...
I have added it to version 0.9.0 which will be pushed very soon.

**Comment by andrewskip** [comment]
Great, thank you!

**Comment by inthecompanyof** [comment]
I'm also excited to hear that this functionality is being offered. 👍

**Comment by hamaff** [comment]
it should be great too if you can make cf-questions multiple lines

**Comment by felixnielsen** [comment]
@hamaff you can just include a </br> tag in the string.
