### ISSUE TITLE
Redirecting to Different URL on Radio Option

### ISSUE THREAD

**Issue by iamtheream** [space10-community/conversational-form#46]
I was wondering how I would go about redirecting the user to a different URL based on their decision on a specific radio input?

**Example Use Case**: I want to start this conversational form out with an option for the guest to go to a more traditional form instead of continuing down the conversational path. By giving the guest 2 radio options in the first input response, I want to redirect to a traditional form if that option is chosen. 

I've tried using the `onclick = "document.location.href='page.html'" ` and a few other methods using _JS_ and _AJAX_.

**Comment by felixnielsen** [comment]
@iamtheream you can do this in two ways:
Here at the "end" of the form tag [setup your own callback]([url](https://github.com/space10-community/conversational-form#parameters-to-pass-the-constructor-of-conversationalform-conversationalformoptions)) via `submitCallback` option.

Alternative, you can use [cf-validation](https://github.com/space10-community/conversational-form#cf-validation)

**Comment by iamtheream** [comment]
@felixnielsen I'm not sure how to use `submitCallback` or `cf-validation` to solve the redirect use case I'm trying to solve for. Any advice?

**Comment by felixnielsen** [comment]
@iamtheream maybe I am misunderstanding. Let me disect.

1. you want to instantiate the Conversational Form upon a users interaction. ex. choosing a specific radio button.
Here I would use [onchange](http://www.w3schools.com/jsref/event_onchange.asp)
Together with instantiating Conversational Form [manually](https://github.com/space10-community/conversational-form#self-instantiate-with-vanilla-js)

2. If you want to open a new window upon an answer from a user (within Conversational Form), then see this [jsbin](https://jsbin.com/canapoluqa/1/edit?html,js,output)

**Comment by iamtheream** [comment]
Thanks for your help @felixnielsen I was trying `onchange=""();`methods but was not seeing any change. Now I realize that I was not instantiating for form manually. 

To call the `$("#formId").conversationalForm();` I should put it in the `head` right?

**Comment by felixnielsen** [comment]
@iamtheream I would call `$("#formId").conversationalForm();` from within your `onchange` handler, if the user-choice is "correct".

**Comment by iamtheream** [comment]
I've tried to do so, but when I remove the `cf-form-element` from the `form` HTML element the functionality is gone. Maybe I'm missing a critical step here. Thanks for your support, it's much appreciated [[roxsign]]

**Comment by iamtheream** [comment]
@felixnielsen in the example [jsbin](https://jsbin.com/canapoluqa/1/edit?html,js,output) you posted a few comments up, I cannot continue without typing "stackoverflow". Is there a way that instead of retuning false, it could skip to the next input questions?

**Comment by felixnielsen** [comment]
@iamtheream jsbin is using a pattern attribute on the field, you can just remove it (readme file for full feature description) regarding your issue, then please make a jsbin and share it.
