### ISSUE TITLE
Multiple one way data binding values

### ISSUE THREAD

**Issue by dstollie** [space10-community/conversational-form#47]
Currently I only see support for `{previous-answer}` It would be cool if there is an api to add custom data binding values. For example; currently im looking for a way to get the value of a property of a few inputs ago.

Name
Age
Mood

In mood I want to ask the questions: So you're {age}. Tell me {name} how do you feel today?

**Comment by felixnielsen** [comment]
@dstollie you think this should only be based on the previous answer or should it apply to all previous answers?

ex.: "Hello {firstname}, people taller than {height}, seem to be taller.."

**Comment by danielfriis** [comment]
I see this as a duplicate of the piping part of https://github.com/space10-community/conversational-form/issues/11

**Comment by felixnielsen** [comment]
@dstollie please see latest [release](https://github.com/space10-community/conversational-form/releases/tag/v0.9.4) and example [value-piping](https://space10-community.github.io/conversational-form-docs/value-piping.html)
