### ISSUE TITLE
Validation in the form

### ISSUE THREAD

**Issue by muskanup** [space10-community/conversational-form#48]
I am concerned about how these forms fields would be validated. Please help me out with the same.

**Comment by felixnielsen** [comment]
hi @muskanup let me know your concerns :) you can use standard pattern [attr](https://github.com/space10-community/conversational-form#input-pattern-attribute) and/or use javascript [validation](https://github.com/space10-community/conversational-form#cf-validation) finally you can validate all the fields via the [submitCallback attribute](https://github.com/space10-community/conversational-form#parameters-to-pass-the-constructor-of-conversationalform-conversationalformoptions)
