### ISSUE TITLE
Balnk Screen Area Form Upper side

### ISSUE THREAD

**Issue by JakSat** [space10-community/conversational-form#50]
First of all, many congratulations for thinking different and better way.

I notice that the form make blank space upper side when size of form is big. Is there anyway the flow of the interaction show the following things as

1. move from top to bottom side
2. the size of form increases as per questions and answer.
3. Also it is shows the existing style of form before showing the conversational form

I will really appreciate, if you could fix these things.

**Comment by felixnielsen** [comment]
hi @JakSat , awesome you can use it.

Conversational Form is made so you are in full control.
1. You are able to inject Conversational Form to a different context (element), see `cf-context` [here](https://github.com/space10-community/conversational-form#optional-attributes)
2. You can easily overwrite styles as you see fit, making it resize to it's context.
3. Conversational has a default look, you can easily overwrite this as Conversational Form is an element injected into your local dom.
