### ISSUE TITLE
Is it possible to turn off the human reply dots (…)

### ISSUE THREAD

**Issue by joakimc** [space10-community/conversational-form#52]
When testing the form on others, someone commented that it looked like someone else was typing while they were typing. I think I agree – there's no reason to visually indicate that the user are typing, and it might be a distraction.

**Comment by danielfriis** [comment]
@joakimc it's a very valid point. We're considering whether this should be removed for the `1.0.0` release. Until then, you can remove the typing by `cf-chat-reponse thinking{display: none !important;}`

**Comment by joakimc** [comment]
Thanks! I removed it with `cf-chat-response text[thinking] {display: none !important;}` to hide the bubble is as well while typing.
