### ISSUE TITLE
Be very cautious deploying this to your LIVE server...

### ISSUE THREAD

**Issue by haktansuren** [space10-community/conversational-form#53]
We have just got our server flagged as "phishing website" because of the file `test/classic.airbnb.html` (by phishlabs.com in northon + cloudflare) 

I suggest the author to remove the file from the repo.

**Comment by felixnielsen** [comment]
@haktansuren why would you put test/classic.airbnb.html on your server??

**Comment by felixnielsen** [comment]
And please rename the Title as it is very misleading ...

**Comment by haktansuren** [comment]
@felixnielsen because I thought this was the repo for the demo here [https://space10-community.github.io/conversational-form/](url)

**Comment by haktansuren** [comment]
Why would you have the clone of airbnb website on repo @felixnielsen?

**Comment by felixnielsen** [comment]
@haktansuren for test purpose ... However you illustrated that one should expect people would deploy/publish all code and therefore a disclaimer and howto will be written into the readme, also those test files will be removed to prevent the possibility 👍 

For reference; files to be deployed to a server is either in the **/dist** folder or if you build the project yourself from a forked repo, then files in **/build** could be deployed again (if your server utilises http/2?) or you would use `$gulp dist` to compile distribution files to **/dist**
