### ISSUE TITLE
How to validate minimum maximum value in text field?

### ISSUE THREAD

**Issue by ssrgspdkt** [space10-community/conversational-form#56]
Currently it supportes validation only for radio and select . I need validation based on my 
`<input cf-questions="questions" type="number" class="form-control" name="coverage-term" id="coverage_term" min="1" max="30">`
currently no errors appearing when I enter more than 30.

**Comment by felixnielsen** [comment]
@ssrgspdkt correct, min and max are not implemented.
You can use pattern attribute instead:
````html
<input cf-questions="questions"  type="number" class="form-control" name="coverage-term" id="coverage_term" pattern=".{1,30}" required>
````

**Comment by renatodeleao** [comment]
@felixnielsen, can't validate a number between 1-10 using standard HTML5 min max, or pattern attribute, or mix of both on `<input type="number" />`
[demo](http://jsfiddle.net/tg3fpjgk/)
Is this expected or should i move this kind of validation to the `flowStepCallback`?
