### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by alvarengathomas** [space10-community/conversational-form#59]
First of all, thanks for open-source this idea and for the hard work, I'm really excited to use in my projects, but I'm insecure because the source code doesn't have any unit tests.

Is there any forecast for the implementation of the unit tests?

**Comment by felixnielsen** [comment]
hi @alvarengathomas awesome that you find the project interesting! Yep, unit-tests are apart of the 1.0.0 roadmap. Release date to be announced very soon.
