### ISSUE TITLE
Comparing entries

### ISSUE THREAD

**Issue by tadinski** [space10-community/conversational-form#62]
having the ability to compare a previous entry with the current one would be really helpful.
use case: entering password twice, to make sure they are identical

**Comment by felixnielsen** [comment]
@tadinski this will be added explicit to one of the up-coming version, before 1.0.0.

You are however able to do what you want with; `flowStepCallback`, this requires you to instantiate Conversational Form [manually](https://github.com/space10-community/conversational-form#self-instantiate-with-vanilla-js). `flowStepCallback` get's called on every step.

````javascript
new cf.ConversationalForm(<ConversationalFormOptions> {
    formEl: <HTMLFormElement>,
    flowStepCallback (dto: FlowDTO, success: () => void, error: () => void) => boolean {
        console.log(dto);
    }
});
````

The dto FlowDTO gives you an array of items where you can get current value value etc.

**Comment by felixnielsen** [comment]
`cf-value-equal={other-input-id}`
