### ISSUE TITLE
delay robot message

### ISSUE THREAD

**Issue by tadinski** [space10-community/conversational-form#63]
is there a way to add a bit of a delay before the robot sends the next field? I see you in your GIF you have that, with 3 dots as a loader...I was able to replicate it by showing and hiding fields, but isn't there a cleaner way?

**Comment by felixnielsen** [comment]
@tadinski you are able to do this using what I describe [here](https://github.com/space10-community/conversational-form/issues/62)

in `flowStepCallback``

````javascript
new cf.ConversationalForm(<ConversationalFormOptions> {
    formEl: <HTMLFormElement>,
    flowStepCallback (dto: FlowDTO, success: () => void, error: () => void) => boolean {
        console.log(dto);
        setTimeout( () => success(), 1000); // <-- delay the next step
    }
});
````

**Comment by xerosanyam** [comment]
what will be es5 code for this ? thanks

**Comment by felixnielsen** [comment]
````javascript
new cf.ConversationalForm({
    formEl: document.getElementsByTagName("form")[0],
    flowStepCallback function(dto, success, error) {
        console.log(dto);
        success();
    }
});
````

**Comment by jamiecounsell** [comment]
I may not understand, but this doesn't seem to work. The timeout fires before the user input is accepted, so it feels like the user's input is being delayed, not the robot's response. Also, this only fires when the field is marked as required.

**Comment by felixnielsen** [comment]
@jamiecounsell I understand, we will be releasing a minor release today/tmr, will see if I can add something that makes this easier to customise.
_As a reference, then we removed the "thinking" logic/delay we had in the beginning because feedback was that it slowed the form process down._

**Comment by jamiecounsell** [comment]
Thanks for the quick response. If you don't get to it, I'll see if I can submit a PR this weekend.
