### ISSUE TITLE
please assist with the build from src

### ISSUE THREAD

**Issue by conixit** [space10-community/conversational-form#73]
can someone zip up the entire compiled source, I am trying to use one of the examples and the linked js and css files are nowhere: I'm assuming I have to compile them somehow- I tried to install gulp, bower and node- and failed- I would really like to try some of the advanced features like if "no" then respond x, if "yes" then respond y.

 <link type="text/css" rel="stylesheet" href="../build/cf/cf.css"/>
  <link type="text/css" rel="stylesheet" href="../build/cf/ui/control-elements/cf-control-elements.css"/>
  <link type="text/css" rel="stylesheet" href="../build/cf/ui/control-elements/cf-button.css"/>
  <link type="text/css" rel="stylesheet" href="../build/cf/ui/control-elements/cf-radio-button.css"/>
  <link type="text/css" rel="stylesheet" href="../build/cf/ui/control-elements/cf-checkbox-button.css"/>
  <link type="text/css" rel="stylesheet" href="../build/cf/ui/control-elements/cf-options-list.css"/>
  <link type="text/css" rel="stylesheet" href="../build/cf/ui/control-elements/cf-upload-file-ui.css"/>
  <link type="text/css" rel="stylesheet" href="../build/cf/ui/cf-input.css"/>
  <link type="text/css" rel="stylesheet" href="../build/cf/ui/cf-info.css"/>
  <link type="text/css" rel="stylesheet" href="../build/cf/ui/cf-list-button.css"/>
  <link type="text/css" rel="stylesheet" href="../build/cf/ui/chat/cf-chat-response.css"/>
  <link type="text/css" rel="stylesheet" href="../build/cf/ui/chat/cf-chat.css"/>

**Comment by felixnielsen** [comment]
@conixit here you go: https://dl.dropboxusercontent.com/u/4512798/0.9.1-compiled.zip
This is the version which we will release tmr, please see documentation on [develop branch](https://github.com/space10-community/conversational-form/tree/develop)
