### ISSUE TITLE
A little scroll

### ISSUE THREAD

**Issue by allantorres** [space10-community/conversational-form#75]
Does any one can help me with this little scroll when the chat hits the top? 

http://201.30.147.89/bot/

**Comment by felixnielsen** [comment]
@allantorres you mean inline scroll?

**Comment by felixnielsen** [comment]
@allantorres please see version [0.9.1](https://github.com/space10-community/conversational-form/releases/tag/v0.9.1) readme is also updated with [0.9.1](https://github.com/space10-community/conversational-form#getting-started)
