### ISSUE TITLE
Inputs as radio Buttons are not appearing anymore

### ISSUE THREAD

**Issue by dominatelj** [space10-community/conversational-form#80]
The Inputs that appears as radio buttons in the Bot is not appearing anymore please if there is any suggestion let me know

**Comment by felixnielsen** [comment]
hi @dominatelj can you please direct me to where you experience this.
When I run tests, then it is working as expected.

Two versions are in play:

<script type="text/javascript" src="https://conversational-form-091-0iznjsw.stackpathdns.com/conversational-form.min.js" crossorigin></script>


<script type="text/javascript" src="https://conversational-form-0iznjsw.stackpathdns.com/conversational-form.min.js" crossorigin></script>

**Comment by dominatelj** [comment]
I am using it on localhost for testing, included the JS and CSS files and everything is running, just the inputs of type radio is not appearing. 
Can u provide me with updated JS and CSS files ? 
since it's been more that two months i got the source code. 
Thanks a lot

**Comment by felixnielsen** [comment]
@dominatelj you can download 0.9.1 from the [release](https://github.com/space10-community/conversational-form/archive/v0.9.1.zip) use the files in /dist folder.
For build files then check [README](https://github.com/space10-community/conversational-form#build-the-source)
Or let me know and I can zip the files for you.

**Comment by dominatelj** [comment]
Thank a lot 👍
