### ISSUE TITLE
Could wit.ai be integrated?

### ISSUE THREAD

**Issue by felixnielsen** [space10-community/conversational-form#81]
[https://wit.ai/](https://wit.ai/) or similar libraries

**Comment by rmaspero** [comment]
Would love this. A nice simple conversational UI that you could embed into your site using JS that uses the Wit.ai brains would be so cool.

**Comment by MediacraftFR** [comment]
100% agree with that, wit.ai or custom API to control next question according to previous answer would be awesome

**Comment by uffou** [comment]
+1

**Comment by lucaydaniel** [comment]
+1 seriously needed for real-world scenarios! (e.g. I am placing an order at the restaurant thorugh the chat interface)
