### ISSUE TITLE
getFormData empty?

### ISSUE THREAD

**Issue by siliconkibou** [space10-community/conversational-form#82]
Hi guys...great concept.  I'm doing a custom AJAX query with submitCallback but I can't seem to get the form data.

The form itself seems to not change (all values are default if I serialize the form), and window.ConversationalForm.getFormData() seems to be empty.

I'm sure I'm missing something really obvious, but I'm at a loss as to what.

Any thoughts?

Thanks,

-Paul

**Comment by felixnielsen** [comment]
hey @siliconkibou , great you like it.
FormData is an elusive one, normally when values of a FormData is empty, it is because [name-attribute](https://www.w3schools.com/tags/att_input_name.asp) is missing from the tag.

See this working [example](https://jsbin.com/nuxecizogi/1/edit?html,js,output)

**Comment by siliconkibou** [comment]
Thanks...I'm sure it's something obvious, but that's not it.  Everything has name attributes.

var formData = kvcfform.getFormData() returns undefined.

Here's the essence of my code:

var KvcfForm = new cf.ConversationalForm({
    formEl: document.getElementById('ftrpformnewcf'),
    context: document.getElementById('splashholder'),
    submitCallback: function() {

      var formData = KvcfForm.getFormData();
            for (var value of formData.entries()) {
              console.log("form data value:", value); 
            }

}

**Comment by felixnielsen** [comment]
@siliconkibou implementation looks fine.
Can you add your form markup?
And let me know which version you include.
