### ISSUE TITLE
Label lookup, edge-case

### ISSUE THREAD

**Issue by felixnielsen** [space10-community/conversational-form#83]
Add logic to look for the `for` attribute when meeting specific cases like:

````html
<label for="fruit-apples">Apples</label>
<input type="checkbox" id="fruit-apples" value="apples">

<label for="fruit-bananas">Bananas</label>
<input type="checkbox" id="fruit-bananas" value="bananas">

<label for="fruit-burger">I hate fruit, give me burger instead</label>
<input type="checkbox" id="fruit-burger" value="burger">
````
Where `label` and `input` fields are stacked and not wrapped in an outer element, like shown [here](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_structure_an_HTML_form#The_<fieldset>_and_<legend>_elements)

It seem to go against [standards](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_structure_an_HTML_form) to not have an wrapping element, but this structure still renders valid.

**Comment by bduff9** [comment]
Hi there, I appreciate your work very much and have been lurking watching its progress.  Just a quick question on this comment:
`This goes against standards, but it seem to be common practice.`

I had always understood standards with labels to be to either wrap the input with the label to set up an implicit association or to pass the `for` attribute when not nested to set up an explicit association.  However, it seems from your comment that you are saying the `for` attribute goes against standards.

I clicked the link you provided to see for myself, however in that link under Labels, it specifically says it is best practice to always pass the `for` attribute in labels, regardless of if the associated input is nested or not.  When you have a moment, I would just be curious if you meant something else or what I am not understanding about your comment.  Thanks in advance!

**Comment by felixnielsen** [comment]
hi @bduff9, I see my description was to vague (it has been updated), and could easily cause confession.. Conversational Form implements the lookup for the `for` attribute (which is most defiantly a standard), but it does not accommodate the scenario described above, where we have many input and label elements stacked in the same element.

**Comment by bduff9** [comment]
Ah, thank you very much for clarifying!  Just wanted to make sure I understood
