### ISSUE TITLE
IE browser compatibility 

### ISSUE THREAD

**Issue by samail** [space10-community/conversational-form#84]
Hi,

Could you please let us know for which version of Internet Explorer this awesome plugin works ? 
Looks like it's not for IE11 (win7 & win8), is this better with Edge ? 

Thanks a lot 
Best

**Comment by felixnielsen** [comment]
hi @samail can you please try the latest push to master and update to [v0.9.1](https://github.com/space10-community/conversational-form/releases/tag/v0.9.1)
Tested (and fixed) it in win8 IE11.

**Comment by samail** [comment]
Hi @felixnielsen, 
Thx for the quick reply and the fix
I'll give a try and i let your know asap
Best

**Comment by samail** [comment]
Hi @felixnielsen,
Seems to be working under win81 IE11
Thx ;)

**Comment by AfaanBilal** [comment]
Hi,
On Windows 10, IE 11, the chat area doesn't scroll so the input box as well as the option inputs are inaccessible.
Any fix?
Thanks!
