### ISSUE TITLE
cf-input-placehoder not working

### ISSUE THREAD

**Issue by fotuzlab** [space10-community/conversational-form#89]
> cf-input-placeholder
> 
> tag specific, set the placeholder text on the UserInput field
> <input type="text" cf-input-placeholder="Should include http" ..

This is not working for me. Any clues?

I am using following js to enable CF on my form
`<script type="text/javascript" src="https://conversational-form-091-0iznjsw.stackpathdns.com/conversational-form.min.js" crossorigin></script>`

**Comment by felixnielsen** [comment]
hi @fotuzlab do you have the `value` attribute set to something else than ""? `value` will overwrite the cf-input-placeholder

See working example [here](https://jsbin.com/wivebenuto/1/edit?html,js,output) that also is illustrates the value scenario.

**Comment by fotuzlab** [comment]
Thanks @felixnielsen for the promt response and the example. Let me try it.

**Comment by fotuzlab** [comment]
I checked that value attribute in my form is empty. Hence should not be an issue.
Here is the form markup https://jsbin.com/pojibuxisu/edit?html,js,output
I assume it has to do something with styling looking at the two user input fields in jsbin above.

**Comment by felixnielsen** [comment]
@fotuzlab when I check out the jsbin `cf-input-placeholder` is working as expected.
see my slightly modified [version](https://jsbin.com/telipozoca/1/edit?html,js,output)
Can you clarify what is not working as expected?

**Comment by fotuzlab** [comment]
I think the issue is not with the library but my implementation or the theme I am using.
I am trying to create a Drupal module for integration with CF https://github.com/fotuzlab/conversational-forms-drupal . Let me dig into what is going wrong.
I will follow up with my findings.

**Comment by felixnielsen** [comment]
@fotuzlab ok, looking forward to hearing about your findings w. Drupal integration.

**Comment by fotuzlab** [comment]
`cf-input-placeholder` works when script is added directly in the Drupal's template file. However, it is not working when added through [drupal_add_js](https://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_add_js/7.x) function.
It's a drupal specific issue :|

Thanks @felixnielsen for help in debugging.

**Comment by felixnielsen** [comment]
@fotuzlab good to know, please let me know if I can further help debug.
