### ISSUE TITLE
Edit previous answers

### ISSUE THREAD

**Issue by danielfriis** [space10-community/conversational-form#9]
Would be nice to be able to go back and change an answer you already provided.

**Comment by DeanWard** [comment]
When typing on skype they detect if you send the same message again with small changes and mark it as an edit. Something like that might work well here, too?

**Comment by onzemark** [comment]
Editing it conversationally would be awesome, but require quite some AI I recon. Fixing a typo with "Oops I meant to say Mark" after typing _Makr_ for instance.

**Comment by hessius** [comment]
(As mentioned on ph) I've done something similar to this but non dynamic, I solved this issue by grouping questions together and asking if they were correct, e.g. "so before we move on Daniel, is it correct that your telephone number is xxx and your home address is yyy" yes/no. If user selects "no": "okay, let's fix that! What part of the info was incorrect? Name/number/address"

It's a bit of a round about way but when the info is correct it is really a minimal bother and can fit right into a natural-ish conversation (with improved copy), for the person correcting their answers I think that in my limited testing this method is acceptable

**Comment by RafaelDavisH** [comment]
Since the idea is to have a form completed as a conversation - more like messaging I would say -, then some of the functionalities that messaging has like auto-capitalization, auto-correction, check spelling and predictability that could minimize the errors submitted. Although, if applicant wants to change any answers and go back, maybe the applicant can have an option to flag or mark the questions which can later be revised.

**Comment by gytdau** [comment]
What if they could click on the message they sent and edit it? That'd be the most intuitive and simple.

**Comment by felixnielsen** [comment]
@hessius I like that idea, this could be implemented quite easily through attributes ex.: `<input cf-validate-previous-answers="are you happy with your previous answers?"...`, together with @gytdau suggestion — which we are implementation as we speak — it would be an simple implementation.

@RafaelDavisH regarding errors submitted then we rely on the [pattern](http://www.w3schools.com/tags/att_input_pattern.asp) attribute and other attributes like selects [multiple](http://www.w3schools.com/tags/att_select_multiple.asp) to prevent faulty values being submitted. Combined with the tag level `cf-validation` attribute, see [here](https://github.com/space10-community/conversational-form#cf-validation) would get you far regarding value validation.
Auto-capitalization, auto-correction, check spelling, predictability etc. is quite project-specific I think and is not something that everyone wants. But this question opens up for the discussion to have a feature that would give a developer control over a value once it is submitted.
