### ISSUE TITLE
Make it possible to disable console log output in production

### ISSUE THREAD

**Issue by query-string** [space10-community/conversational-form#91]
I think it would be nice to disable console log messages until this option is enabled explicitly.
Otherwise browser log looks too verbose and it is no way to get rid of unnecessary messages unless all console.log statements removed from the source code manually. 
![image](https://cloud.githubusercontent.com/assets/160712/23933780/61d360f0-0973-11e7-8396-ddb34162c183.png)

**Comment by felixnielsen** [comment]
@query-string yes! It is on it's way. Will be shipped with release this week.
