### ISSUE TITLE
Can you publish to npm?

### ISSUE THREAD

**Issue by kalinchernev** [space10-community/conversational-form#93]
Hi guys,
Thanks for your work on this project and providing it for free under MIT!
Do you have any plans of providing the package on npm?
Thanks!

**Comment by felixnielsen** [comment]
@kalinchernev check [release v0.9.2](https://github.com/space10-community/conversational-form/releases/tag/v0.9.2)

**Comment by kalinchernev** [comment]
Thanks @felixnielsen !
