### ISSUE TITLE
Bug: Checkbox values set to "1" or "0".

### ISSUE THREAD

**Issue by AfaanBilal** [space10-community/conversational-form#98]
On selecting or unselecting checkboxes, CF sets the values to 1 or 0. This wouldn't be a problem with single checkboxes but when using multiple checkboxes with the same `name` field (eg `name=field1[]`), it becomes impossible to get which checkboxes were selected. Please fix!

**Comment by felixnielsen** [comment]
hi @AfaanBilal hotfix pushed to v0.9.2 + cdn is updated as well. Let me know if hotfix is sufficient.

**Comment by AfaanBilal** [comment]
Hey @felixnielsen It's working! Thanks a lot for the quick fix!

**Comment by felixnielsen** [comment]
@AfaanBilal great, no problem!
